### ISSUE TITLE
Display whether a submission passes the tests

### ISSUE THREAD

**Issue by LegalizeAdulthood** [exercism/exercism.io#1710]
I think it would be useful to know when a submission passes the tests and if it is failing some tests, which tests it is failing.  I'm not sure how this would be implemented; I think it would have to be some weird forked travis build of the appropriate repo with the student's submission taking the place of the reference solution.  For C++, I don't think this even has a chance of working until we can do [multiple file submission](https://github.com/exercism/exercism.io/issues/1165).

**Comment by wobh** [comment]
I should look into the API more, but is there a way to ask for the code of an iteration by URL? If so, either a nitpicker or testing service could get the implementation and run tests on it. On the flip side we'd need a convenient handle to send the URL to the testing service and it would use the API to fetch the code, test, and, generate a page of test results. Test result pages might have to respond to things like unsubmissions or deletions. It might be good to expire them, or maybe post them As nitpicks or maybe their own tab on the iteration page if it's something that can be integrated.

**Comment by kytrinyx** [comment]
At the moment, you can ask for code by submission key, so provided that we could send the key to the service, the service could turn around and fetch the solution. If I recall correctly this also sends the readme/test suite, so it should be enough to actually run the tests.

If we can get a testing service to work, then I'd like to add a separate mechanism to store test results (different from nitpicks), so that we can show pass/fail discreetly and people can click for more.

**Comment by wobh** [comment]
Thanks @kytrinyx! I can make sure the testing script for the lisp track can be used this way.

**Comment by siakaramalegos** [comment]
:+1:

**Comment by kytrinyx** [comment]
In the past two weeks I have done a fairly large audit of the issues on exercism, and realised that there are a handful of recurring topics that come up, and many issues are trying to address the same underlying topic. Rather than trying to address each issue individually, I believe that it will be useful to collect the suggestions in one place, as well as discuss the underlying problems that have prompted these issues.

I am creating summary topics for these recurring issues, and closing the associated discussions that prompted the issue. If I have missed some important points in the summary, please add your voice to the discussion there.

-------

Summary topic for feedback that doesn't fall under the banner of peer code review: #2312.
