### ISSUE TITLE
"unable to submit" error. (http: 400)

### ISSUE THREAD

**Issue by TheSavage** [exercism/exercism.io#1777]
Just got this error when trying to submit for the first time.

2014/09/23 12:20:37 unable to submit (HTTP: 400) - unknown problem (track: proje
cts, slug: exercismcsharp, path: \projects\ExercismCSharp\ExercismCSharp\Year.cs

**Comment by jackwilsonv** [comment]
Commenting here for people that run into this error in the future (or today like me)...

If you jumped the gun like I did and fetched the whole language repo directly from github instead of using the exercism CLI client you may run into this error. I recommend removing the entire directory and using `exercism fetch` like they suggest on exercism.io. After doing that, I haven't had any issues submitting the exercises.

It may be as simple as changing the dir name to `[language]` instead of `x[language]` but I didn't actually try this myself.

**Comment by kytrinyx** [comment]
Changing the dir name would work, provided that you configure your exercism client to recognize the parent directory of the repo as the base. E.g.:

```
$ cd /tmp
$ git clone git@github.com:exercism/xhaskell.git haskell
$ exercism configure --dir=/tmp
```
