### ISSUE TITLE
Javascript: bob_test.spec.js is missing

### ISSUE THREAD

**Issue by KitKatMartin** [exercism/exercism.io#1796]
Hi there,

I'm a tad new at using node and am trying to get up and running with the javascript exercises. I've gotten up to the "Running Tests" section of the help (http://help.exercism.io/getting-started-with-javascript.html), but am getting this error when I execute: jasmine-node bob_test_spec.js

"/Users/username/bob_test.spec.js is missing."

Any help would be much appreciated. :)

Kathryn

**Comment by strtw** [comment]
Can anyone provide an answer to this part of @merlihan 's question?

"I thought though, that since the directory: /Users/markmartin/exercism had been added to my $PATH that it should have been found anyway, no?"

**Comment by kytrinyx** [comment]
This problem doesn't have anything to do with `$PATH`. Jasmine node doesn't look for files in the unix `$PATH`, that's used when the shell tries to find programs to run (for example `cd` or `brew` or `exercism`).

The problem here was that the test was trying to load a file named `bob.js` and that file didn't exist.

As a side note I doubt that `/Users/markmartin/exercism` directory was added to the `$PATH`. The way to check that would be to say `echo $PATH` and look for that.

**Comment by strtw** [comment]
@kytrinyx Thanks. There were problems with my PATH variables and folders. Now I'm working on the exercises. Great so far.

**Comment by kytrinyx** [comment]
Excellent, glad you got it sorted out.
