### ISSUE TITLE
Colorblindness accessibility

### ISSUE THREAD

**Issue by namshub3** [exercism/exercism.io#1834]
Initial front page of exercism.io has banner that is not possible to read for deuteranomaly colorblindness. This may apply to other types of colorblindness.
![screen shot 2014-09-24 at 23 37 24](https://cloud.githubusercontent.com/assets/4661056/4396997/b6aecda8-443b-11e4-88e2-fbed10833046.png)

Using a mixture of colors suggested by the following cartography site (http://colorbrewer2.org/) may assist in choosing a good contrast of text on background.

**Comment by saiqulhaq** [comment]
what do you think if like this?

![Image of Yaktocat](https://content.uploady.com/download/exercism.io.png?f=exercism.io.png&fid=JdN54%7E7nHFo&p=Bej843Zs6WJ&m=image%2Fpng&s=1&u=https%3A%2F%2Fwww.uploady.com%2Fdownload%2FJdN54%7E7nHFo%2FmJwEbcEBbdektJFL&tp=remote&t=1426289869&ex=172800&ip=2344866135&h=57e13817afa5f55f537cf477874d71d84912f152&width=934&height=300&type=thumb)

**Comment by kytrinyx** [comment]
I'm going to ask on twitter if there are any designers who can weigh in on this. It feels like it lost something in translation, but (a) I don't know design, and (b) I don't know how to check if it works if you're colourblind.

**Comment by saiqulhaq** [comment]
I think it was a good idea, by directly asking the people who are color blind on twitter

**Comment by fteem** [comment]
This might help with testing: http://colororacle.org/ 

"Color Oracle applies a full screen color filter to art you are designing – independently of the software in use..."

**Comment by kytrinyx** [comment]
Thanks!

**Comment by kytrinyx** [comment]
It looks like this issue is fixed. We deleted some of the hard-to-read text the other day. Screenshots follow.

![screen shot 2015-03-28 at 12 04 04](https://cloud.githubusercontent.com/assets/276834/6882457/9b673af6-d542-11e4-8c83-fba0dd58482c.png)
![screen shot 2015-03-28 at 12 03 54](https://cloud.githubusercontent.com/assets/276834/6882458/9b6a32ba-d542-11e4-8c6a-ce40eeb996fd.png)
![screen shot 2015-03-28 at 12 03 45](https://cloud.githubusercontent.com/assets/276834/6882459/9b6fecbe-d542-11e4-8b9f-d6ef4d9e319c.png)
