### ISSUE TITLE
Add documentation about deleting exercism CLI

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#1844]
Essentially it boils down to running something like `rm $(which exercism)`

**Comment by kytrinyx** [comment]
Note that this will be different for windows.

Also, it's a three-step process (at least):

1. locate binary,
2. delete binary,
3. delete config file (might want to do `exercism debug` to figure out where the config file lives).

Could be automated into `exercism uninstall`.

**Comment by tejasbubane** [comment]
A quick google search tells me that for `rm` there is an equivalent `del` command in windows. Any idea how the binary can be located in windows?

**Comment by kytrinyx** [comment]
I have no idea. on *nix I would use `which` to find the binary. Is there a windows equivalent?

**Comment by iamtjg** [comment]
`where` for cmd or `where.exe` if using PowerShell

**Comment by kytrinyx** [comment]
Thanks, @iamtjg -- do you happen to know what the error would look like if you tried to use `where` in PowerShell or `where.exe` from cmd?

**Comment by iamtjg** [comment]
`where` in PowerShell helpfully does nothing and silently goes to a newline :smiling_imp:.  `where.exe` will still work in cmd so best to have people use the 'longhand' regardless of which they are using

**Comment by kytrinyx** [comment]
Haha, how handy. OK, that works, then.

**Comment by nellshamrell** [comment]
Relevant files - https://github.com/exercism/exercism.io/blob/3da726bc71b79db11ad866c1da259ec85fd086ac/x/docs/md/cli/mac.md - looks like we edit the instructions for the CLI on mac here

https://github.com/exercism/exercism.io/blob/b4a08f00eea43212cde3b655e46727cbcbbb3b4b/x/docs/md/cli/linux.md - looks like we edit the instructions for the CLI on Linux here

https://github.com/exercism/exercism.io/blob/b98c0b65df6f4dbd4867a756c55124f6b7ffc899/x/docs/md/cli/windows.md - looks like edit the instructions for the CLI on Window here

**Comment by nickborromeo** [comment]
@kytrinyx Im reading through the relevant files that @nellshamrell has gracious provided for 

- [Windows](https://github.com/exercism/exercism.io/blob/master/x/docs/md/cli/windows.md)
It seems like the instruction already outlines the use of a package manager. That package manager has an [uninstall command](https://github.com/chocolatey/choco/wiki/CommandsUninstall)
```
choco uninstall <pkg|all> [pkg2 pkgN] [options/switches]
cuninst <pkg|all> [pkg2 pkgN] [options/switches]
```

Do you think it is enough to add that instruction to the windows.md file instead of the discussion of using Poweshell that you had in this issue?

- [Linux](https://github.com/exercism/exercism.io/blob/master/x/docs/md/cli/linux.md)
Im not sure if anything else needs to be done but looking at the install instructions it might be good to outline the reverse of the instructions?

```shell
$ rm -rf ~/bin/exercism
```
Then maybe something like open your bash profile with your favorite editor and remove `~/bin` from the PATH variable?

**Comment by kytrinyx** [comment]
> Do you think it is enough to add that instruction to the windows.md file instead of the discussion of using Poweshell that you had in this issue?

@nickborromeo I think so. That would at least be a good start, and then if someone has questions about how to do it without chocolaty they can ask, and we'll find out then how to improve the instructions.



> outline the reverse of the instructions

Yepp. And perhaps also have people delete the config file, as well.

I think it's fine to leave `~/bin` on the PATH. If they've later put other things in `~/bin` I wouldn't want to instruct them to remove it from their path, as those other programs would not be found, and they might not understand enough about PATHs to fix it.

**Comment by nickborromeo** [comment]
@kytrinyx do you think we can close this or did you want additional things to be added to the docs?

**Comment by kytrinyx** [comment]
@nickborromeo We're all good here, thanks!
