### ISSUE TITLE
Exercism does not help teach how to write good unit tests...

### ISSUE THREAD

**Issue by aidanw** [exercism/exercism.io#1876]
I think that the writing and maintaining of good unit tests is vital to being a modern developer. The way that exercism currently works, with a list of pre-written tests that the developer causes to pass, is not how real code is written.

It would be great if the Red, Green, Refactor cycle could be introduced and verified.
Maybe have both the test suit and the class be submitted, and instead of having a complete set of tests, just have two or three to start off the process then have further requirements in comments that the student must interpret into tests.

I realise this is probably exponentially more difficult to manage, explain and verify!

Does that make sense? Is this the right venue to explore such alterations?

**Comment by kytrinyx** [comment]
It's been a while since this came up, and I've done quite a lot of thinking about what exercism is about.

My conclusion has been that exercism is about the conversation around code (thoughtful critiques, recognizing code smells, thinking about and exploring idioms and trade-offs). The practice problems are there as an opportunity to go deep in practicing the basics, and also as a conversation starter.

While I believe that getting better at writing tests is a very important topic, I don't think that it is part of the core focus of exercism.

Thank you for making the suggestion, it has really helped clarify the purpose of the site.
