### ISSUE TITLE
-bash: exercism: command not found

### ISSUE THREAD

**Issue by liv-s** [exercism/exercism.io#1896]

**Comment by gerard-morera** [comment]
Hello! I am having problems as well. I've been following the post so I already done some of the test. Can anybody give me a hint about the problem? thank you :)
Gerards-Computer:exercism gerardmorera$ ls ~/bin
exercism	subl
--------
Gerards-Computer:~ gerardmorera$ echo $PATH
/Users/gerardmorera/bin:/Users/gerardmorera/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin
-----
Gerards-Computer:~ gerardmorera$ exercism -v
-bash: exercism: command not found

**Comment by kytrinyx** [comment]
Hi @gerard-morera, the binary is there, and the directory is in your path (twice!), so it's very strange that this isn't working.

Can you run the command `ls -la ~/bin/exercism`? That will show us permissions for the binary. Maybe it's not set as being executable.

Also, what happens if you open a new terminal window and say `exercism -v`? (same thing? different?)

Side note: I added so-called "code fences" around your command line output examples (three backticks on the line over the code, and three backticks on the line under the code). Check out https://guides.github.com/features/mastering-markdown/ for more about formatting in the comments.

**Comment by gerard-morera** [comment]
Hi @kytrinyx . Thanks for your help! This is the output I got from the terminal:
`Gerards-Computer:~ gerardmorera$ ls -la ~/bin/exercism?
ls: /Users/gerardmorera/bin/exercism?: No such file or directory`

`Gerards-Computer:~ gerardmorera$ exercism -v
-bash: exercism: command not found`

**Comment by kytrinyx** [comment]
Sorry, the question-mark wasn't supposed to be a part of that. Try this:

```
ls -la ~/bin/exercism
```

**Comment by gerard-morera** [comment]
Hello, sorry for the mistake.
`Gerards-Computer:~ gerardmorera$ ls -la ~/bin/exercism
total 0
drwxr-xr-x  3 gerardmorera  staff  102  6 ene 14:08 .
drwxr-xr-x  5 gerardmorera  staff  170  6 ene 14:43 ..
drwxr-xr-x  3 gerardmorera  staff  102  6 ene 14:08 ruby`

**Comment by kytrinyx** [comment]
OK, that makes sense.

What you have in `~/bin/exercism` is not the exercism binary, but a directory with problems in it.

You'll need to mv that somewhere else, e.g.

```
mv ~/bin/exercism ~/
```

Then install the exercism binary https://www.youtube.com/watch?v=TCT4eHGwfaE

**Comment by gerard-morera** [comment]
Thank you!

**Comment by kaylouj** [comment]
Hi, hope I can ask this question here. I read through this entire thread, trying to figure out what my issue was, but I'm still not sure why exercism commands aren't executing when I try to submit it. I managed to get exercism working insofar as I downloaded my first test to try (hello-world), and I completed it, ran the tests, got it fixed, and when I tried to use the $ exercism submit command it keeps coming back with 'command not found'...? I want to submit my code, but I don't know how if the command isn't working.

**Comment by kytrinyx** [comment]
@kaylouj What platform are you on? Mac, Windows, or Linux?

If you want to get realtime help, try the support chat: https://gitter.im/exercism/support (there are often people hanging out there).

**Comment by kaylouj** [comment]
I'm on Mac, so I'm using Terminal. I also used curl to install

**Comment by yvonmanzi** [comment]
Hi @kytrinyx ! 

I was having similar issues with folks on this thread. One thing I found out, which was the culprit of my issue, was that `brew update && brew install exercism` command was only executing the first half of the command. When it comes to the second half of the command--`brew install exercism`--, it would only download it. Then it would place it here:`/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/exercism.rb`. 

What I had to do was to actually ask the homebrew to install exercism.rb separately. When I did `HOMEBREW_NO_AUTO_UPDATE=1 brew install exercism`, everything started working as expected. 

I think that might be the thing causing some of these issues. One way, I think, to help new folks would be to add an extra step in the documentation where one actually asks homebrew to install exercism instead of just placing it in Formula folder.

**Comment by iHiD** [comment]
@yvonmanzi Hello. Thanks for your advice :) It's worth noting that you're commenting on a **very** old issue here. I've just created this [PR to split this over two lines](https://github.com/exercism/interactive-cli-walkthrough/pull/92). I think it would address the problem you're outlining? Maybe you'd like to comment there and let me know if it will help or not :)
