### ISSUE TITLE
Similar/Dissimilar code related to your submitted code

### ISSUE THREAD

**Issue by ismaild** [exercism/exercism.io#1921]
In order to aid learning a useful feature would be conducting static analysis on code, and then displaying to the user code that is similar to theirs, and code that is not very much like theirs. mentioned in: #1893

Thresholds could be added each way, that way you can see:
* How someone has solved the problem in a completely different way to you. 
* How someone has solved the problem in a similar way to you

**Comment by kytrinyx** [comment]
In the past two weeks I have done a fairly large audit of the issues on exercism, and realised that there are a handful of recurring topics that come up, and many issues are trying to address the same underlying topic. Rather than trying to address each issue individually, I believe that it will be useful to collect the suggestions in one place, as well as discuss the underlying problems that have prompted these issues.

I am creating summary topics for these recurring issues, and closing the associated discussions that prompted the issue. If I have missed some important points in the summary, please add your voice to the discussion there.

-------

Summary topic for feedback that doesn't fall under the banner of peer code review: #2312.
