### ISSUE TITLE
Rank solutions by  Code Metrics

### ISSUE THREAD

**Issue by smesropyan** [exercism/exercism.io#1928]
Participants might find it useful to compare their solutions to solutions with better metrics:
 - Lower Cyclomatic Complexity
 - Fewer Lines of Code
 - Smaller Maximum method depth
 - Smaller Percent of Branch Statements

Perhaps other metrics that developers find informative.

**Comment by kytrinyx** [comment]
In the past two weeks I have done a fairly large audit of the issues on exercism, and realised that there are a handful of recurring topics that come up, and many issues are trying to address the same underlying topic. Rather than trying to address each issue individually, I believe that it will be useful to collect the suggestions in one place, as well as discuss the underlying problems that have prompted these issues.

I am creating summary topics for these recurring issues, and closing the associated discussions that prompted the issue. If I have missed some important points in the summary, please add your voice to the discussion there.

-------

Summary topic for feedback that doesn't fall under the banner of peer code review: #2312.
