### ISSUE TITLE
Exercise listed twice

### ISSUE THREAD

**Issue by tehael** [exercism/exercism.io#1940]
In my list of exercise I have a duplication:

* My first submission of "ruby rna trascription" http://exercism.io/submissions/520293df95c11257f4729428 shows up as an exercise with one iteration
* the second submission of the same exercise http://exercism.io/submissions/ac1d03794408e19267ce32b1 shows up with two iterations

On both submissions pages the other submission is linked correctly.

![image](https://cloud.githubusercontent.com/assets/254312/4515156/d8420eae-4bab-11e4-907d-df5413a7fb3a.png)

**Comment by Adam89** [comment]
Just noticed that I have this issue as well and I don't know what caused it. 

![duplicate_submission](https://cloud.githubusercontent.com/assets/2530296/5602445/c25e2316-9345-11e4-960e-7e7ed0973bad.png)

**Comment by kytrinyx** [comment]
It looks like this is due to two different states: `needs_input` and `pending` both causing the exercises to be listed.

I'm not sure if this bug can still occur, or if this is left-over from an earlier fix. Either is equally likely. As a first pass I will write a small migration that sanity-checks and fixes the existing ones, and if it appears again before all of this is superseded by the activity stream feature, then we can dig into it.

**Comment by kytrinyx** [comment]
The more I think about this the more I think that the underlying problem was fixed. I'm deploying the rake task that fixes the current inconsistencies. If it happens again let's re-open this issue or start a new one.
