### ISSUE TITLE
Idea: Require nits before continuing

### ISSUE THREAD

**Issue by MadcapJake** [exercism/exercism.io#1956]
After submitting your solution, create a queue of other users' solutions to be nitpicked.  Require that 3 nits be made before allowing users to fetch the next exercise.

This would increase nits for sure though possibly have an impact on retention of users.  Just make it crystal clear that it doesn't have to be big, innovative, or even right to be a good nitpick.

**Comment by vaughankg** [comment]
+1 @daneandersen and a low pressure approach. 

A midway here would be to require the user to __view__ another nit before fetching the next exercise.

**Comment by kytrinyx** [comment]
@vaughankg that's an interesting idea!

**Comment by jkrmr** [comment]
:+1: I think this would be a great addition. 

I want to suggest cribbing some features from Thoughtbot's Upcase app, which I think is really well done:

(1) Leave a nit (or a few) to progress to the next exercise

Upcase requires users to submit a feedback to other users, suggesting one in particular who's at the top of the queue, in order to move on to the next exercise. While it's not perfect, it certainly helps. Personally I think it should require leaving feedback for at least two other users, as sometimes the wait for some comments is long.

(2) Featured Solutions

After completing an exercise, in addition to a queue of solutions waiting for feedback, Upcase users can see a featured solution done by an thoughtbot developer.

As a pie-in-the-sky idea, these could be implemented for Exercism as some kind of promotional effort with notable figures in different language communities: "How would Sandi Metz (or, ahem, @kytrinyx) solve the Hamming exercise?", for example.

More realistically, maybe users can flag solutions from which they learned something, and those with more than x flags can be put into a pool to be featured.

**Comment by kytrinyx** [comment]
> maybe users can flag solutions from which they learned something, and those with more than x flags can be put into a pool to be featured.

I've been wondering how to let interesting solutions float to the top. This could be one way.

>  Leave a nit (or a few) to progress to the next exercise

I'm very hesitant to do this, as I can imagine it leading to rushed/bad feedback. That said, it could be worth trying, provided that we look at both the stats and evaluate the quality of the feedback before and after.

It doesn't even have to be a hard requirement. It could be  something like _now that you've submitted a solution, go give someone else feedback. Perhaps this one [LINK]_.

**Comment by kytrinyx** [comment]
I've opened a discussion issue, aiming at the higher level goal of increasing the participation in the code reviews / conversations, and improving the quality of that participation.

https://github.com/exercism/discussions/issues/88
