### ISSUE TITLE
Profile Activity Stream

### ISSUE THREAD

**Issue by jalyna** [exercism/exercism.io#2059]
This is probably a vision but it would be great to have an activity stream (submissions, nitpicks, team joins/leaves, ...). This could be shown on the profile page. On top of that the activity stream of team members and your entities (submissions, nitpicked submissions) (and later people I follow?) could be shown on a dashboard.

I think that would connect people better and make others aware of changes. If we have at some point collaboration tools this will get even more important. :lollipop:

**Comment by kytrinyx** [comment]
OK, it's time to do this.

We have basic activity streams for each track, and also for each team. In the team activity stream we have code that lets you filter all of a given user's solutions by language. We could use the same code, I think, on the profile page. It should be pretty straight forward to implement!

**Comment by kytrinyx** [comment]
The first version of this stream would only be solutions submitted.

It needs to support the following behavior:

- under normal circumstances, you only see exercises that you, personally have access to. That's via the `acls` table (access control lists). We give you access to an exercise once you've submitted at least one solution to it, or if you are a mentor on that language track.
- we also support a "private share URL", which gives an alternate URL to a profile page, and it gives the person who has that URL access to see any solution that you've submitted, provided that they access it through a link on the page with the private URL.

We should probably also have the feature to set or unset the private share url on this page, rather than in the account.

**Comment by kytrinyx** [comment]
I think we should show all exercises, including archived ones. We should flag archived exercises as such.

**Comment by squanto** [comment]
starting to work on this

**Comment by kytrinyx** [comment]
Sweet, thank you. Holler if you have questions!

**Comment by kytrinyx** [comment]
@squanto What's the status on this? Are you making any progress?

**Comment by GustavoCaso** [comment]
@kytrinyx is there any one working on this one ?

**Comment by kytrinyx** [comment]
It doesn't sound like it, @GustavoCaso. Grab it if you want it!

**Comment by jtigger** [comment]
When filtering by submissions & comments made by a specific user, this would also address #1297.

**Comment by jtigger** [comment]
When filter by submissions and comments made on by a given user, then this would address #1297 .
