### ISSUE TITLE
Allow me to announce on social networks that I've shared/updated a solution

### ISSUE THREAD

**Issue by LegalizeAdulthood** [exercism/exercism.io#2125]
Allow a user to associate their exercism account profile with twitter and facebook and authorize exercism to tweet/share a link when I've submitted an exercise.

This will do two things: 1) it will help my friends who are also programmers know about my solution and give me feedback on it.  Feedback from friends is more important to me than feedback from strangers.  This is similar to teams, where the team is my personal social network.  2) it will help spread awareness of exercism itself and generate more participation.

**Comment by kytrinyx** [comment]
I think it would be useful to shift the discussion from the tactic to the strategy. In other words instead of "let's implement X", we should probably discuss what we're trying to achieve with X so that we can figure out if there are any other related changes we would want to make, and if a different approach might be better.

I'm going to close this, and if you still have thoughts about this, please open a new discussion in https://github.com/exercism/discussions/issues
