### ISSUE TITLE
Meetup: add tests that cover the fifth-Xday-of-the-month case?

### ISSUE THREAD

**Issue by JKesMc9tqIQe9M** [exercism/exercism.io#2142]
Some solutions to 'meetup' pass the tests, but they don't necessarily handle the date-out-of-bounds situation (_eg_ asking for the fifth Monday of a month that doesn't have five Mondays) -- instead they return a date in the following month.

Would it be possible to add a test that would assert that a date *not* be returned in these situations (and, say, an exception raised)? And maybe a test asserting that the right date is returned for a month that does have five Mondays?

Thanks!

**Comment by kytrinyx** [comment]
I've added individual issues for each language that has a meetup problem.

**Comment by etrepum** [comment]
You can't regularly schedule a meetup on the fifth week of every month because February usually doesn't have a fifth week at all (and no month ever has a full fifth week). It's nonsense to even support "fifth" as an input in the first place. I think that first-fourth, last, teenth are the only scheduling inputs that should be supported.

**Comment by kytrinyx** [comment]
Excellent point! I wish I had thought of this before I opened all the issues :)
