### ISSUE TITLE
Javascript fails if comment has a single-quote

### ISSUE THREAD

**Issue by coreyhaines** [exercism/exercism.io#2143]
I wrote the following comment:

```
That's a great change. No, there wasn't a particular reason, more like a bit of not paying attention at the final stage.
While first/second reflect their position, they don't really accurately reflect what they are. Positional naming isn't the greatest. I've pushed up a second submission that adds their role. Thanks!
```

and the single quotes seem to cause it to fail when displaying.

**Comment by code-R** [comment]
@kytrinyx this issue is happening because of single quote in the comment thread.. which caused the parsing issue with angular.. I have now escaped that which should resolve this issue..https://github.com/exercism/exercism.io/pull/2146

And that is the reason why all those six comment threads were not shown for that nit..My pull request should fix this issue.

**Comment by kytrinyx** [comment]
Thanks @code-R -- as mentioned I'd like to take a step back from the entire feature, since it turned out a lot more confusing than I expected. Thanks so much for taking the time to work on it, as we couldn't have figured any of this out without an initial implementation!
