### ISSUE TITLE
Comments vs Nits -- very confusing

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2145]
I'm really torn about the new comment-threads introduced in #2130.

The UI is really confusing. There's no indication who said what in the comments, and it's not clear whether I should click "comment" or "nitpick".

![comment-threads](https://cloud.githubusercontent.com/assets/276834/5587486/9e317908-90ec-11e4-9f71-cad3d7fbf5b9.png)

Any thoughts on whether we should simply back this out entirely, or try to iterate on it?

/cc @code-R (because comment-threads are your initiative)
/cc @jalyna (because you made the whole discussion part usable in the first place!)

**Comment by kytrinyx** [comment]
@wobh I don't have stats (though it shouldn't be too hard to figure out). I think you're right that at-comments would be useful.

**Comment by code-R** [comment]
@kytrinyx Implementing proper UI for this feature will clear the confusion.. There should be a proper visual distinction between nits and comment threads.. 

In current system only submitter can comment on a nit. Any third person's comment on the nitpick needs to be added as a separate nitpick. Even if that person would like to say "Hey your nitpick looks cool +1 for it", in the current system, he can only add that as a nitpick rather than simply commenting on a nitpick

![selection_017](https://cloud.githubusercontent.com/assets/894831/5595381/3c7cf3a2-9297-11e4-9f91-9a616a7079ea.png)

It should be posted as a comment rather than a nitpick..This feature doesn't look that useful because of the UI and I think proper UX should boost this feature a lot.

![selection_016](https://cloud.githubusercontent.com/assets/894831/5595368/09fc637c-9297-11e4-9678-1f38271faa37.png)

**Comment by kytrinyx** [comment]
I'd like to think more about this. My current impression is that two levels of comments is overkill, and the distinction between the two is not great enough to warrant the extra complexity.

**Comment by coreyhaines** [comment]
I agree that a proper UX would make this feature more explicit. However, before rolling this back in, would be good to see some examples of a good, value-add UX for this feature.

@code-R could you put together some examples of what you are thinking about improving on the UX that would make this feature really valuable? If we had some screenshots, we could have a good discussion here and make our way to something.

**Comment by darkliahos** [comment]
Couldn't you have some sort of toggle button, so if someone types in a comment, they can choose if it is a nitpick or if it is a praise for good coding practice.

**Comment by kytrinyx** [comment]
Any feedback about the code, whether it is a critique or pointing out interesting or positive features qualify as "nitpicks" in the lingo of the site.

The threaded comments are about responding to someone else's feedback (like the distinction between answers and comments to answers on stack overflow). In some cases I think that this distinction makes sense, but here it's quite fuzzy and confusing.

**Comment by kytrinyx** [comment]
I've decided to not move forward with threaded comments. Thanks, everyone, for the discussion.
