### ISSUE TITLE
Order of problems in other tracks in relation to the sequence of difficulty 

### ISSUE THREAD

**Issue by masters3d** [exercism/exercism.io#2159]
Is there a standard on how problems flow after the other? for example the problem meetup seem to be all over the place but bob or leap seem to start most tracks. Is that up to the main track contributor? I felt that the swift track sequential difficultly level was well laid out and proportional. Is there a "master" track that the other tracks follow as far as problem order? I am just trying to get guidance on the problem sequence. 

<a href="http://imgur.com/jtpTjFk"><img src="http://i.imgur.com/jtpTjFk.png" title="source: imgur.com" /></a>

**Comment by kytrinyx** [comment]
> Is that up to the main track contributor?

Yeah, each track makes its own choices about it. There's no master track or overall sequence. Basically the original sequence happened pretty much by accident, others copied it, and then several of the tracks have re-arranged things as they got feedback.

For example, 'bob' was originally the first exercise on the first track, but it turns out that it had a lot of complexity that made it hard for new programmers to get a quick win. We moved 'leap' and 'hamming' earlier, since both of these are basically a very simple input-output type of thing with one computation and no state.

**Comment by masters3d** [comment]
I think it would be helpful if somebody clicks on a problem on a track that this take them to the test for that problem on that track. Also, maybe a wikipedia style table where on the left is the master list of problems. http://en.wikipedia.org/wiki/Comparison_of_programming_languages

**Comment by kytrinyx** [comment]
Yeah, that would be great (both getting taken to the test suite for that problem/track, and the wikipedia style table).

**Comment by kytrinyx** [comment]
We've got an open discussion about ordering of exercises here: https://github.com/exercism/discussions/issues/60

Closing this in favor of that one.
