### ISSUE TITLE
Allow declaration of language mastery.

### ISSUE THREAD

**Issue by Havvy** [exercism/exercism.io#2164]
Even though I've not done any of the JavaScript exercises myself, I know JavaScript enough to actually help people who have done them, but since I haven't done them myself, I'm not allowed to look at others' solutions. Is there a way to make it possible to self-declare one proficient in a language so that they can review others' exercises?

**Comment by kytrinyx** [comment]
+1000 I really need to address this, because doing all the exercises can be tedious and boring if you already know a language (a handful of the problems might be interesting, but certainly not all of them).

The biggest thing that worries me is that novices tend to think they're much, much better at things than they really are (e.g. a gent I was talking to a while back told me he was an intermediate javascript developer. After chatting for a while he mentioned that he had programming for two months).

One thing I was considering was having a small barrier to this, where people "practice-nitpick" two or three problems, and other people (who already have been granted 'mentorship' or 'mastery' status) can vet that this person actually knows what they're talking about.

That, of course, has other potential pitfalls, and it might be worth just letting people self-profess mastery and figure out what to do if we get too many novices.

**Comment by wobh** [comment]
I feel like this could short circuit something fundamental that makes exercism work for me.

**Comment by wobh** [comment]
Sorry, I'll try to gather more concrete thoughts on this, this weekend.

**Comment by carlisia** [comment]
:+1:  for something like this. 

An additional thought along the same lines: when I get multiple suggestions on my solution, sometimes, inevitably, there will be conflicting advices. This may lead to redoing the solution multiple times because different people showed up with diverging opinion, but not necessarily that their solution was amazingly better than any of the others. Someone who is a beginner would not know enough to identify a suggestion that is truly superior to another versus something that is very equivalent but only differ in style. I would very much like to be able know who has a better handle on the language and OO concepts and pay more attention to that. Of course I can go to their profile and see how many exercises they have completed, but that doesn't tell me if they have completed them with any competency.

Totally going out on a limb here: should we be able to 'star' people's solution and use that as some sort of ranking?

What I'm saying here is a bit different than what the op is saying, but indicates another need for some sort of language mastery indication.

**Comment by kytrinyx** [comment]
> I feel like this could short circuit something fundamental that makes exercism work for me.

I originally thought this as well, but I've come to believe that some people would want this more than the do-the-problem-first approach. As long as it's opt-in, I think that it could be worth it.

That said, I really would love to hear more in-depth thoughts about what you think the risks could be, @wobh. I have some ideas, but I want to hear your thoughts first.

> sometimes, inevitably, there will be conflicting advices [...] Someone who is a beginner would not know enough to identify a suggestion that is truly superior to another versus something that is very equivalent but only differ in style.

I'm not sure there's any good solution to this. Beginners who are willing to try many different things based on feedback are doing something right. Eventually they will evolve an informed opinion on what is better and not.

I think that good feedback also includes reasons why they would suggest the change. The most interesting discussions are often when there are conflicting opinions, and it could be that both are correct... in different situations. The trade-offs are very real, and surfacing that in the discussions is very valuable.

I don't want to do any visible ranking (stars, labels) for people, since that would give them authority beyond whatever they've earned by simply giving useful, helpful, quality feedback.

In my experience, the more competent someone is, the more they'll be able to identify actual reasons why they prefer one thing over another. Also, the more competent they are, the more it seems like they discuss trade-offs (see anything written by Martin Fowler, for example). It's not always the case. You'll always have opinionated experts who refuse to budge on things, but still. The discussions tend to be a lot more nuanced than with beginners.

**Comment by wobh** [comment]
Thoughts:

There are already a few ways, a user could be able to view exercises without having to actually do the exercise, but we can consider only these two:

- Users choose to share the exercise via [twitter](https://twitter.com/hashtag/exercism), github gist (wish there were a better way to search for these), pastebins, etc
- A user submits an incomplete exercise, perhaps with just a comment (eg. `// TODO: implement a leap year detector`)

Considering the second case: I believe I've probably read the corresponding exercises of everyone who has ever nitpicked one of mine (aside: feature request, let's make this even easier, like one-click), and it would surprise me to learn that very many others had not done likewise. I don't know how other people would feel, but if it weren't a name I recognized, I'd be pretty skeptical of taking advice from someone who had put up such a submission, even if the comment, proclaimed expertise, and had a link to whatever they considered credentials. I don't want to beat up on this strawman much, only to point out that if "nitpick-only" users were established, many might find it difficult to establish credibility. Certainly with me.

Considering the first case: we can figure out how to enable more of this, maybe more sites, maybe a one-click post to gist, or pastebin, or freenet#exercism. We could also implement a "shark tank" section, where submitters and nitpickers could throw up code snippets and get help/reactions. Unfortunately, I came up with a bunch of ideas for the shark-tank instead of thinking about the big picture of this. But anyway, the important thing is that the sharing is initiated by the sharer.

Why do I feel this could be bad? 

As frustrating as it might be for more expert observers and participants, exercism.io, as I've experienced it so far, is, or is becoming a really great place where beginning users of *approximately equal* skill can find, explore, and learn from each other, even if it's sometimes the wrong thing. Peer-to-peer learning opportunities seem to be very hard to come by, very valuable, but don't seem widely valued for irrelevant cultural reasons.

As much as it would be great to have some more language and subject experts participating, they should participate. In my opinion, experts should submit code and accept nitpicks from beginners. That's the best way of helping with the resources we can offer right now. Heck, they should submit bad code! One definition of expert is: someone who knows how to make a lot of mistakes. If they don't want to do that, they can submit code to one of the harder exercises and maybe nitpick and get nitpicked by someone closer to their level.

The big challenge as I see it, is getting more beginning users to ask questions, be critical, and make nitpicks and conversations with each other.

Ok, I'm out.

**Comment by kytrinyx** [comment]
While the shark tank could be interesting, it seems like a completely separate thing from exercism.

The twitter thing is already probably happening. I have no idea if people are actually nitpicking because of it. We could add a hashtag to it to make it more searchable.

> Considering the second case: I believe I've probably read the corresponding exercises of everyone who has ever nitpicked one of mine [...], and it would surprise me to learn that very many others had not done likewise.

In the first few months I left something like 2000 nitpicks, and didn't do any exercises. I think that my comments spoke for themselves. They're not always correct, but I try to make them respectful and make it clear that this is personal opinion based on experience, not expert advice.

> (aside: feature request, let's make this even easier, like one-click)

Sure, would you add an issue for that?

> The big challenge as I see it, is getting more beginning users to ask questions, be critical, and make nitpicks and conversations with each other.

Yes, that's one of the big challenges, but I don't see it as the only one.

It's very common for beginners to give bad advice with absolutely no concept of how little they know. I'm not saying that all beginners do this, or that all the advice between beginners looks like this, but it happens a lot, and I don't think that it's good for learning at all.

I always feel guilty when I see beginners leading each other down the rabbit hole. They have no basis for the advice they're giving, beyond, perhaps, that someone gave them the same advice.

I would be much happier about the whole thing if we could find a way to encourage beginners to nitpick more by asking honest questions than by giving unfounded advice: _I understood everything up to line 17, but I don't get how that works, can you explain it?_, or _sometimes I see people do X, but you do Y and it seems like it does the same thing? What's the difference between them?_

There are a number of people that do not nitpick on exercism even though they would have had a very good reason to do so: They're mentoring students at a programming bootcamp, and those students use exercism.

These are generally people who have at least some experience programming (sometimes a lot of experience), and many of them would probably give really good feedback. But in order to do so they have to install the CLI and do exercises. It's not that those exercises are hard, but these are busy people who just don't care about the practice aspect for themselves, and who could be very valuable in giving comments back to people who do.

Later, I think that many people would want to do some of the exercises. I have seen some very experienced programmers do really interesting things when they practice. One programmer who has been earning a living at this since the 70s would submit 4 different approaches for each exercise they did, along with really, really long comments about what the trade-offs would be and what they were thinking. It was fascinating.

I hesitate to just let people loose. I would really want people who nitpick-only to have some skin in the game so that it doesn't devolve into reddit or hacker news. I want there to be some sort of barrier. I also want them to prove that they're capable of providing feedback that is specific, actionable, and respectful. That they don't give things away ("do this, do that", completely robbing people of the experience of discovering that on their own), but suggest something to think about that might lead someone to choose to do X or Y. That they provide reasoning for the feedback that they give, even if it's just based on a gut feeling.

@etrepum - if you have thoughts on this, I'd love to hear them.

**Comment by Havvy** [comment]
Give a page of what is expected out of nitpickers who don't do the exercise discussing the things you are discussing in here. If people disregard the message, just ban them from the "expert" pool. Tell them explicitly that Exercism is not stack overflow, and maybe give an example of how to constructively nitpick. That would turn a one button process into a two button process.

Another option, one that takes more human-power is to have an example entry and then have people critique that, and if the critique is good, let them be an expert. You could also have other people in the expert pool critique too, if you find yourself low on man-power.

Remember, if the implementation leads to a worse experience, you can always gut it with an apology.

Though, you're also probably swamped with different avenues you can take. I didn't forsee there'd need to be this much discussion for such a change, and if there are other things that are more pressing, I'd understand if you postponed or rejected it just on the basis of time.

**Comment by etrepum** [comment]
@kytrinyx the simplest thing that might work would be to change the threshold such that an entry still needs feedback unless it's been liked or commented on by 2 or 3 different people. Hopefully this would be a way for inappropriate feedback to be corrected.

**Comment by kytrinyx** [comment]
@etrepum I think that would work in some language tracks, but we have significant bottlenecks that would make it so we don't discover bad feedback in others (especially in Ruby, Python, and JavaScript).

```
> SELECT COUNT(id), language FROM submissions WHERE state='pending' AND nit_count=0 GROUP BY language ORDER BY COUNT(id) DESC;

 count |   language   
-------+--------------
  6176 | ruby
  6017 | python
  3249 | javascript
  1382 | clojure
  1167 | go
  1007 | csharp
   660 | haskell
   621 | cpp
   587 | perl5
   522 | elixir
   455 | scala
   348 | coffeescript
   204 | swift
    97 | erlang
    93 | fsharp
    73 | objective-c
    55 | lua
    40 | ocaml
    18 | lisp
     4 | php
     2 | rust
     1 | java
```

Maybe the bottlenecks are the real problem that needs to be addressed, though, not the decision about whether people can skip past actually writing some code that others can nitpick.

**Comment by etrepum** [comment]
I think that query might not really say too much, since it doesn't account for likes. Either that or the interface doesn't show me those 660 entries for some reason!

**Comment by kytrinyx** [comment]
Good point. Here's what I get when accounting for likes:

```
> SELECT COUNT(s.id), language FROM submissions s LEFT JOIN likes lk ON s.id=lk.submission_id WHERE state='pending' AND nit_count=0 AND lk.id IS NULL GROUP BY language ORDER BY COUNT(s.id) DESC;

 count |   language   
-------+--------------
  5517 | ruby
  5124 | python
  3062 | javascript
  1251 | clojure
   995 | go
   833 | csharp
   567 | cpp
   458 | elixir
   452 | perl5
   336 | scala
   331 | coffeescript
   173 | swift
   170 | haskell
    78 | erlang
    66 | fsharp
    65 | objective-c
    47 | lua
    31 | ocaml
     4 | php
     2 | lisp
     2 | rust
     1 | java
```

There must still be some other factor as well, since I doubt that you are seeing 170 unanswered problems.

**Comment by chezwicker** [comment]
I'm completely new to exercism, so I'm going out on a limb here - my comment might miss some existing concepts. If so, please feel free to just get rid of it ;-)

I think one way of "proving" language mastery would be to offer a (random?) selection of solved examples that are known to have been improved based on reviews. A new user would have to review (nitpick, you call it here, right?) these examples and these reviews would be scrutinized by a set of already proven members. Naturally, this would happen anonymously (the scrutinizing gang would not know who's review they're checking out). Based on what they see, they would "award" a certain level (comments sounded like that concept exists) to get the user started.

The above said, I think it would indeed make sense to "force" every new member to submit a certain set of exercises as well - that allows to link back to their code when checking out their reviews. Also, you wouldn't want to overload the "scrutinizers", so there should be a barrier to entry...

**Comment by kytrinyx** [comment]
@chezwicker I think that having people who have already in some way proved that they give decent feedback would be a good way to do this. I don't even think you need to have language mastery, only

1) the humility to know when you don't know something,
2) the ability to ask good questions and provide a respectful critique

I think it would be useful for people to have solved some problems in each language they provide feedback in, both so that their profile links back to actual code that they wrote, and also so that they get a feel for the track, but I don't think it's essential.

**Comment by kytrinyx** [comment]
I'm closing the discussion, as we're digging into the questions around feedback and mentorship as part of the design reboot / user experience research.

(It has the design-research label, which is what we're using to keep track of prior discussions about the topics).
