### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism.io#2208]
It seems that the website's performance is slowly degrading. I assume this is due to the website becoming more and more popular, which is a good thing! Some pages are beginning to take quite long to load, most notably the team page. Perhaps some tuning could be done to improve the performance.

**Comment by kytrinyx** [comment]
Agreed, it's getting pretty bad. I've been meaning to rewrite portions of this. In particular, the biggest change which would make a huge difference is implementing the [activity streams feature](https://github.com/exercism/exercism.io/issues/1899).

I'll take a look at the worst offenders, though, and see if I can tweak what we have.

**Comment by ErikSchierboom** [comment]
Good luck!

**Comment by kytrinyx** [comment]
:) Thanks

**Comment by kytrinyx** [comment]
I implemented activity streams (not quite in the way described, but close enough).

We still need to do work to figure out what the slowest pages are, and fix them. I'm not sure what the best approach to this is—perhaps tracking/monitoring in production?

**Comment by nickborromeo** [comment]
I am not sure what free options there are out there but NewRelic is a good tool to just analyze the slowest pages. Maybe it can just be a trial period to see what the slowest pages are and then keep track of that. Benefit is you have somewhere to start, Con, is that long term you loose the tracking 😄

**Comment by kytrinyx** [comment]
I was using NewRelic, but at some point it started filling the logs with garbage (maybe due to an incompatibility in versions? Not sure). Anyway, I didn't have the bandwidth to deal with it, so I just removed it.

We could also agree to not deal with performance until we do the reboot (https://github.com/exercism/discussions/issues/113) which we are currently working on.

We have addressed issues on specific, painful pages.

What do you think about closing this issue and dealing with performance on a page by page basis if it becomes really painful, and otherwise putting it off for the redesign?

**Comment by nickborromeo** [comment]
I am not opposed to closing 😄  However, it will need to be tracked or "pinned" somewhere so that it is not out of side out of mind coz it would be good for the project to consider performance for the sake of the users. And I think when the users complain, that is already a failure on the project or the app coz that means its unbearable at that point.

**Comment by kytrinyx** [comment]
In the reboot, performance will be one of our primary concerns.

> when the users complain, that is already a failure on the project or the app coz that means its unbearable at that point.

Yeah, I know you're right. It's just—the prototype is such a disastrous mess, because it's grown organically over the past few years without any sort of plan or design (and rightly so, because we didn't quite know what we were building).

I would not be opposed to someone making a plan for the data collection to find the worst offenders, and then opening issues for each of the things we would like to fix, but I do not have the bandwidth to take this on right now.

**Comment by ErikSchierboom** [comment]
> In the reboot, performance will be one of our primary concerns.

Hurray! Performance *is* a feature, something that is sometimes neglected. Great to hear that won't be the case with the reboot.

Slightly related to performance, will the reboot also involve working with a different front-end libraries stack? I have some thoughts on that, but don't know where to share them.

**Comment by kytrinyx** [comment]
> will the reboot also involve working with a different front-end libraries stack? I have some thoughts on that, but don't know where to share them.

Probably, yes. Would you open a discussion in the discussions repo about that? We're still in the design research phase (not even at wireframes), so nowhere near talking about implementation, but it would be great to hear your thoughts on it.

**Comment by ErikSchierboom** [comment]
Sure, I'll post my thoughts in the next couple of days.

**Comment by ErikSchierboom** [comment]
@kytrinyx Just posted my thoughts at #127.

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this one now, since we have performance properly tracked for the reboot.
