### ISSUE TITLE
Improve test scenario

### ISSUE THREAD

**Issue by purezen** [exercism/exercism.io#2265]
I have been going through the codebase and feel that there's much scope for improving the test scenario here. A lot of tests seem missing. Also, the coverage report shows poor coverage of a lot of files. Apart from that there are some tests which don't seem to be working properly.

**Comment by purezen** [comment]
These files seem to be missing their tests:

- [ ] lib/app/helpers/github_link_helper.rb
- [ ] lib/app/helpers/gravatar_helper.rb
- [ ] lib/app/helpers/notification_count.rb
- [ ] lib/app/helpers/profile_helper.rb
- [ ] lib/app/helpers/session.rb

**Comment by purezen** [comment]
These files for instance have test coverage < 50%.

![test_coverage](https://cloud.githubusercontent.com/assets/3036093/6863995/1e7811a8-d481-11e4-8f90-0c60f50c72ca.png)

**Comment by purezen** [comment]
I ran the test test/helpers/site_test_helper_test and I found that the test_title method doesn't actually access the actual code in corresponding file in lib/app/helpers/.. (?)
Also, what does the helper method do in the test file?

**Comment by kytrinyx** [comment]
Yeah, the tests are spotty at best. This is in large part because most of the code in the codebase is a rough experiment, and we're still not quite sure where we're going.

We've extracted the part of the codebase that seemed self-contained and well-understood into  https://github.com/exercism/x-api. It has proven to be quite stable. Improvements can be made of course, but the coverage is nearly complete, and the tests have proven to be useful in that when we have discovered a bug or seen the need for new behavior, it has been quite straight forward to understand the tests and add new behavior.

I went through the files you listed quickly:

* `lib/exercism/github.rb` - this is a fairly janky file that does the 3rd party integration to authorize against github. It hasn't changed in a year aside from a small bit of cleanup. It could probably benefit from a test, most likely using VCR since it calls out over HTTP.
* `lib/app/routes/metadata.rb` - this is used to display the README and test suite for a problem. Again we would need to use VCR, since the Xapi is a separate application, and this calls out over HTTP. It would be great to have better test coverage here, as I suspect that we could move some of the complexity out of  the route.
* `lib/app/routes/solutions.rb` - this is an experiment, I wouldn't bother testing it.
* `lib/exercism/xapi.rb` - all HTTP stuff, could be tested, but I wouldn't bother with more than a smoke test.
* `lib/app/routes/problems.rb` - this is an experiment, I wouldn't bother testing it.
* `lib/app/routes/stats.rb` - an experiment, it's going away.
* `lib/app/routes/user.rb` - mixed bag. The `/:username/:key` route is deprecated, and I'll probably delete it in the next week or so.  "become nitpicker" is probably dead code (or should be). The profile page is going to be redesigned. Only the `reset api key` would be worth having a test for.
* `lib/exercism/explore.rb` - experiment, not really sure if it will stay.
* `lib/assumable/user.rb` - only used in dev, not worth testing.
* `lib/exercism/authentication.rb` - should probably be tested, but it's difficult because it does the third party oauth thing. I wouldn't bother mocking things out. I made it as short as possible. The method that gets called on line 4 is fully tested, I believe, and line 3 is calling out to github.

The `test/app/helpers/site_title_helper_test.rb` isn't doing much. You're right that the `test_title` method doesn't do anything. It should be deleted or improved.

The helper method creates a self-contained instance in the most light-weight way possible. The helper modules are included into the sinatra application itself, but there's no need to test them in a controller test.

**Comment by purezen** [comment]
Ah, that was some nice insight!
Cool. So I will try to make some improvements to the tests now.

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this issue—but if you want to help improve the tests further, then please do so!
