### ISSUE TITLE
Project wide discussions

### ISSUE THREAD

**Issue by pminten** [exercism/exercism.io#2268]
This is I fear a bit of a vague issue but I've noticed that exercism has become rather fractured in terms of communication. Each language now has its own git repo which has the side-effect of having it's own issue tracker. On top of the 30+ issue trackers we have two other means of communication, neither of which terribly well advertised: the gitter chats (roadmap and support) and the exercism@librelist.com mailing list. Of course exercism itself also facilitates discussions, but those are in the context of specific submissions.

The downside of this fractured communication model is that it's pretty hard to communicate across track boundaries. Any time an issue is discovered in a particular exercise Katrina manually has to file issues for that exercise on all other tracks that have it. But if I wanted to discuss issues of exercise quality with developers of other tracks there's no good way to do that.

Users also don't have a good place to discuss issues with exercises. Sure, there's the issue tracker, but if you're a newbie you may very well feel that your problem is probably your fault so filing an issue feels too much like saying "hey you have a bug".

I don't really have much of a solution I'm afraid. Could imagine that a central discussion forum, with github login, would work but it would still be just another way to communicate.

**Comment by kytrinyx** [comment]
I don't have any good answers, and this is something that I have been thinking about quite a bit.

I think that for anything that has cross-cutting concerns, the issue should be filed in this repository (exercism/exercism.io).

If it's relevant to each individual language, then I think it's useful to post an issue to each language since the language track maintainers will likely have notifications turned on for that repo, and not for the exercism.io repo (since the main repo is very noisy).

I have a script that posts issues to all of the separate repositories, so that's not very painful.

Another way of doing this would be to create a "language track maintainers" team under the exercism organization. If we have a general issue that should be discussed across languages, then that tag can be notified with an `@` mention, I think (e.g. @exercism/track-maintainers). Then we could use a simple checkbox-style approach in the first post of the issue, and each track maintainer can check off their language (either because it's irrelevant to them or because it's done). I would have to give the track maintainers access to the main exercism repo, otherwise they can't check the boxes, but that seems fine, as it seems unlikely that anyone will go and commit code to master without consulting me or each other.

For where to ask for support... I'm really not sure. I actually think that the issues could work well if we make it very clear that support issues are fine (even if it's their fault, we'll help you sort it out).

Maybe we can even ditch the mailing list and have the more meaty discussions here, with a particular tag. We could auto-close discussions after X amount of time so that they don't languish, and if there are action-items that come out of a discussion we could open a new, focused issue that links to the original discussion.

The chat rooms are useful for the more free-flowing ad-hoc discussions.

**Comment by pminten** [comment]
Regarding language track maintainers. I could imagine that x-common would be the repo where such issues would go since that's all about exercises while the exercism.io repo is more about the machinery of exercism. That way the track maintainers also wouldn't have to have access to the exercism.io repo, only to x-common.

**Comment by kytrinyx** [comment]
That's a great idea. I'm creating the team right now, and I'll add it to the x-common repository as committers.

**Comment by masters3d** [comment]
Where do we post news things . Like today making it to the first page of HN?

https://news.ycombinator.com/item?id=9307570
![image](https://cloud.githubusercontent.com/assets/6539412/6955854/935d3892-d899-11e4-9bd5-1d3e872f5441.png)

**Comment by kytrinyx** [comment]
I'm not sure. Twitter?

**Comment by masters3d** [comment]
Twitter could work. we could tag news links with #exercism or something similar. Then maybe make a widget to filter that hashtag and put it on the website. I've seen good marketing being done this way with testimonials.

**Comment by mtakac** [comment]
:+1: (for both, making it to the first page on HN and Twitter)

**Comment by kytrinyx** [comment]
It took a year of thinking about this, but I finally ended up creating a repository where we can put discussions: github.com/exercism/discussions - I intend to slowly move all the fuzzy discussions from elsewhere in the exercism organization to this new repository.

I've posted the question about news here: https://github.com/exercism/discussions/issues/19
