### ISSUE TITLE
Example pseudo-submission as discussion forum

### ISSUE THREAD

**Issue by pminten** [exercism/exercism.io#2280]
This is just a crazy idea that popped up in my head. What if for every exercise we'd have the example as a kind of pseudo-submission that people can comment on and that gets linked from all pages about that exercise?

The main benefit here would be to get a kind of very lightweight discussion forum to talk about problems with the exercise itself without having to add much extra infrastructure.

**Comment by kytrinyx** [comment]
I would want the example to be talked about to exhibit some problems in that case, so that there's something to talk about.

**Comment by mtakac** [comment]
Wouldn't it just divert users form nitpicking on actual submissions? I mean why would somebody bother with nitpicking if you can see all possible comments in one place?

**Comment by kytrinyx** [comment]
That's certainly a possibility; it wouldn't be all possible comments, though, would it? The example solution is only one way of approaching it.

At the moment I don't know that I want to try this out, but I think it's definitely worth discussing the merits and disadvantages it might have.

**Comment by kytrinyx** [comment]
In the past two weeks I have done a fairly large audit of the issues on exercism, and realised that there are a handful of recurring topics that come up, and many issues are trying to address the same underlying topic. Rather than trying to address each issue individually, I believe that it will be useful to collect the suggestions in one place, as well as discuss the underlying problems that have prompted these issues.

I am creating summary topics for these recurring issues, and closing the associated discussions that prompted the issue. If I have missed some important points in the summary, please add your voice to the discussion there.

-------

Summary topic for feedback that doesn't fall under the banner of peer code review: #2312.
