### ISSUE TITLE
Logging in with github lands me at an existing exercism user account halst

### ISSUE THREAD

**Issue by halst** [exercism/exercism.io#2289]
Logged out and revoked exercism access immediately, but that is just kind of the worst

**Comment by kytrinyx** [comment]
Ouch, that's awful. Thanks for the heads up.

Note to self: https://github.com/exercism/exercism.io/blob/master/lib/exercism/user.rb#L31 -- use only github_id, usernames can belong to different user's sequentially.

**Comment by halst** [comment]
User seems to have had this github account name in the past? I'm shooting him an email to see what's up.

**Comment by kytrinyx** [comment]
I'm deploying a fix for this, and I've also added logic to unset the old user's username in the system, since the person who just authenticated with GitHub clearly has that username. Their username will then get updated the next time they log in.

Would you be willing to try logging in again to verify the fix? I totally understand if the answer to that is "no".

Thanks again for letting me know about this.

**Comment by halst** [comment]
Looks good on my end, thanks!

**Comment by kytrinyx** [comment]
Thanks so much!
