### ISSUE TITLE
Landing pages free ads for exposure

### ISSUE THREAD

**Issue by masters3d** [exercism/exercism.io#2291]
I was not sure where to put this but I thought this may be a good spot. 

How about applying for the 10k a month from Google and run some ads?
www.google.com/grants/

We could have very simple landing papers per language track to stream line the on boarding process. 

I am not seo expert but having landing pages could help good Google search results too. 

As of right now there no one stop shop for each language to inform people what exercism is. 

For example. I wanted to send a link to a friend about the swift track but we require a log in for the most interesting stuff. (Landing page)

These are multiple items but I was thinking more on terms of exposure.

**Comment by mtakac** [comment]
Hehe is the application in a state that it can handle it? I am not a marketing expert, but considering that I was able to get 1000+ daily visitors on my site for a few bucks, this could bring in some serious traffic.

**Comment by kytrinyx** [comment]
I do want to make landing pages for each language (lately I've been thinking that the front page should have little "cards" with each active language, each card would link to the landing page for the language, and we could have something in the main menu for "languages" as well).

I'm not at all ready to market the site, though. I think it needs to have a coherent intro and onboarding experience, and we need to fix the performance of the worst stuff (probably by implementing the activity streams and taking a moment to think about the teams feature).

Even if I wanted to market the site, we couldn't apply for the grant, since it's for non profit organizations, and while there's no profit in exercism, it's also not a legal organization of any kind.

I'm going to close this because of the marketing slant, but will open a new issue for language landing pages (if you don't beat me to the punch).

**Comment by masters3d** [comment]
Sound good! I'll think of some content for the lading pages this weekend.
