### ISSUE TITLE
Investigate the state of all the tracks

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2309]
How many people are:

- trying once and never come back?
- submitting code each week?
- submitting code regularly?
- commenting on other people's code?

- How many exercises have no feedback?
- What is the average number of iterations per exercise? What about on different problems?

- What kind of discussions are happening? What kind of feedback? Mostly experienced developers or mostly newbies or a mix/balance?

- Are there a small handful of individuals who are carrying the discussions?

**Comment by pminten** [comment]
The problem here is that you kinda need database access in order to answer these questions.

Actually you need only a subset of the database since the interesting bit is the metadata (user A submitted a solution to exercise B) instead of the data (contents of the solution).

Perhaps its an idea to publish anonymized data (for example with the usernames replaced by numbers and the content omitted) and see what kind of crazy statistics people can draw from it.

**Comment by kytrinyx** [comment]
Yes, some form of anonymized stats could work.

Or, if someone could help define what the actual things we should track are, and how to track them, I could build a reporting engine.

Or I could just do it myself; I just wanted an issue here because it's important to do, even if nobody can help with most of it.

**Comment by kytrinyx** [comment]
I'm raising these questions in a separate (offline) discussion as I investigate some of the questions around making exercism sustainable. I'm going to close this issue.
