### ISSUE TITLE
API for new front end

### ISSUE THREAD

**Issue by mtakac2** [exercism/exercism.io#2322]
I am not really sure what are plans for the API, but we won't be able to move forward with front end without having at least a basic specification (or, yet better, implementation) of API. Is there any plan for this? Is somebody working on it or do we need to start from beginning?

**Comment by kytrinyx** [comment]
I can write the API for the new front-end. Let's outline what's needed, and in which order it would be useful to have it.

**Comment by kytrinyx** [comment]
Can we make a list of the features to convert so that we can agree on the api endpoints that are needed? Also, if we can have some sort of planned order, that would help so that we can add the most useful endpoints at any one time.

**Comment by mtakac** [comment]
I have in mind something like this (in order):

1. **Submission page** (/submissions/:id);
Submission, iterations, files (readme, test suite), comments (list, create, edit)
2. **Team page** (/team/:slug):
Team (edit, destroy), members (list, destroy)
3. **Pending submissions page** (/nitpick/:track):
Submissions
4. **Account** (/accont):
Teams (list, create), invitations (accept, decline), exercises
5 **Dashboard** (homepage for logged in user):
Really not sure what we want to display here

And then the rest, nit stats and whatever we'll need.

Anyway I think we should first decide how we are going to built the API. Is it going to be REST-full API? Are we going to use Hypermedia? Do we want the API to be public or it's just for our frontend? If public, how are we going to document it? (we will need something that will build docs from code - it's really hard to keep docs updated otherwise)

I suggest to create detailed specification before writing any code. There are lots of great tools for it. E.g.: http://editor.swagger.io/. As soon as the specs are ready, actual coding of the API will be quite easy. And also, the specification will help us to come up with really good architecture.

**Comment by kytrinyx** [comment]
I think yes for RESTful. I would love to do hypermedia, though I've never done it before, so I'd need help getting the specification right.

I think it's fine for the API to be public in the sense that it's accessible, but I don't want to worry about building documentation in the first pass. Let's just get this working so we have a reasonable front-end.

> I suggest to create detailed specification before writing any code.

Yeah, the hard part of APIs is generally deciding on the endpoints and payloads. The rest is generally straight forward. Swagger.io looks great!

**Comment by mtakac** [comment]
@kytrinyx I've created a PR with basic API specification (#2338). I've kept it pretty simple, but should be everything we need for the submission page. 
Personally I wouldn't try to implement Hypermedia - it looks like it's not really wort it - I would much rather just "borrow" some of the principles (e.g.: don't use ids, use links). We still need to come up with a way how to let front end know which actions are permitted for the current user and you will be probably able to come up with much better names for JSON attributes.

**Comment by kytrinyx** [comment]
The JSON attributes look fine, I had one question, but the rest seems like good common-sense choices. I agree on the hypermedia. Let's keep it simple and borrow the link idea.

For the actions we might have an authorization call that returns the basic auth for each language, which we can cache on the front-end. At the moment authorization is fairly straight forward and only changes when you submit a solution to a new problem.

This could get more complicated when we add mentorship relationships.

And, now that I think about it, we have something with teams as well. Hm. Yeah, we'll need to think about that a bit, I think.

**Comment by mtakac** [comment]
So I created more complete spec (#2339) adhering to swagger specification. You can view it in interactive editor here: http://editor.swagger.io/. Just copy and paste the file from PR into editor (or import it).

Only missing things (at least as far as I know) are teams and authentication. I need to take a look at the relationships of teams and users and anything else before designing the endpoints. We can use authentication that we use know and switch to the auth via API can be very last step - I don't see any problem there. Also when we will be implementing API authentication we can keep it simple. I like to work with JSON web tokens (http://jwt.io/), it's very easy to implement and should be secure.

I wanted to give you a quick overview of the architecture decisions I've made and discuss some random thoughts:

1. As I've mentioned I borrowed few concepts from HAL. I extended the usage of **links**. I like the idea that client doesn't need to worry about URLs and we won't need versions because of this (I know, you've said API is for now only for exercism itself, but I guess it's good to plan for future)
2. Second HAL concept that I included into the spec are **embedded resources** (although in slightly different way from HAL specification). Embedding the resources that logically belong together will save us some trips to the server.
3. Another thing that I 'borrowed' from HAL is `_`. I use it to mark 'meta' attributes (Things like total number of resources in the collection, number of pages etc.) and I added `_type` attribute for every resource. I guess we won't use it in the beginning, but It's easy to implement and some of other clients may need this.
4. I thought a lot about nesting resources and decided to nest only if it makes absolutely no sense to have the resource on top level. So for example comments, are nested under submission only when creating new one. Collection of comments is on the top level and same result as with nesting can be achieved by filtering (E.g. instead of call to `/submissions/:id/comments` we'll call `/comments?filter[submission]=:id`). This approach is just much more flexible.
5. Every collection has set of parameters that can paginate, filter and order the collection. It just felt right to be consistent and add them, even to the collections where we probably won't use them immediately. Furthermore it can be quite easily implemented in one place for all collections.
6. Another issue I've been thinking about is authorization. The nicest solution I was able to came up with is to use links to indicate to the client what he can and cannot do (E.g. if client can edit a resource add `edit` link to the resource, if he cannot just omit it). Same can be truth regarding few attributes (but really just few), like let's say user's api key.
7. The only endpoint we will need for submission detail page is `/submissions/:id` so I guess we can start with it. We should anyway create some basic structure of the API so we can reuse code.

Regarding the mentorships, I am not really sure what the plan is here, but as I imagine it, it basically means that a user can have many mentors and also be a mentor to many users. I this is the case, it will be quite simple from API point of view: We'll add endpoints for creating, deleting and maybe listing and showing mentorships and we'll just add links (or embedded objects) representing singular mentorships to the user resource. User resource is embedded into the submission, so both user and submissions will have access to mentorships.

What are the plans for the implementation? Have you decided on the tools already? If not, maybe take a look at Grape (https://github.com/intridea/grape) - it's pretty easy to work with - basically Sinatra for APIs and we could use Grape Entities (https://github.com/intridea/grape-entity) or Roar (https://github.com/apotonick/roar) to model data in the API.

**Comment by kytrinyx** [comment]
I agree that we can leave authentication for last.

1. Agreed.
2. This seems reasonable. I'm not sure if it's a premature optimization, but it seems like we already know that these things are going to be needed together, so I think it's fine to just embed them already.
3. I like `_` for meta attributes.
4. Yeah, I've struggled with this concept before, and I think this is a good compromise.
5. Absolutely. I hate adding pagination etc piecemeal later. Let's just make it consistent.
6. If we do this, we will not be able to cache the responses from the server, since everything will be dependent on auth. I don't think this will be a problem right now, though, so this could be fine.
7. Yeah, this sounds like a good place to start.

For mentorships, yes, it's a many-to-many relationship, and the reason I brought it up is because it affects authorization. A mentor is allowed to see anything that their mentee submits, even if the mentor has not done the problem themselves.

I haven't decided when this will be implemented (I'm still finishing up the audit so that I can create the roadmap).

I was thinking of just doing a small Sinatra app for the API, but Grape looks very nice. I wouldn't mind trying it out. I don't have an opinion on grape-entity vs roar vs plain old active record serializer.

**Comment by mtakac** [comment]
Re no. 6: Oh nice! I didn't realize that. And what if we include keys but just with a null values for user that isn't authorize to see the attribute?

**Comment by purezen** [comment]
Hmm.. Grape sounds good. Btw, how do we intend to use it.. on top of Sinatra, or on plain Rack?

**Comment by kytrinyx** [comment]
I've never used Grape so I don't know what makes sense for it. I'm open to suggestions (or pointers to good blog posts about it).

**Comment by mtakac** [comment]
The only reason I can think of why we would want to use it on top of plain Rack (I mean in our current setup) is if we had plans to build the API as a new application. I think we can safely mount it on top of the existing sinatra app.

**Comment by kytrinyx** [comment]
I don't understand the benefits of using using Grape on top of the current Sinatra app. I've been looking through the documentation, but almost everything I find assumes that you're mounting this inside of a rails application. Sometimes it says something about a sinatra app.

What I don't get is _why_ would you want to use grape on top of rails or sinatra? Nobody is talking about the trade-offs of why they would choose one thing or another. All the posts are about "type X, put Y in file Z".

Since the current exercism.io repo is going to become the front-end client, it seems wrong to keep building the api within that repo. It would be much cleaner to start fresh somewhere, but since nobody has suggested that, I feel like there's something obvious I'm missing.

**Comment by mtakac** [comment]
The reason people like to mount grape into Rails / Sinatra app is that it gives you access to all helpers and models you have. You can think of grape as a set of specialized controllers, but you still need some models to access data. 

So we can either create a new repo and have grape as it's own application, which means we will have to create new data layer or we can mount it on top of existing application and reuse the models we already have.

**Comment by kytrinyx** [comment]
OK, I can see how that would be useful.

The current data layer is a complete mess, but it's there and it's reasonably well tested, for a prototype.

I guess mounting the new api into the current application would be the shorter path to getting the front-end under control, and once the front-end has been fully migrated, we could look at moving the grape application out and rebuilding the data layer.

**Comment by aarti** [comment]
I can help with writing tests for the api, if you point me on how to get started.

**Comment by kytrinyx** [comment]
Thank you! I've been ridiculously swamped lately, and I'm trying to figure out how to get started with this. I was at a conference where someone demoed https://github.com/plexus/yaks -- I really liked what I saw. I'll try to get all the boilerplate put together so that it's easier to contribute. I'd love to get this out the door so that we can get rid of the old stuff.

**Comment by kytrinyx** [comment]
I completely failed to follow through on this, and I'm going to table it. I'm so sorry.
