### ISSUE TITLE
[topic] Lowering the barrier to entry

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2323]
It's quite difficult to start using exercism, for two reasons:

- there's no good explanation of what exercism is, how it works, and how to get started, and
- a command-line centric workflow is pretty challenging for beginners

This topic is about the second point: improving the experience for beginners and making it easier for them to get started using exercism.

A number of suggestions have come up:

- an interactive tutorial that walks beginners through all the steps of installing the CLI and doing an exercise (#2047)
- native installers so that beginners don't have to learn about PATH (#1706, #1707)
- a cloud-based hosted editor (#2261)
- an integrated editor (#2107)
- a GUI front-end to the CLI
- command-line tutorial (#2254)
- a web form to submit the code (#2191)

Most of these solutions are quite involved, and none of them are about improving the core experience of exercism (the conversations). The simplest of these, I think, is providing a web form to submit the code. The user would still have to do the exercises locally (or in the cloud), but could avoid the whole CLI by just copy/pasting their solution into the web page.

While I think that it's extremely important to make exercism friendly for beginners, I think that it's more important to ensure that exercism is _useful_, and that beginners get good, useful feedback than make it easy for them to get started using the site.

I would still like to collect ideas and suggestions for addressing this problem, but it is unlikely that we will work on actively solving this until the core issues of ensuring that the conversations happen and that they are useful.

**Comment by JaKXz** [comment]
I really appreciated the skeleton file that was provided for the JS `Bob` exercise. It gave a great launchpad so that I could focus on starting the problem as opposed to figuring out how to get set up in the context of exercism's provided tests.

That said, I've noticed some other languages are lacking in this area, and I think adding those for the first exercises would be the least amount of effort required to provide the most value in terms of lowering the barrier to entry. Haskell is a great example - it would be fantastic to have a playground to learn the syntax and get up to speed with the thinking behind it. 

I personally think that being familiar with CLIs is just a part of everyday development, so for beginners it's a great chance to get comfortable in that environment.

**Comment by kytrinyx** [comment]
I think you're right that a skeleton file for the first exercise is a low-hanging fruit.

**Comment by hmistry** [comment]
@kytrinyx It will be really helpful if you formerly defined what exercism is, what it isn't, and how you envision it to work. This way it is clear to us all as we think of ideas. Also once you've establish that, we can look at the landing page and other pages and see if the messaging conveys the right message to the user.

**Comment by kytrinyx** [comment]
I know enough now to define what exercism is, but I don't know where I need to put this. README? Issue?

**Comment by hmistry** [comment]
@kytrinyx Let's put it in an issue for now so it can be discussed and refined if needed. Also reference it from other issues like this one, the marketing and branding issue, and any other relevant one.

**Comment by kytrinyx** [comment]
Ok, that's a good idea. I am about to travel back home from a conference, and I will work on a write up in the next couple of days, and I'll reference it from here and a few of the other issues where this is relevant.

**Comment by nhu313** [comment]
I know as a developer we're supposed to be dry, but I find that there are too many clicks and I got confused (and I'm also very lazy). What if we duplicate the information or having partial info so that everything is in one page for setup. Something like this:

1. Login with a github account on [exercism](http://exercism.io/)
2. Get your API key
  1. Click on your profile
  1. Click "Account"
  1. Click "Setting"
  1. You should see an API key there. Keep this tab open.
3. Download the CLI ([Mac](http://help.exercism.io/installing-the-cli-on-mac.html), [Linux](http://help.exercism.io/installing-the-cli-on-linux.html), [Windows](http://help.exercism.io/installing-the-cli-on-windows.html))
  a. If you're using Linux, the easiest way is to download the script

  ```bash
    curl -O https://raw.githubusercontent.com/exercism/cli-www/master/public/install
    chmod +x install
    ./install
  ```
4. Add your API key from step 2 `exercism configure --key=YOUR_API_KEY`
5. Fetch the exercise `exercism fetch elixir`
6. Run the test `elixir bob/bob_test.exs`
7. Open up `bob/bob.exs` and add your code to make the tests pass
8. Submit your code for nitpicking `exercism submit bob/bob.exs`
9. [Nitpick](http://help.exercism.io/nitpicking-code.html) others code by logging into the [website](http://exercism.io)
  a. Click on "Nitpick"
  b. Select "Elixir"
  c. You can view other submissions by recent submissions or exercises you submitted

**Comment by kytrinyx** [comment]
Thanks @nhu313. I've linked to this comment from one of the other threads where others have chimed in with thoughts and suggestions.

**Comment by kickinbahk** [comment]
Another thing that I had to do when first getting exercism is run `brew update` and `brew doctor` before I could pull down exercism. Most beginners will not know how to do this and may not know how or what to search for. Not sure that it should be included in the README, but it is worth discussing how we might want to let beginners know what to do if they are running into an issue with homebrew.

**Comment by kytrinyx** [comment]
@kickinbahk that's a great point. I will add that to the default Mac instructions today.

**Comment by kytrinyx** [comment]
We've made a bunch of improvements over the past year. I'm going to go ahead and close this.
