### ISSUE TITLE
[topic] Getting Started

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2324]
There are a number of things that make it difficult to get started:

- it's unclear what exercism is, who it's for, how it works, and what is available
- the existing user interface is quite confusing
- once you submit your first exercise, it's not clear what is supposed to happen
- "what is supposed to happen" (great feedback) doesn't always happen
- people are unfamiliar with TDD

Ensuring that people understand what exercism is about is absolutely crucial to making exercism work. The core functionality of exercism (rich conversations and ensuring that everyone who submits code gets high quality feedback) cannot happen unless people who come to the site understand the point of the site and how it works.

--------

There are a number of suggestions for fixing some of these issues, and we probably need to come up with more:

* Language-specific language pages (#2299) will make it clear what languages are available and how to get started in that language.
* A "hello world" tutorial that would interactively let people experience how exercism works (#2021)
* Putting a README at the root of the language dir when fetching exercises (#1931)
* Activity stream so that people see relevant and interesting content (#1899)
* Encourage existing users to provide feedback to people after their very first submission to the site (#1660)
* Add documentation about the fail/fix/refactor workflow (#1869)
* Fix the onboarding flow so people get the right information at the right time (#1717 tries in part to address this)
* Add a blog (see below)
* Add a `GETTING_STARTED` file to the first problem in each language (the Ruby track has this in Hamming) (#2254)

----------

There are also some resources that could be useful to point people to:

* Overkill https://www.youtube.com/watch?v=GWEEPt8VvmU
  (video) This talk basically explains the essence of what exercism is about.
* Nitpicks and Devils http://www.codenewbie.org/podcast/nitpicks-and-devils
  (audio) The CodeNewbie Podcast episode about exercism
* The Magic Tricks of Testing https://www.youtube.com/watch?v=URSWYvyc42M
  (video) This talk lays out the basics of unit testing in a beautiful and understandable way.

**Comment by mtakac** [comment]
Hey @kytrinyx sorry if it was mentioned somewhere before, but have you considered having a blog? I realize it won't solve the whole issue, but I think it could at least partially help. There could be plenty of great articles explaining concepts behind exercism, code reviews & TDD in much more detail than you could ever have on the exercism website itself.

**Comment by kytrinyx** [comment]
Yeah, I've considered it and I keep telling myself I should do it... but I have a lot of trouble keeping up with the issues on GitHub and trying to keep on top of bugfixes, and a blog is a huge amount of effort to get right.

That said, I think that you're right. I'm putting it on the list of suggestions.

**Comment by prathamesh-sonpatki** [comment]
I think many people might have written blog posts about how they got started with exercism, or how they fixed any issues they got while getting started. We can ask them to send us the link of their blog and show it somewhere on the site?

**Comment by kytrinyx** [comment]
I'm trying to find ways of making it so that people don't have problems getting started with exercism, rather than trying to work around that by explaining how to get started. While it could help to have documentation and links to documentation, I think that it would be more effective to change the site to make it easier to understand/use.

**Comment by bIgBV** [comment]
I think having a flow of sorts when the user first logs in would be useful. Something like

```
user logs in with github -> user is shown the tutorial with a few simple commands to install the 
CLI* -> User is shown a list of languages to choose from -> user selects  a language -> 
User lands on language landing page where further information about getting started in the language is shown
```

\* We can have a video with more information regarding what the CLI is or a link to relevant documentation.

The reason I came up with this idea is because for someone who is completely new to programming the whole command line experience would be new and kinda daunting. When there is some hand holding involved people become more comfortable and once that happens they start exploring things on their own.

**Comment by trueheart78** [comment]
Two notes I just want to put down here, after talking with @kytrinyx about this. They may or may not be relevant any longer(it's been a very rough weekend), but I didn't want them to be forgotten.

First, as we've been discussing how to lower the barrier to entry, one of the thoughts that came to mind was, what if we had an actual installer for the CLI? We should be able to re-use the same binary, but this would also allow us to take care of the PATH dependency. We'd even be able to create a proper un-installer at that point.

Second, it's evident that there are going to be a lot of users that may be uncomfortable at the command-line. There was a bit of a discussion about creating a GUI wrapper around the CLI that could make submitting and retrieving exercises. It'd be prefered to use a cross-OS compatible language/deployment strategy so that we could keep development cost and time lower. [QML][https://github.com/go-qml/qml] looks like it might be an option for use with Go.

**Comment by sguermond** [comment]
@mixolidia came up with a list of issues and suggestions for the basic getting started process and the first few uses of the site by a new user

**1. Getting started**
**Issues**
- lots of jargon
- too many clicks to get anywhere
- Overal website flow issues
- no clear way to get started, should have a big START HERE button that takes you through a linear flow
- unclear who is the audience. Beginners? Advanced beginners? Contributors?
- “Welcome new users” page is very disorganized, too many paths to take, too much reading, different content (using product vs contributing to development)
- assumes knowledge of github/issues/pull requests/downloads/etc etc etc
- assumes knowledge of the command line
- there is no clearly defined single installation guide!!! cli.exercism.io vs help.exercism.io…

**Suggestions**
- Reword “Welcome new users”/front landing page
- make one single quick start guide
- make it easy to know where to start
- maybe have beginner vs advanced tracks?
- clear, obvious link to gitter support chat everywhere
- Include basic requirements to install exercism (ex. homebrew) 
- need to do some user experience testing/design

**2. Using the site as a new user**
**Issues**
- No way to give nits if you haven’t onboarded
- Getting help is confusing
- Submitting Github issues can be offputting
- first problem submission is very long and has multiple tests
- little/no discussion
- no way to know how recently the help/install page for a language was updated, instructions/software may have changed

**Suggestions**
- make the first problem “hello world” or something easy so users can submit asap and see what nitpicking is all about
- only have 1-2 tests for the first problem
- make early problems easy so users can spent 30min/1h on their first few visits and make a bit of progress rather than spending 4h on a single problem and getting discouraged
- have opt out “no thanks, I just want to see what’s up” button on the onboarding process so people who want to play with the website don’t get bogged down in the process/mentors who would rather nitpick than solve problems can go ahead and do it
- have more reminders to give feedback to other users (ie. “give some feedback to X about X problem” banner like on user dashboard page, but on every non-help page, even when logged in)
- “stale” track warning: if a help page hasn’t been updated in 2 months, have a sticker on the page with “this track hasn’t been updated in a while. It may not be accurate. If it’s not working for you, you should report it here [link to new github issue]”
- have separate github repos for issue reporting: 1 for contributors, 1 for users. If they are directed to the issues opened by contributors, users may feel that their issue isn’t “serious” enough and they won’t report it
- directly link to “open new issue” form to minimize number of clicks

**Comment by kytrinyx** [comment]
OMG this is brilliant, @sguermond @mixolidia! All of your comments are spot on, and your suggestions are great. It feels like every single point you made could be turned into a todo list.

I have a few (kind of random) thoughts...

> make the first problem “hello world”

We've started this process, but most languages are missing this exercise. Check out this issue, and related issues: https://github.com/exercism/todo/issues/12

Maybe we could make some sort of community-wide campaign to add a hello-world to every track (with the exception of C++ where the maintainer doesn't think it's needed). I don't know what a campaign would look like, but I know that some people are really skilled at getting a bunch of people coordinated and excited and all working towards the same thing. Maybe someone from RGSoC would be able to help point us to some resources about how to run open-source campaigns?

> make early problems easy

We have tried to do this, but clearly we've failed at it. I think we should think about how we can fix that. E.g. how can we make it easy for people to say that a problem is too hard, or say that they're stuck so that we can reorder exercises? How can we make it so that they report problems instead of getting stuck/discouraged?

> maybe have beginner vs advanced tracks?

Take a look at this issue: https://github.com/exercism/x-common/issues/63 - if we can classify exercises, then we could probably do a much better job of showing people only what they're currently interested in.

I think that we can stay with single tracks for a language, but we could do a lot more around what we show you based on whether you're beginner or advanced.

**Comment by kytrinyx** [comment]
Check out [this comment](https://github.com/exercism/exercism.io/issues/2323#issuecomment-126985318) by @nhu313 for some more great suggestions about easing the whole getting-started process.

**Comment by Skarlso** [comment]
I don't know, it might be because I a background in these things, but when I got started with exercsim it was pretty easy to follow the steps and understand what it does and what it is. I had zero problems getting started.

- Download the cli
- Set it up with API key
- Work, work, zug, zug
- Submit
- Bask in the glory that is your code

**Comment by kytrinyx** [comment]
@Skarlso I appreciate the feedback. We've made a bunch of changes since this ticket was opened. I think that we've gotten to a place where the onboarding is significantly improved. There are still a ton of little things that could make the process smoother, especially for people who are fairly new to programming.

I'm going to leave it open for now, until I can figure out how to better organize the roadmap and suggestions (working on that).

**Comment by Skarlso** [comment]
@kytrinyx You are most welcome. I do love exercism. It made me learn. Which I like. :)

**Comment by kytrinyx** [comment]
:heart:

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this now. We've got a number of UX discussions open that are addressing it at various levels.
