### ISSUE TITLE
Unable to submit - unable to identify track and problem

### ISSUE THREAD

**Issue by Assimilationstheorie** [exercism/exercism.io#2335]
my bad. :(

**Comment by bIgBV** [comment]
Make sure you ran `exercism configure` with the right API key.

Try running `exercism debug` and paste the input here.

**Comment by kytrinyx** [comment]
@Assimilationstheorie did you get this resolved?

**Comment by gabivoicu** [comment]
I'm having a similar issue, trying to submit my first exercise(yay!), but it's saying
```Unable to submit - unable to identify track and problem```

**Comment by kytrinyx** [comment]
It looks like the configuration can't figure out where `Desktop/exercism/` is. Try adding the `~` to represent your home directory:

```
exercism configure --dir ~/Desktop/exercism
```

**Comment by gabivoicu** [comment]
yay, it worked! Thank you, @kytrinyx !

**Comment by kytrinyx** [comment]
sweet! :heart:

**Comment by mcdiamondz** [comment]
Unfortunately, i am having this same issue and i have done everything correctly. I read the above comments and compared to what i have been doing

:~/$ exercism configure --key=xxxxxxxxx --dir /home/wen/Downloads/Torrents

:~$ exercism debug

**** Debug Information ****
Exercism CLI Version: 2.1.1
OS/Architecture: linux/386
Home Dir: /home/wen
Config file: /home/wen/.exercism.json
API Key: xxxxxxxxxxxx
API: http://exercism.io [connected]
XAPI: http://x.exercism.io [connected]
Exercises Directory: /home/wen/Downloads/Torrents

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please include this information (except your API key. Keep that private).

:~$ exercism submit /home/wen/Downloads/Torrents/Program.cs 
2015/06/20 11:20:03 Unable to submit - unable to identify track and problem

I tried on my windows virtual machine, the issue is still the same.

C:\Users\Admin\exercism>exercism.exe configure --key=xxxxxxx --dir C:\Users\Admin\exercism
The configuration has been written to C:\Users\Admin\.exercism.json
Your exercism directory can be found at C:\Users\Admin\exercism

C:\Users\Admin\exercism>exercism.exe debug

**** Debug Information ****
Exercism CLI Version: 2.1.1
OS/Architecture: windows/386
Home Dir: C:\Users\Admin
Config file: C:\Users\Admin\.exercism.json
API Key: e260b44f974db2dd80d080d2b6abe4399dc27e40
API: http://exercism.io [connected]
XAPI: http://x.exercism.io [connected]
Exercises Directory: C:\Users\Admin\exercism

If you are having trouble and need to file a GitHub issue (https://github.com/ex
ercism/exercism.io/issues) please include this information (except your API key.
 Keep that private).

C:\Users\Admin\exercism>exercism.exe submit C:\Users\Admin\exercism\Program.cs
2015/06/20 02:32:31 Unable to submit - unable to identify track and problem

**Comment by kytrinyx** [comment]
What command are you running to submit, and where are you running it from?

**Comment by mcdiamondz** [comment]
On my Linux machine i tried running the submit command from all these prompts

wen@DBlur:~$ exercism submit /home/wen/Downloads/Torrents/Program.cs
 2015/06/20 11:20:03 Unable to submit - unable to identify track and problem

wen@DBlur:~$ exercism submit ~/Downloads/Torrents/Program.cs
2015/06/20 11:13:37 Unable to submit - unable to identify track and problem

wen@DBlur:~/Downloads/Torrents$ exercism submit Program.cs 
2015/06/20 11:05:00 Unable to submit - unable to identify track and problem

**Comment by kytrinyx** [comment]
@mcdiamondz What is the `exercism debug` output on your linux machine?

The error you are getting suggests that the files you are submitting are not located where the exercism CLI is configured to look for them. Since the CLI uses the filesystem structure relative to the configured exercism directory to determine the track/problem, I need to see both the configured exercism dir, as well as where you're submitting the file from in order to figure out if this is the problem.

For your windows machine I just saw that the last line describes the command that you're using to submit:

```
C:\Users\Admin\exercism>exercism.exe submit C:\Users\Admin\exercism\Program.cs
```

The CLI is configured with the following as the exercism directory:

```
Exercises Directory: C:\Users\Admin\exercism
```

When you fetch a problem, it will be put in `C:\Users\Admin\exercism\LANGUAGE\PROBLEM\`, and if you move the solution file to a different location, then the CLI cannot figure out what language and problem the solution is for.

**Comment by pgragg** [comment]
Same deal here: 


    C:\Users\Piper>exercism submit hamming.rb
2015/06/21 21:43:51 Unable to submit - unable to identify track and problem

    C:\Users\Piper>exercism debug

**** Debug Information ****
Exercism CLI Version: 2.1.1
OS/Architecture: windows/386
Home Dir: C:\Users\Piper
Config file: C:\Users\Piper\.exercism.js
API Key: xxxxxxxxxxxxxxxxxxxxxxxx
API: http://exercism.io [connected]
XAPI: http://x.exercism.io [connected]
Exercises Directory: ~/Desktop/exercism

**Comment by kytrinyx** [comment]
@pgragg your config specifies: `Exercises Directory: ~/Desktop/exercism`. This means that if you say `exercism fetch ruby hamming` or `exercism fetch ruby`, it will put the hamming exercises in `~/Desktop/exercism/ruby/hamming/...`. For the submit to work, hamming.rb must be within the expected location: `~/Desktop/exercism/ruby/hamming/hamming.rb`

**Comment by pgragg** [comment]
Oddly, it is! 

:/ I'll try this on a mac later. 

![Screenshot](https://cloud.githubusercontent.com/assets/9450846/8274571/72356f28-1862-11e5-9d86-f20fc19f5df4.png)

**Comment by kytrinyx** [comment]
That's so weird. What happens if you say `exercism configure --dir=C:\Users\Piper\Desktop\exercism`?

**Comment by pgragg** [comment]
Haha that did it. Thanks very much!

**Comment by kytrinyx** [comment]
Sweet. There must be something about relative vs absolute paths that it's not handling at the moment.

**Comment by alecsechechel** [comment]
Help me ) I have same problem ((

**** Debug Information ****
Exercism CLI Version: 2.2.1
Exercism CLI Latest Release: 2.2.1
OS/Architecture: darwin/amd64
Build OS/Architecture /
Home Dir: /Users/admin
Config file: /Users/admin/.exercism.json
API Key: ***
API: http://exercism.io [connected]
XAPI: http://x.exercism.io [connected]
Exercises Directory: /Users/admin/Documents/Develop/Swift/exercism

I try call
iMac-admin:~ admin$ exercism submit Documents/Develop/Swift/exercism/Leap/Leap.xcodeproj
2015/08/26 18:18:31 Unable to submit - unable to identify track and problem

What do I do wrong?

**Comment by kytrinyx** [comment]
You have configured the exercism CLI like this:

> Exercises Directory: /Users/admin/Documents/Develop/Swift/exercism

If you say `exercism fetch swift leap`, then it should put the leap exercise in 

```
/Users/admin/Documents/Develop/Swift/exercism/swift/leap/
```

When you submit, the CLI uses the configured directory path along with the path of the file you're submitting to figure out which language track and exercise it is, so the problem needs to stay under `/Users/admin/Documents/Develop/Swift/exercism/swift/leap/`

**Comment by alecsechechel** [comment]
So I do
1. configure new rout
Exercism CLI Version: 2.2.1
Exercism CLI Latest Release: 2.2.1
OS/Architecture: darwin/amd64
Build OS/Architecture /
Home Dir: /Users/admin
Config file: /Users/admin/.exercism.json
API Key: ***
API: http://exercism.io [connected]
XAPI: http://x.exercism.io [connected]
Exercises Directory: /Users/admin/Documents/Develop/Swift/exercism

2. I made exercism fetch swift leap
3. Put in /Users/admin/Documents/Develop/Swift/exercism/swift/leap/ my project

4. iMac-admin:~ admin$ exercism submit Documents/Develop/Swift/exercism/swift/leap/
2015/08/27 10:50:42 Unable to submit - unable to identify track and problem

**Comment by kytrinyx** [comment]
You need to submit the actual files that you want to submit, not the containing directory.

**Comment by alecsechechel** [comment]
thank it is working!
