### ISSUE TITLE
Sum of Multiples missing key test cases.

### ISSUE THREAD

**Issue by julianandrews** [exercism/exercism.io#2341]
Currently all the test cases for the "Sum of Multiples" exercise on at least several language tracks involve only sets of factors that are relative primes of each other. Also, only one set of 3 factors is tested, and the cap is set below the factors' lcm in that case which avoids testing some clear pitfalls. 

This creates the possibility for reasonable seeming but incorrect attempts that pass all tests. Scanning through the python solutions, for instance, I found at least a couple solutions that passed all tests, but would fail on factors of 4 and 6 with a cap of 13 or higher.

The issue seems to apply to at least the Ruby, Python and Javascript tests. The Haskell tests address the relative prime issue, but could probably benefit from at least one test with 3 or more factors that aren't relatively prime. I'm guessing the issue applies to other languages as well.

I would suggest adding a test case with factors of 4, 6, and 7 and a cap of 100. This should catch almost any reasonable seeming but incorrect attempt.

Anyway, I'd be happy to fix this myself (at least for Python, Ruby, Javascript, and Haskell), but since it seems to apply to a broad range of languages, I wasn't sure if there was any particular protocol. Is this the right repo for this issue?

-------

Here's the list of languages that have this problem.

- [ ] xcpp
- [ ] xcsharp
- [ ] xelixir
- [ ] xerlang
- [ ] xfsharp
- [ ] xgo
- [x] xhaskell
- [x] xjavascript
- [ ] xperl5
- [x] xpython
- [x] xruby
- [x] xswift

**Comment by kytrinyx** [comment]
I always appreciate improvements to the exercises. I'll ping the other track maintainers so that anyone who has an opinion can chime in.

/cc @exercism/track-maintainers

**Comment by etrepum** [comment]
Any improvements to any Haskell test suite would be happily accepted :)

**Comment by henrik** [comment]
Sounds like a given :thumbsup: @kytrinyx, I guess it mostly comes down to the policy on test fixes: how should they be done, if we want to keep languages in sync? How has this been done before?

One way I can think of is to accept a PR, merge the code but leave the PR open with a `- [ ] Checklist` for any remaining languages, then mention maintainers.

**Comment by pminten** [comment]
Well in an ideal world we'd just use templating to write the cases for exercises like this since they should be 100% portable (as long as you don't go use numbers that overflow fixed size ints/floats). But this is not an ideal world. ;)

Realistically the usual checklist dance seems to be the best option.

It would be good to have a list of "good" extra test data in this ticket to simplify changing the exercises in various languages.

**Comment by kytrinyx** [comment]
Sonia Keys has experimented with templating test case data, and writing a custom generator for the problem. It seems like it might work to extend that, though I can't see 20 different tracks all implementing this in the near future.

So yes, realistically, a checklist would probably be the way to go.

@JulianAndrews Would you suggest a canonical list of good test data for this problem? (I'm guessing that you have some ideas).

Here's the list of languages that have this problem - @JulianAndrews let me know if it's ok if I edit your original issue to add the checklist.

- [ ] xcpp
- [ ] xcsharp
- [ ] xelixir
- [ ] xerlang
- [ ] xfsharp
- [ ] xgo
- [ ] xhaskell
- [ ] xjavascript
- [ ] xperl5
- [ ] xpython
- [ ] xruby
- [ ] xswift

**Comment by JulianAndrews** [comment]
Yup, go ahead and edit the issue!

As for test data, thinking on it more, I think I'd add two test cases to the ruby tests:

Cap | Factors | Result
--- | --- | ---
1 | nil | 0
3 | nil | 4
10 | nil | 23
1000 | nil | 233,168
20 | 7, 13, 17 | 51
15 | 4, 6 | 30
150 | 5, 6, 8 | 4419
10,000 | 43, 47 | 2,203,160

The 6th and 7th are new, and should catch any incorrect attempts at the most obvious non brute force approach. Since the brute force approach is overwhelmingly the most popular, I figure the large number case should still be the last test. The 6th is easy to verify by hand, which should help people understand the problem if that's the one giving them trouble. The 7th hits a bunch of different edge cases.

**Comment by soniakeys** [comment]
Go currently has these (non 3,5) cases,

	{{7, 13, 17}, 20, 51},
	{{43, 47}, 10000, 2203160},
	{{5, 10, 12}, 10000, 13331672},
	{{1, 1}, 10000, 49995000},
	{{}, 10000, 0},

(I don't remember reasoning behind them.)

I'm very much in favor though of common test data.  Templating aside, A number of problems now have  data in x-common as <problem>.json.  Collaboration on this would be great.  Discussion on which test cases to include could happen here or as issues and PRs on the x-common json file.

**Comment by kytrinyx** [comment]
This has been fixed.
