### ISSUE TITLE
WordCount test failed, yet output printed in console is the same

### ISSUE THREAD

**Issue by Vulchare** [exercism/exercism.io#2350]
In the WordCount exercise the result of the test includeNumbers() is false yet when I print the results to the console the outcome is exactly the desired result for the test.

Also for the test ignorePunctuation() the method i created to remove any non-alphanumeric character seems to ignore the characters '$' and '^'. How can I include those to be removed and any other character that would possible be ignored?

Submission:
http://exercism.io/submissions/961097f619e543ff9c2ef106227de22f

NB: I've added the following line after submitting
				<code>str = str.replaceAll("  "," ");	</code>
in the getAlphaNumeric(string str) method to remove double spaces.

**Comment by kytrinyx** [comment]
Hi @Vulchare - I don't know JavaScript so I can't give you specific advice on this, but I was thinking it might be possible to rework the question so that it could go on StackOverflow? People tend to be great about answering this type of thing there.

In order to post it there I would recommend not linking to the exercism submission (since the question isn't really about exercism--it's about javascript or perhaps testing with jasmine). Instead I would describe (with specific inputs/outputs) what you expected and what you're actually getting.

**Comment by kytrinyx** [comment]
Another option would be to submit what you have to exercism and describe your problem in the comment thread. That would put your code in front of other people who are doing javascript.

**Comment by Vulchare** [comment]
Hi Kytrinyx, It's Java ;) But you're right. Stackoverflow would be a good idea. Thx

**Comment by kytrinyx** [comment]
Oh, hah. Yeah, I actually do know some Java, but yeah--I'd be willing to bet that I'd get it wrong :)

**Comment by Dog** [comment]
I went ahead and pulled the exercise to sanity check it.

Running gradle with your code is correctly throwing failed. The problem is punctuation. You are counting `1,` in includeNumbers() rather than `1`. If you fix punctuation handling, then you should pass all the tests correctly.

**Comment by Vulchare** [comment]
I´ve revised my code and the problem was indeed the punctuation. By using regular expressions in my replaceAll() method I managed to solve the issue. Solution has been submitted :)

Thx!

**Comment by kytrinyx** [comment]
Sweet!
