### ISSUE TITLE
Direct link to account/exercises?

### ISSUE THREAD

**Issue by andreimoment** [exercism/exercism.io#2352]
Right now the only way to view my exercises is to go to account and then click on exercises. This is a very frequent pathway I am taking and I'm wondering if it would be possible to add a My Exercises option to the menu under my account name.

**Comment by kytrinyx** [comment]
That's interesting; we used to do a couple of things:

1. We had current exercises in the top menu bar. For people who are doing all the exercises in all the tracks, it gets really unweildy, because the list is longer than the page, and scrolling in menu bars is not easy.
2. We had the whole menu on the same tab of the same page. Again it got a bit unweildy when there was a lot of content.

I'm sure we can find a better way to make these quickly accessible.

Do you look at exercises that you've completed or mostly just exercises that you are still working on?

Is there a section on the main dashboard with your current exercises on it? I know we talked about doing that, but I can't remember the outcome off the top of my head.

**Comment by andreimoment** [comment]
Since I submitted this issue, I discovered that exercism.io/ and exercism.io/myusername both show a list of my current exercises. So I would consider this closed. Thank you for responding.

**Comment by kytrinyx** [comment]
Oh, nice! Thanks for checking back in.
