### ISSUE TITLE
Link to own exercise from 'recently viewed' list: 'Exercise not found'

### ISSUE THREAD

**Issue by LadyLovesCode** [exercism/exercism.io#2355]
Depending where you where in the app, there isn't always a direct link to your current exercises (Notifications.) This led me to click the link to view a list of my recently viewed exercises and choose my own exercise from the list. This link consistently doesn't work. I get an error telling me that the exercise wasn't found. 

See here: http://cm.d.pr/1dpVS/5G3rxVfU

This is probably not a typical path one would follow to try and get to their own exercises, but the option is presented to you, so I just thought I'd mention that it doesn't seem to work. This is true at least in my case.

**Comment by kytrinyx** [comment]
I'm torn as to whether to put this as a bug or just a massive UI fail.

For a while I had a list in the top menu that was "your current exercises", but some people have basically done all the exercises in all the languages, and they might be working on 50 different exercises at once, so that list was completely unweildy.

The current paths seem to be either:

1. click on the exercism.io logo top left to get back to the "dashboard" (I know, that's a very pretentious term in this context...), or
2. navigate to "my account" and then click "exercises" which is more clicks.

Do you have any suggestions?

Or... in your podcasting days, have you come across any UX people who would jump at the opportunity to contribute to a growing open source project? (Heh. One can always hope!)

**Comment by LadyLovesCode** [comment]
I will definitely be on the lookout for someone who might be able to help with this. 

Though, I did just want to mention that this particular issue is slightly different from that which I know at least one other person created an issue for. The link to my exercise simply doesn't work when clicked from the list of recently viewed exercises. I didn't know whether you caught that the first time around. 

There might even be a reason for this that I'm unaware of, but from my perspective it seemed to be a bug. http://cm.d.pr/1dpVS/5G3rxVfU

**Comment by kytrinyx** [comment]
> The link to my exercise simply doesn't work when clicked from the list of recently viewed exercises.

That was not entirely clear to me. I need some more information in order to be able to investigate the problem. What is the exact link that is failing, and where do you expect it to go?

The screen cap you're posting shows the notification page, which links to the "recently viewed" page. Is it the "recently viewed" link that isn't working? Or does the "recently viewed" page have a link on it to one of your exercises, but that the link gives you a 404?

**Comment by LadyLovesCode** [comment]
So, if I go to Notifications and click to view the list of exercises I have recently viewed, I can see all of the exercises I've recently nitpicked or otherwise looked at. This includes my own Hamming exercise. If I click that link to my own exercise, it gives me a blue box (as seen at the end of my screencast) saying 'exercise not found.' I then have to navigate to my exercise another way. Luckily the page I'm sent to at that stage has a list of my exercises and so I can access it from there. 

Again, I realize that this isn't a usual way of navigating to your own exercise, but the option is presented to you and doesn't appear to work. The easiest solution, unless I am misunderstanding why I'm being told 'exercise not found,' might be to simply exclude one's own exercise from the list of 'recently viewed' exercises altogether. 

Does this make sense?

**Comment by kytrinyx** [comment]
oh you posted a screencast? I only saw a screen-grab (picture)! That explains it.

The link should totally work. This is a bug.

**Comment by LadyLovesCode** [comment]
Yeah, not the best UX on the part of Droplr, either, to have that 'play' button below the fold. I'm sorry about that! It's cracking me up to imagine you going, ¯\_(ツ)_/¯ 'What am I supposed to being looking at?!'

**Comment by tejasbubane** [comment]
This works for me. I can click on my own submissions from `/looks` and it is properly redirected to my submission.

**Comment by kytrinyx** [comment]
This is the same bug as the can't log in / ghost user problem. I've fixed your account, @LadyLovesCode -- but the underlying bug is still there.
