### ISSUE TITLE
Exercise code escaping formating

### ISSUE THREAD

**Issue by ThomasZumsteg** [exercism/exercism.io#2380]
Some escape sequence in a submitted exercise causes the submitted exercise code to breakout of the code formatted box. Likely cause is triple back-ticks.

[Example](http://exercism.io/submissions/56abfba48d714ec8a4228ea1938e15f9)

**Comment by kytrinyx** [comment]
Thanks!

**Comment by Tonkpils** [comment]
Interestingly enough, Github markdown has this same issue. Markdown will match the first closing backticks 

```python
"""
```helloworld
> Cool
```helloworld
```
"""
See?
```

Not sure what a good solution would be for this one-off case of attempting to include markdown backticks

**Comment by kytrinyx** [comment]
Indeed. Wow, OK, so not really a solved problem, probably.

**Comment by NobbZ** [comment]
AFAIK you can circumvent this by using `~~~` as fence:

~~~
"""
FooBar
```
BarFoo
```
"""
~~~

Otherway around should work also:

```
~~~
~~~
```

(This does not work in the JavaScripted preview, so I have to comment to check if it is a general github problem)

**Comment by NobbZ** [comment]
OK, it does NOT work, you can open with a tilde-fence and close with backtick-fence.

Where can we report github-markdown-parser related bugs?

**Comment by kytrinyx** [comment]
I've no idea!

**Comment by kytrinyx** [comment]
We upgraded to a version of the syntax highlighting library that I think has a fix for this. Is this still an issue?

**Comment by ThomasZumsteg** [comment]
Still an issue.
[example 1](http://exercism.io/submissions/9bd0c50e30f443038c4ac9bb450263b5)
[example 2](http://exercism.io/submissions/56abfba48d714ec8a4228ea1938e15f9)

**Comment by kytrinyx** [comment]
Thanks, @ThomasZumsteg!

**Comment by mfrost** [comment]
As far as I can tell, this has to do with the [#md](https://github.com/exercism/exercism.io/blob/master/lib/app/helpers/markdown.rb#L18) helper. As we already know the language of the `Submission`, we automatically wrap all of the content in a codefence. Redcarpet is unaware of the significance of comments in the `Submission` body, and reads ahead until it finds a closing backticks. In psuedo-markup, it is read something like:

```html
<code>
###
Comments in Code 
</code>
More comments
###
<code>
..remainder of file
</code>
```

In order to fix this, we might consider splitting the `#md` helper into one just for rendering code in which case we can escape all contained backticks before processing. We don't want to apply this to comments as they are a mixture of plain text and codefences.

**Comment by kytrinyx** [comment]
Let's create two helpers, one for code and one for regular markdown.

**Comment by mfrost** [comment]
Ok, I'll give that a shot tomorrow.

**Comment by mfrost** [comment]
Fought this for a while, but realizing I might be going about it the wrong way. My understanding is that `submission.solutions` are always source files. If that is correct, do we need to run them through `#md` at all? Seems like we really just want the good highlighting bits like:

```ruby
formatter = Rouge::Formatters::HTML.new(
  css_class: "highlight #{lexer.tag}",
  line_numbers: true
)

formatter.format(lexer.lex(code))
```

Are there cases where a `submission.solution` is actually markdown that needs parsing?

**Comment by kytrinyx** [comment]
No, you're absolutely right. `Submission.solution` is always going to be source files.
