### ISSUE TITLE
cannot submit Unable to submit - unable to identify track and problem

### ISSUE THREAD

**Issue by arashbi** [exercism/exercism.io#2444]
I am trying to submit for clojure bob, and  I got a Unable to submit - unable to identify track and problem.
I am behind a rather nasty proxy, I wonder if that is the problem.

**Comment by jtigger** [comment]
Actually, that error message tends to indicate that the current working directory is other than the exercism root.

I'm assuming you're on a *nix setup.  Could you post your debug output (with the api key redacted)

```bash
$ exercism debug | grep -v "API Key"
```

Doing so also tests your connectivity with the API.  And also your current working directory:

```bash
$ pwd
```

The CLI will only submit iterations from paths underneath `Exercises Directory`.  If `pwd` is not within that path, the CLI will fail to find it and give this message.

The fix is to ensure that your solution files are contained within the `Exercises Directory`.  Either, move the files there or configure that location.

You'd do the latter like so (for example, if you've place your solution files under the path `~/workspace/exercism/clojure/bob/`):

```bash
$ exercism configure --dir="/Users/johndoe/workspace/exercism"
```

If that's not working, please post your debug output and pwd and we'll have a look-see.
