### ISSUE TITLE
Class defined multiple times

### ISSUE THREAD

**Issue by sguermond** [exercism/exercism.io#2464]
I'm running into an issue where multiple things are called Problem, Language, etc. 

They tend to reference the same object (problems, language tracks, etc) but with only a subset of the information. For example, Problem in one section of the code will only have a track_id and a slug, but Problem in other sections of the code will have a blurb and a slug but no track_id (or something else).

Is it worth considering a refactor to make a single, central object of each type with all the required elements in order to remove duplication and minimize confusion? 

A related concern is nomenclature: do we have specific definitions, ie. a problem only refers to the set of all possible problems in the database, and an exercise only refers to a single user's copy of that problem and associated files?

**Comment by kytrinyx** [comment]
> Is it worth considering a refactor to make a single, central object of each type with all the required elements in order to remove duplication and minimize confusion?

I'd rather not, since these are intended to be used in a very small, specific context. I think the right solution is to namespace each one so that it can be referred to unambiguously. E.g.:

```
module Presenters
  class Problem
    # ...
  end
end
```

> do we have specific definitions

The nomenclature has started becoming clearer, but it's still a mess. I can't even really make up my mind in my own head what it should be.

I've been using "problem" to refer to the combination of a test suite + README in a specific language... but then when I talk about it outside of the x-api, I use "exercise", because "problem" is ambiguous in normal every-day language. _The problem is that we have too many words that mean the same thing..._
