### ISSUE TITLE
I don't receive notification emails

### ISSUE THREAD

**Issue by jhannes** [exercism/exercism.io#2487]
I remember there being notification emails last year when I tried exercism first, but when I returned this year, I don't receive emails for comments any more. Is this functionality currently broken?

I am afraid I will forget about checking for comments and forget about using the site. Or that the comments I give to others will go unread.

**Comment by kytrinyx** [comment]
I removed all the email functionality. It was an unconfigurable firehose and I didn't want to pay the $80 subscription a year to support a feature that felt half-implemented. Since I didn't have time to focus on fixing it correctly I decided to remove it.

I'm going to be focusing on exercism a great deal more in the next few months, and I'm going to be focusing on two things:

* the onboarding process (in particular making the whole process more freindly and pleasant for people who are newer to programming)
* improving the conversations

The second part is huge and it's unclear exactly what will go into that. More fine-grained/well-implemented email notifications might be a part of it.

**Comment by ekse** [comment]
+1 for email notifications.

**Comment by alanbsmith** [comment]
Definitely don't want to beat a dead horse here, as you gave a very full response, @kytrinyx . 

If you _did_ have someone thinking about this issue / willing to contribute to some sort of notification system, you would consider it, or is it too far outside where you want the project to head? Or maybe that falls under the 'improving conversations' bullet you listed.

I really, really appreciate all you're doing here. :smile: It's such a useful tool! I definitely agree with the idea of 'helping conversations continue', which is sort of where all this is pointing, I think. And I'd like to help if I could.

Thanks again!

**Comment by kytrinyx** [comment]
Thanks! I'm still working on the onboarding stuff, and haven't gotten to the part about conversations yet.

I would be interested in having email notifications implemented, with a couple of caveats:

- I'd like to make sure that notifications are more targeted/fine grained than they were in the previous iteration
- I can't spend money on delivery

**Comment by kytrinyx** [comment]
Ref: https://github.com/exercism/exercism.io/issues/2711

**Comment by kytrinyx** [comment]
I'm going to close this, but I am strongly considering adding granular subscriptions and email notifications to Exercism: https://github.com/exercism/discussions/issues/91 so the feature might come back.
