### ISSUE TITLE
Deleting a submission doesn't update exercise correctly

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2524]
We need to make sure that the following fields are correct:
- `iteration_count`
- `last_activity`
- `last_activity_at`
- `last_submission_at`

**Comment by tejasbubane** [comment]
Do we have any related issues which elaborate the problem?

I was looking to fix this but the `update` code [here](https://github.com/exercism/exercism.io/blob/master/lib/exercism/use_cases/updates_user_exercise.rb#L11) seems correct. It is called from [here](https://github.com/exercism/exercism.io/blob/master/lib/exercism/use_cases/unsubmit.rb#L22).

**Comment by kytrinyx** [comment]
No, I just noticed this when messing around. I'll try to come up with reproduction steps, and if I can't we can close the issue.

**Comment by alebaffa** [comment]
Are you talking about the case when the user _unsubmit_ a problem, but the dashboard is not correctly updated (i.e. the num of iterations for that problem doesn't change or, if it was the 1st iteration, the problem doesn't disappear at all from the dashboard)?
I ask because I was about to open an issue for this. You can take the example of my last submission (Food Chain, in Go). Here below some screenshots.

I unsubmit the 1st iteration, so I was expecting it to disappear from the dashboard. 
![exercise1](https://cloud.githubusercontent.com/assets/465513/10875499/5d8cfb42-8133-11e5-9134-27e881b17909.PNG)
But it's still there, and if I click on it, I get this page:
![exercise2](https://cloud.githubusercontent.com/assets/465513/10875509/854ff72e-8133-11e5-9934-56f6a73d8bb9.PNG)
which makes not really sense to see.

**Comment by alebaffa** [comment]
Also, I just realized that, since the iteration (apparently) still counts as submitted, I can now see the solutions from the other people for that problem (so, it can be a tricky for people.. just submit/unsubmit and you can see other solutions).

**Comment by kytrinyx** [comment]
No, that's not a bug, it's intentional. I figure if someone really, really wants to work around it by submitting an empty solution and then unsubmitting, then that's fine. If people end up using that in order to be mean and snarky to people, then we'll have to find a solution to that, but I wouldn't want to take away access that was granted.

**Comment by mfrost** [comment]
Any idea on steps to reproduce? Not entirely sure what you saw originally.

**Comment by kytrinyx** [comment]
I'm not entirely sure either. Let's close this until someone has clear reproduction steps.
