### ISSUE TITLE
Inbox floods recently viewed page

### ISSUE THREAD

**Issue by sguermond** [exercism/exercism.io#2539]
There should be a distinction in the database between views from "mark as read" and actual views. I have 344 pages in my recently viewed and it's hard to find something I actually looked at.

![exercism recently viewed](https://raw.githubusercontent.com/sguermond/images/master/exercism-recently-viewed.png)

**Comment by kytrinyx** [comment]
We could have a separate table (perhaps called `watermarks`) where we have:

- user_id
- marked_at
- language
- slug

Then if someone says "mark as read" we can add an entry for the correct language/slug. If they say "mark as read" for everything in a track, then we can add a record for each of the language/slug combinations that they have access to.

This would add another join, but since we're already looking up views separately, we will go from zero to one joins. This is not the bottleneck on performance for the page, so I think this would be a decent solution.

**Comment by kytrinyx** [comment]
I'm working on this fix at the moment.

**Comment by kytrinyx** [comment]
Fixed in #3146
