### ISSUE TITLE
5-a-day should not include archived exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2561]
I should have caught this when reviewing, so sorry!

The 5-a-day feature is currently showing archived exercises, and it links to submissions that may not be the most recent iteration.

We should be selecting exercises, not submissions, which would make it fairly straight-forward to exclude exercises that have been archived.

/cc @mixolidia @sguermond

**Comment by bmulvihill** [comment]
Hey @kytrinyx I was checking out the 5 a day feature, its pretty neat!  

I noticed what you mentioned above, specifically the 5 day not bringing you to the latest iteration.
I also noticed that we are only provided exercises which have already been commented on.  Is this the desired behavior?

**Comment by sguermond** [comment]
@bmulvihill This shouldn't be happening, thanks for letting us know.

@kytrinyx working on it!

**Comment by sguermond** [comment]
So there is a small issue: we check that someone hasn't commented on an exercise by joining with the comments table. However, by joining with the comments table we de facto exclude all 0-comment exercises, and SQL does not allow conditional joins as far as I know (ie. check user id of comments if nit count > 0). @kytrinyx what are your thoughts on this?

I lean towards taking the risk that someone might get a problem they've already commented on, since in most cases we would already be giving them a problem with 0 comments.

**Comment by bmulvihill** [comment]
@sguermond I think I have a solution, by left joining on the comments table and then change the WHERE clause statement to
```sql
AND (a.user_id <> c.user_id OR c.id IS NULL)
```
This should pull in exercises with no comments. I can submit a PR if you want

**Comment by kytrinyx** [comment]
Yeah, left joins will work. They're also very, very slow. We might have to do it in a couple passes like we do in the inbox.
