### ISSUE TITLE
Rename JavaScript Test Files

### ISSUE THREAD

**Issue by AbdullahAlger** [exercism/exercism.io#2581]
I just have a suggestion to reformat the test files generated for JavaScript so that the file name is in camel case. I know that Ruby files use an underscore, but usually JavaScript uses camel case.

**Comment by kytrinyx** [comment]
I have no problem with that in theory, since each language on exercism is using its own conventions, however it's my understanding that there are no actual standards in JavaScript. All the javascript developers that I've worked with have used lowercase filenames, and most have used hyphens rather than underscores as word separators, though that varied a lot more.

/cc @exercism/javascript thoughts?

**Comment by AbdullahAlger** [comment]
Sounds about right to me. Maybe using hyphens instead of underscores would be better. For a file named `one_crazy_spec.js`, perhaps `one-crazy.spec.js`, `oneCrazySpec.js`, `oneCrazy.spec.js`, or `one-crazy-spec.js`? I'd prefer the former over the latter file names suggested.

**Comment by kytrinyx** [comment]
I like `one-crazy.spec.js`.

**Comment by rchavarria** [comment]
Most people would agree to use camel case to name elements of the language: functions, variables,...

For naming JavaScript files, I also like `one-crazy.spec.js`. Specially, I like to see `spec` as part of the file extension instead of the file name, so I can find easily both tests (`one-crazy.spec.js`) and implementations (`one-crazy.js`).

**Comment by kytrinyx** [comment]
That's 3 votes in favor :) I'd say let's just go for it.

**Comment by kytrinyx** [comment]
Fixed in exercism/xjavascript#119 -- thank you @AbdullahAlger!
