### ISSUE TITLE
Where to start?

### ISSUE THREAD

**Issue by Spikeyblur** [exercism/exercism.io#2584]
I'm pretty new to programming, and I've been reading a few books on C# as that's what I'd like to learn. I have been planning on using exercism for a long time now and only just got around to it and started the csharp exercise. 
But I feel absolutely lost, I don't know how to write a program that calculates leap years! 
So should I head back to the books and read up more, or should I learn by doing? The only way I'm going to be able to get this program to work is if I look online at examples, and that feels like cheating.
What should I do? And is this program supposed to be runnable, or do I leave it as is?

Honestly I'm just really lost, and any help is super appreciated.

**Comment by kytrinyx** [comment]
Hi @Spikeyblur -- I'm so sorry this is confusing! We're actually in the middle of figuring out how to make this less confusing/intimidating if you're new to programming (but it's going to take a while to get everything sorted out).

The exercise should be runnable in the sense that you should be able to run the test suite, and it should give you a failure, and that failure should tell you what the next step is. Usually this is in form of an error message, and error messages are sometimes very cryptic, so there are a few hurdles.

Are you able to run the test suite?

**Comment by Spikeyblur** [comment]
Thanks for replying @kytrinyx !
No, unfortunately not. Actually, I'm having some difficulty understanding what you mean by 'test suite',do you mean (and I know this really shows absolutely how entirely inept I am) Starting the program/running it using Ctrl+f5? Because it only says 'Attach'. I have a few guesses as to what this implies, but I'm essentially in the dark.
I just really feel lost, but I guess that's expected when diving headfirst into new territory!

**Comment by kytrinyx** [comment]
I've never written an C#--so I don't know how to help with specifics, but I can certainly tell you conceptually what I'm talking about.

When you said `exercism fetch`, you should have gotten two files:

```
csharp/
└── leap
    ├── LeapTest.cs
    └── README.md
```

The `LeapTest.cs` file is what I'm calling a "test suite". The idea is that this test suite contains code that will pull your code in and run it, and it will check if your code is doing the right thing or not.

I'm actually not sure how to run tests in C#--I generally work in languages that don't use IDEs, but I think C# would use VisualStudio, so there's probably some short cut or keystroke or something that would trigger the test suite to run.

There's a help page here: http://help.exercism.io/getting-started-with-csharp.html and if you're getting stuck working through that, then we should be able to improve the page once we figure out how/where you got stuck.

If you open up the `LeapTest.cs` file, you'll see that all but the first test has an `[ignore]` declaration. That is so that when the tests get executed, it will only worry about the very first test. That gives you less to think about.

The tests are implemented so that each test builds on the previous one. It breaks things down so that you don't have to think about the whole problem all at once.

The underlying philosophy of exercism is that you should be able to solve the problem in tiny steps, and each step is checked by an automated test. It gives you little goals to work towards: just get the current test working. Once one test is passing, then you would delete the `[ignore]` declaration above the next test, and run the tests again.
 
@jwood803 - do you do C#, right? Do you have anything to add to this?

**Comment by Spikeyblur** [comment]
Oh! So are you saying that I'm not supposed to write an entire program that calculates leap years, but rather make the code that's already there work?
If so, that actually makes a lot more sense...
So do I simply fix it, debug it to see if it runs, delete [ignore] and work on the next one until completion?
I initially thought I was to make a program to calculate leap years from scratch, so that's where I was confused.

**Comment by kytrinyx** [comment]
The tests will lead you to write a program that calculates leap years from scratch. Once you run the test suite, the first complaint it will make (probably) is that it's trying to reference something called Leap or Year or something that doesn't exist yet... and then you'll have to create that thing. (Again, I don't know C#, so I'm not sure what the error will look like, but other languages tend to complain about things like that).

**Comment by Spikeyblur** [comment]
Alright, well thanks for the help! I'm sure I'll get it... Eventually... hopefully...
Although I have one suggestion since you said you're in the process of making it more beginner friendly, maybe start with an even more introductory program? Probably not 'Hello World' type simple, but something that familiarizes you with syntax or such? I dunno, maybe I need to solidify my foundation in programming before attempting this.
Again, thank you for the help!

**Comment by kytrinyx** [comment]
Actually, we're adding "hello world" to most of the tracks, we just haven't gotten to C# yet.

**Comment by Spikeyblur** [comment]
Oops, well looks like you're already on top of the ball,
Thanks for all your hard work!

**Comment by jwood803** [comment]
Sorry for the delay. @Spikeyblur, since this issue is closed and if you're still having trouble or just any questions, just join us on the [Gitter chat](https://gitter.im/exercism/support).
