### ISSUE TITLE
Authenticated user information is being transported over HTTP

### ISSUE THREAD

**Issue by esabelhaus** [exercism/exercism.io#2589]
This is not necessarily bad, but it is somewhat bad practice in terms of authentication.

SSL certs are pretty cheap:
https://www.ssls.com/ssl-certificates/comodo-positivessl

And sometime soon, free :smile::
https://letsencrypt.org/certificates/

Or, if you're running things in Heroku:
https://elements.heroku.com/addons/ssl

The reason I bring this up, is the install-cli and account views both transport your API key in the open over HTTP. This makes it easy for a man in the middle to snag said key and use it to impersonate as the intended recipient.

If you're not running on Heroku, this can be very easily implemented using Nginx as a reverse proxy to a localhost port, and enabling nginx to perform the SSL connection securely, while still quickly serving up the content.

The config for nginx would look like this:

```
upstream exercism {
    server localhost:3000;
}

server {
        listen      80;
        server_name exercism.io;
        rewrite     ^   https://$server_name$request_uri? permanent;
}

# Supports WWW A-records
server {
        listen      80;
        server_name www.exercism.io;
        rewrite     ^   https://$server_name$request_uri? permanent;
}

server {
    listen          443 ssl;
    server_name         exercism.io;
    keepalive_timeout   70; 

    location / {
        proxy_pass http://exercism;
    }

    ssl_certificate     /etc/ssl/COMODO_Bundle.crt;
    ssl_certificate_key /etc/ssl/my_key_file.key;
    ssl_protocols           TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers             HIGH:!aNULL:!MD5;
}

# Supports WWW A-records
server {
    listen          443 ssl;
    server_name     www.exercism.io;
    keepalive_timeout   70; 

        location / {
                proxy_pass http://exercism;
        }

    ssl_certificate     /etc/ssl/COMODO_Bundle.crt;
    ssl_certificate_key /etc/ssl/my_key_file.key;
    ssl_protocols           TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers             HIGH:!aNULL:!MD5;
}
```

If you don't use a WWW A-record for DNS, you can remove the www server configs

The only catch I would see here, is if your binary for the command line doesn't easily support SSL. Any how, just thought I would lend my two cents :smile: 

Please let me know if you'd like any help with this

**Comment by kytrinyx** [comment]
Thanks!

Yeah, @canweriotnow and I have briefly chatted about fixing this.

There's no reason why the CLI couldn't use HTTPS, it uses the Go net/http package which supports both.

The API was never intended to be particularly secure, just a shorthand for identifying people when fetching/submitting code. The functionality has expanded a bit since, and we really should take care of it.

**Comment by e-sabelhaus** [comment]
I've been meaning to get my feet wet with Go. I could take a swing at it if you're accepting PRs

**Comment by kytrinyx** [comment]
Yeah, sure accept PRs on the all parts of the project. https://github.com/exercism/cli

I was going to wait until we have the new version of the API out, since I really don't see this as a security risk: There's no personal information. We don't store any passwords, and the only actions you can use the API key for is to fetch code or submit solutions.

It seems like unlikely that someone would bother impersonating someone else to submit really embarrassing code, though the internet is full of very strange things, so I suppose it could happen.

The HTTP -> HTTPS change is just that one character (in the CLI), however if we make the change we should do some prep work with @canweriotnow to reorganize the endpoints to match what the new API is going to have.

We should also support the old endpoints with a deprecation warning asking people to upgrade to the new client.

We're hosting this on heroku, but we don't have to do the $240/year option, I can buy an SSL cert from DNSimple, which I think is $20 (well, $40, since we have two APIs, but if we clean up the endpoints, we could easily make all of the CLI calls go to a single domain).

@canweriotnow do you have any thoughts about this (priority, timeline, implementation details)?

**Comment by johnpaulashenfelter** [comment]
@kytrinyx You'll still need to get a Heroku SSL endpoint ($20/m) to point your DNSimple cert at -- you need the cert and the endpoint to resolve it.

**Comment by kytrinyx** [comment]
In that case, I don't think this is worth it right now. I'm willing to reconsider, but I think that we have bigger, more interesting problems to solve.

**Comment by e-sabelhaus** [comment]
If you're not tied down to Heroku, you could probably stand up the entire site using a Digitalocean droplet for $20-40 a month depending on how much throughput you require. And since you're already going through dnsimple, it would be easy to point it to the name servers at Digitalocean. I do this myself, and it is a breeze. 

For consideration https://www.digitalocean.com/community/tutorials/deploying-a-rails-app-on-ubuntu-14-04-with-capistrano-nginx-and-puma :smile:

**Comment by kytrinyx** [comment]
I'm not tied to Heroku, and exercism has sponsorship from Rackspace, so if I had the spare cycles to move the various pieces to Rackspace then this would be much, much cheaper.

The problem is not getting it up and running (I know how to do that, and there are plenty of great tutorials for the bits and pieces that I might not be familiar with). The problem is _keeping_ it running. Monitoring. Logs. I've worked on enough large systems that I know how often things go wrong. I am not an ops person, nor do I play one on TV. When things go wrong, I'm not the person you want to call to fix it, because I don't have the several years of experience required to be able to troubleshoot efficiently. Keyword: efficiently.

For what it's worth, I already have parts of exercism running on Rackspace, but they're not critical pieces, and if they go down for an hour or a day, it's not going to cause any big problems.

It's not particularly relevant to this discussion, but exercism is not Rails. There are two node apps, four or five sinatra apps, two or three static sites, and the Go daemon.

**Comment by e-sabelhaus** [comment]
I could help you put together monitoring through Nagios. Using the NRPE plugin, nagios can remotely determine whether a process is running, monitor the number of processes running, check disk space, and basically anything else you could think of. Best of all, it's open source!

Also, if they're sinatra / node, you could use Passenger with Nginx to handle them. It automatically scales up and down based off incoming requests. And Nginx is stupid fast at handling static content.

Full disclosure, I work in a DevOps environment, and maintain my teams monitoring :smile:. Outside of that, I love the open source community, and think what you have put together is awesome!

**Comment by kytrinyx** [comment]
That would be fabulous. I'm familiar with all the pieces, we used Nagios at the job I worked at from 2010 to 2013, and I've already got nginx running on the rackspace servers.

The bit that still has me worried, however, is that if Nagios warns me that something is wrong, I wouldn't be great at troubleshooting what went wrong, and something that an experienced ops person could solve in minutes might take me hours to figure out... meanwhile, exercism would be down.

@johnpaulashenfelter Would you mind helping think through the trade-offs here?

**Comment by andreagrandi** [comment]
@kytrinyx hi Katrina, are you still hosting the website on Heroku? Can you please give us a few more details about the technologies involved? It looks like it's a RoR application, right?
In terms of "devops" stuff we could do, we could prepare an Ansible script to deploy everything, so we will be able to easily re-deploy everything in the future if we should decide to change hosting.

**Comment by kytrinyx** [comment]
> are you still hosting the website on Heroku

Yepp, we sure are. And they just gave Exercism a bunch of platform credits so that I can upgrade some of the resources that I'm using there, so we'll be staying there for the foreseeable future.

> It looks like it's a RoR application, right?

It's Sinatra—so more or less the same deal. Ruby + Rack anyway. We also use Redis and PostgreSQL.

We've also got a Go daemon running on a Rackspace server with a small upstart script. I don't know devops so I wrote a minimal deploy script in bash for that: https://github.com/exercism/rikki/blob/master/bin/deploy

**Comment by andreagrandi** [comment]
@kytrinyx hi, then it's even more simple, let's not over complicate this (ignore my "devops" suggestion). I'm happy to hear that Heroku decided to support the project! Surely the easiest solution is to activate the SSL option through their panel. I'm not sure if they also provide the certificate or if we need to get it separately.

**Comment by mhelmetag** [comment]
@andreagrandi , Heroku doesn't provide certs. It would probably be easiest to get them through Let's Encrypt. However, Let's Encrypt certs expire every 90 days and there isn't an easy way to renew the certs (at least not through Heroku).

Heroku now offers free SSL (found [here](https://devcenter.heroku.com/articles/ssl-beta)).

So the steps are:
* Run certbot to get the shared secret that would have to display on a specific exercism route (to prove ownership)
* Merge the certbot route to exercism and get that deployed
* Get the new exercism certs and add ssl through the heroku cli
* Renew them every 90 days (or preferably setup something to do that)

There's also a slightly easier way to do all of these through CloudFlare (nice tutorial [here](https://robots.thoughtbot.com/set-up-cloudflare-free-ssl-on-heroku)). No certs and renewals needed.

Either way would get us the desired results of https.

**Comment by andreagrandi** [comment]
```
Heroku SSL is included for free on any app that uses paid dynos: Hobby, Standard-1X, Standard-2X, Professional-M and Professional-L.
```

if you are using paid dynos, yes, the SSL feature will be free. I don't think it's possible (or easily doable) to use LetsEncrypt with Heroku, because you still have to manually upload the certificate (unless they provide a proper API, then it would be possible but you still need to upload something on the website and make it available for verification), but there is another provider offering free SSL certificates and it's called StartSSL. I used them for a couple of years. Their renew procedure is not very user friendly (you need to login using a browser certificate etc....) but it's free.

**Comment by kytrinyx** [comment]
I'll go through the https://devcenter.heroku.com/articles/ssl-beta documentation and see if I can get this running. It may take a few days to get to it.

**Comment by kytrinyx** [comment]
My estimate was a few days, but it's already been over a month. And the next month is looking like it will be equally hectic :(

@olivierlacan you said you got something like this working with an auto-renewable certificate. What was that about?

**Comment by mhelmetag** [comment]
I know I don't like buildpacks but... setting up caddy could be a good idea?

Basically it's a go sever that automatically fetches and configures your handled routes for https with let's encrypt certs.

I can look into getting a demo going tonight.

https://elements.heroku.com/buildpacks/fishman/buildpack-caddy

**Comment by kytrinyx** [comment]
Thanks @mhelmetag @nilbot. Caddy looks like a promising option.

**Comment by mhelmetag** [comment]
Definitely! I'd love to try it out on my own heroku instance but I'm having problems getting my database set up on heroku... so... there's that haha.

**Comment by kytrinyx** [comment]
@mhelmetag I've successfully managed to set up a database on heroku (barely, but let's not talk about my lack of ops skills right now). Holler if you want to spend a few minutes troubleshooting together.

**Comment by olivierlacan** [comment]
See https://github.com/pixielabs/letsencrypt-rails-heroku, that's what I use for several projects hosted on Heroku.

**Comment by kytrinyx** [comment]
Thanks @olivierlacan!

**Comment by mhelmetag** [comment]
Awesome!

I'm going to try this out with the code changes mentioned in one of the PRs that make the code framework agnostic (so it'll work with sinatra). Hopefully that PR will be merged in soon.

**Comment by kytrinyx** [comment]
FYI: I started setting up certs for heroku, and ran into a snag with the DNS. It might not actually be a snag, but I don't have the headspace right now to figure it out. Essentially the Heroku guide said "now point to the ssl version of everything", except my DNS is pointing to Fastly, and Fastly proxies to Heroku.

**Comment by andreagrandi** [comment]
I can still help, maybe using a solution similar to the one I'm using on my static website. Do you still need help? Cheers

**Comment by kytrinyx** [comment]
Thank you @andreagrandi!

We've solved this in v2 of Exercism which should be launching before too long. In v2 we're using HTTPS, and also the token is passed in the header rather than as a URL parameter.

I don't think we need to address it in v1, since that entire site/codebase is going away shortly.
