### ISSUE TITLE
Self-rank proficiency/years exp in a language (for others to see)

### ISSUE THREAD

**Issue by jessejanderson** [exercism/exercism.io#2594]
Knowing that I'm a bit of a newb, sometimes I'm hesitant to leave comments because I'm afraid of steering someone the wrong way.

Basically, one of my main worries when leaving nitpicks is that they will be a newbie too and suddenly think the thing I said is gold because they have no way of knowing if I've been writing Ruby for 15 years or 2 weeks.

My other worry is that they are actually really experienced and I'm the idiot trying to tell the mechanic how to fix my car.

If I had some sort of icon or something next to my name that self-professed "I'm new at this" or maybe just "I've been programming for less than 2 years" or whatever, I think that would be great.

It would also help give some weight to the comments I receive - though I understand this might be a hesitation to adding a feature like this...

**Comment by kytrinyx** [comment]
I would rather this be a part of the conversation: If you're not sure that your suggestion is useful, then perhaps there's a way to ask more open ended questions that indicate that you're exploring ideas more than making suggestions.

In Go and Ruby I try to point to specific things in the code, and specific references that back up what I say about idioms. Well, more in Go than in Ruby, to be honest. There's not a whole lot of official documentation about idioms in Ruby.

I think that it's incredibly valuable to have someone come into a conversation and say: "hey, I'm new at this. I don't understand what you did on line 7" or whatever. Or "I tried doing this a different way (short description). What is the trade-off in doing it your way?"

**Comment by jessejanderson** [comment]
I guess that makes sense, I guess I could refer to style guides when I feel like my nitpick is something like "usually things are done like ___ in Ruby".

**Comment by kytrinyx** [comment]
Yeah, the best nitpicks in my experience refer to style guides, or to experience with the understanding that your experience might be different from mine. I especially like nitpicks where people explain the pain that they've experienced when they've worked with code that has the specific feature that is being discussed.

**Comment by remcopeereboom** [comment]
I think stackoverflow has some great ideas that might be useful here. First of all they have these two little boxes that give hints about the formatting of nits (i.e. that you can use markdown) and this box about _how to ask_. I think we could have something similar in exercism: _how to nit_.
@kytrinyx made this great comment in another post where she mentioned some good beginner questions:

> I would be much happier about the whole thing _[nitting without having completed the exercise]_ if we could find a way to encourage beginners to nitpick more by asking honest questions than by giving unfounded advice: I understood everything up to line 17, but I don't get how that works, can you explain it?, or sometimes I see people do X, but you do Y and it seems like it does the same thing? What's the difference between them?

Perhaps if we showed a random example question above the nit box, that would encourage people to not be afraid to ask "dumb" questions and also to encourage people to ask questions that initiate a dialogue instead of simply saying: "change this to this".

We could also consider linking to a checklist for code review? You could start the list with basic things like consistent formatting and naming and move on to more complex things like defensive programming, class design, and efficiency. I think that that might encourage novice programmers to start with the simple things (everyone can see if formatting is consistent or not). It might help lessen the fear of nitting and help people when they review code. You could make it a bit more interesting by adding **good** questions to ask at each checklist point.

**Comment by kytrinyx** [comment]
Linking to a checklist would be great. Linking to a different checklist per language would be fabulous, I think.

I think the idea of adding random example questions could work, as long as it doesn't become noise that people ignore.

**Comment by petertseng** [comment]
Seems similar to https://github.com/exercism/exercism.io/issues/2164 , maybe should merge

**Comment by kytrinyx** [comment]
Yes, agreed. I wish there were a literal merge option, but in the meanwhile... closing as duplicate. Please see the discussion in #2164.
