### ISSUE TITLE
Duplicate rikki nits

### ISSUE THREAD

**Issue by mikeyjcat** [exercism/exercism.io#2601]
I noticed that rikki posts the same nit for each version of a problem I had. While each is a valid comment, would it not be better to post them once? There are pro's and con's each way, it just felt weird to have six identical comments, and the duplicates didn't add much value.

**Comment by kytrinyx** [comment]
I'm sure the duplicates didn't add much value, but what caused you to not act on it? Did you disagree? That's one thing. Did you not understand what rikki meant? That's another. Did you understand what rikki- was talking about but not know how to go about doing it? That's a third. Did you just not think it was important? That's different again.

I would rather fix these issues than just stop showing duplicates.

**Comment by mikeyjcat** [comment]
Hmm, this specific scenario unfolded as follows:
- I created and submitted the solution before rikki was born.
- I submitted a couple of solution versions (all with the same format issue)
- rikki was born, and created nits for each of the problem versions.

Rikki's nit was perfect, issue valid, I know how to fix, I agree should be fixed.

Possibly rikki should, if looking at a problem for the first time, only nitpick on the latest version?

**Comment by kytrinyx** [comment]
Yeah, rikki- should only be given the most recent version of a problem if we feed it historical data.

This was quite a long time ago, right? If it wasn't then we might have a different problem.

**Comment by jessejanderson** [comment]
I just started using exercism, and had this problem too.

I posted some code, made a couple iterations, and then a few days later I got 2 duplicate rikki comments on older iterations. (http://exercism.io/submissions/6ea5463f2eda430f9aac147f266cffce)

**Comment by mikeyjcat** [comment]
The rikki comments were two days ago. She commented on the first four versions of the solution.

The final two were not commented on as the issue had been resolved.

So possibly two issues:
- Multiple comments
- Comments on an issue that has subsequently been resolved in later versions of the problem.

**Comment by kytrinyx** [comment]
I have not asked rikki- to process historical data since I launched it in February. That said, Rackspace took down my server for maintenance, and that would have caused rikki-'s queue to fill up, and when it came back online rikki- would process that queue in FIFO order.

We could address this on the API end of things and only save a comment from rikki- if it's on the most recent submission for an exercise at the time that the comment is being submitted. That way, if rikki- gets a backed up queue and submits a comment for iteration 1 when iteration 2 and 3 has already been submitted, then we can simply not save the comment. If rikki- then submits the same comment for iteration 3, we'll know to save it without having to check what comments rikki- already submitted.
