### ISSUE TITLE
Code looks malformed in the GUI when it is in DOS/Windows format and contains comments

### ISSUE THREAD

**Issue by cganchev** [exercism/exercism.io#2629]
When the submitted file is in DOS/Windows format (CR/LF) there is an extra newline after each comment. The line numbers are not aligned with the code.

Example: http://exercism.io/submissions/c3c1b2b5ac294a7dad9d7cded45bc7e2

**Comment by mfrost** [comment]
Sure thing, I'll dig in.

**Comment by mfrost** [comment]
Took a look at the Rouge lexer and it seems to only care about `\n`. Guessing that running it through the Markdown library normalized this before the change. I guessed that the highlighter ignores CR/LF, and taking a look at the HTML response in vim with `:e ++ff=unix` reveals untouched `^M`s. Attached is a screenshot since newlines can be annoying to view: 

<img width="322" alt="newlines" src="https://cloud.githubusercontent.com/assets/168570/11540774/ef36fb40-98eb-11e5-93b9-0af829ddc0e2.png">

@kytrinyx think it is acceptable to normalize the new line character during display? I'm guessing we don't want to modify the user submitted data.

**Comment by kytrinyx** [comment]
Yeah, normalizing during display seems like the right thing to do. Definitely don't want to touch user-submitted data, since there's no way back afterwards if we do that.
