### ISSUE TITLE
Exercism Debug - Ruby Raindrops Exercise

### ISSUE THREAD

**Issue by McEileen** [exercism/exercism.io#2674]
I tried to submit three times from the terminal and got three different errors.  I attached descriptions of them below.

1) 2015/12/23 16:20:57 unable to submit solution - an internal server error was received.
Please file a bug report with the contents of 'exercism debug' at: https://github.com/exercism/exercism.io/issues 

2) 2015/12/23 16:26:02 unable to submit solution - error parsing API response - invalid character '<' looking for beginning of value

3) 2015/12/23 16:35:55 unable to submit solution - error parsing API response - invalid character '<' looking for beginning of value

I'm not sure what these errors mean.  Thanks!

**Comment by n7fury** [comment]
hi, i got the same error. It seems like there is an internal error or the exercism server is down and the the server is responding with an html error page instead of the expected json. 
Here is a package capture of a request.
[execrism_pk.txt](https://github.com/exercism/exercism.io/files/71362/execrism_pk.txt)

**Comment by kytrinyx** [comment]
Sorry about that--the site was down, but it should be back up now.
