### ISSUE TITLE
dashboard notifications area doesn't show pretty language name

### ISSUE THREAD

**Issue by LegalizeAdulthood** [exercism/exercism.io#2694]
![image](https://cloud.githubusercontent.com/assets/4270863/12069734/0b8617ec-b005-11e5-8ad8-f363427df616.png)

It should say `C++` not `Cpp`.

**Comment by kytrinyx** [comment]
Ah, yes! Definitely a bug.

This should be simple to fix as each track has both a track_id (`cpp`) and a language (`C++`). If we're not using the `X::Track`, then we can get the language corresponding to a track ID using `Language.of`.

**Comment by tejasbubane** [comment]
If I am not wrong, the notifications page is `./app/views/notifications/index.erb` and `Language.of` is being used there: https://github.com/exercism/exercism.io/blob/master/app/views/notifications/index.erb#L68

the problem here is:
```
pry(main)> Language.of("Cpp")
=> "Cpp"
pry(main)> Language.of("cpp")
=> "C++"
```
A simple `downcase` would fix this. 
@kytrinyx let me know if this is correct and I will send a PR.

**Comment by tejasbubane** [comment]
Ohh this is the dashboard notifications! My bad. There we have `capitalize` instead of `Language.of`: https://github.com/exercism/exercism.io/blob/master/app/views/dashboard.erb#L72
