### ISSUE TITLE
Improve reviewer workflow

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2698]
I'd like to spend a few days improving the workflow for those who spend a lot of time giving feedback on the site.

My own workflow is to go to the inbox, filter it for "go" and "leap" and then give feedback to everyone who has submitted something since I last visited. Then I do "go" and "clock". I'm working my way up to more of these.

Sometimes, when I have time, I go and give feedback on old submissions that never got a review.

The first two improvements that come to mind are:
1. re-implement the "next submission" link so that it always takes you to the most recent unread exercise in the _<current filter>_, where _<current filter>_ is whatever you last visited on the inbox link ("Exercises" in the top menu).
2. create a filter for "everything that has not received feedback". This could mean "nobody ever gave feedback on any of the iterations", or "there are zero comments on the most recent submission".

Do you have any other thoughts off the top of your head about things that would make it easier to review solutions?

/cc @etrepum @remcopeereboom @NobbZ @ThomasZumsteg @abo64 @verdammelt @wobh @matthewmorgan @stevejb71 @TrophyNinjaShrub @alxndr @ryanplusplus

**Comment by NobbZ** [comment]
Since my own track is currently somewhat stale, I'm reviewing other tracks in my spare time, often it my flow is similar to the following:

1. Just try to pick on the five dailys.
2. If there were some that I could not pick on because I simply dislike that specific track/exercise/user or because I just gave a thumbs up, I choose a track and then an exercise by random and go through the unread items on the first and second page, sometimes a little bit more, sometimes a little bit less.

From a reviewers point of view, I'd wish some possibility to easy filter everything by track/exercise/age/comments/iterations/etc and combinations thereof. Probably even "everything in the ruby track that is half a year and uncommented but neither the beer-song nor the food-chain".

From a regular users view, I'd wish a way to get my stuff reviewed. I just archived a lot of stuff without any likes or comments, because it did not receive anything in 5 months.

**Comment by kytrinyx** [comment]
> From a reviewers point of view, I'd wish some possibility to easy filter everything [...]

Yes, I think this would be very useful.

> From a regular users view, I'd wish a way to get my stuff reviewed.

Yeah, absolutely. Once I finish the big task I'm currently working on, I'm going to look at ways of improving that.

**Comment by NobbZ** [comment]
There was a race condition while I edited my own post, therefore I'll copy paste here for better reference:

I just realized that the link to my own submission has vanished. It was essential in my workflow, to use it to open up my own code quickly and then compare both. Sometimes this even helped to polish up my own stuff.

**Comment by kytrinyx** [comment]
I moved the link down into the comments--but of course if you haven't commented yet, then that won't help. I'll put it back.

**Comment by matthewmorgan** [comment]
My two cents: it would be nice to be able to flag submissions for later review.  Sometimes I look at a submission and want to give feedback, but need some time to compose my thoughts.

**Comment by kytrinyx** [comment]
@NobbZ I've put back the link to your own solution. Deploying now.

**Comment by verdammelt** [comment]
At least once a day I check for items in my inbox (items I'm already involved in) then for new items on my track. At the moment that's all I can handle, but also luckily, it is enough to generally keep ahead of my track.

I like the idea of being able to filter by track, etc. - but perhaps more useful to me to begin with would be being able to flag items  - so I could tick items I see when I'm at work but I want to do something about when I get home.

**Comment by ThomasZumsteg** [comment]
Reviewing submissions less than a day old in a specific track is my favorite. Especially the simpler exercises. Some of the later/longer solutions are more difficult to critique. Lately I've been trying to complete the daily 5, usually unsuccessful.

Re-implementing the "most recent unread submission" sounds good. These are the most satisfying as a reviewer and submitter, it's better to interact when the ideas are fresh.

Also highlighting users I've reviewed before would be nice. Over 3~5 exercises a rapport develops.

Could notifications on similar submissions be combine? When a submitter replies they tend to upload one (or many) new iteration along with a comment. A typical inbox is

```
<submitter1> commented on <submitter@exercise>
<submitter1> uploaded a new submission to <submitter@exercise>
<reviewer2> commented on <submitter@exercise>
<submitter1> commented on <submitter@exercise>
<submitter1> uploaded a new submission to <submitter@exercise>
```

but could be

```
<submitter@exercise> has 5 notifications 
```

With an optional fold out of what notifications are.

@matthewmorgan Flagging submissions for later review would be great, right now I just leave the tab open...

Thanks for all the great work!

**Comment by kytrinyx** [comment]
Today I added activity stats for all of the tracks: http://exercism.io/stats

**Comment by verdammelt** [comment]
RE: stats page for Lisp - interesting - huge hump for the first few then drop off (OK, people starting and then not continuing) but then another hump about 5 exercises later then another flat spot. So those middle ones are just "meh"?

**Comment by kytrinyx** [comment]
Maybe! What happens if we move those middle ones to the end for a while and see if people go farther?

**Comment by verdammelt** [comment]
I looked at the chart again this morning and now wonder if it is showing two cohorts, one that started longer ago (second bump) and some that started recently (first bump). So the valley is just that some people are past those exercises and others haven't reached them yet?

Reordering the exercises could be an interesting experiment. We'd just have to change the `config.json` in the track repo and wait for it it to integrate with the rest of the system right?

**Comment by kytrinyx** [comment]
That's a good point about the cohorts. I think you could be right.
Let me add some "historical data" type charts so that we can avoid making decisions based on what happened over the holidays, which could be totally spurious.

Reordering the exercises would just be the config, and then deploying the x-api again (which I do every day-ish).

**Comment by remcopeereboom** [comment]
I am always reviewing the ruby track, so I find it a bit annoying that I have to select ruby every time when I click on the Exercises button. Perhaps we could store the last selection so that every time you login it is restored. Alternatively, why not have the dashboard show a mix of submissions from all tracks?

I try to look for submissions that never got a review so a filter for that would be nice. And I tend to go for problems that I find more interesting, so if I could sort the tracks by once I check frequently that would be nice.

It's also a bit annoying to have to go to that button in the top right of my rather wide screen. Why not make a section of "to be reviewed" on the dashboard? That would also give it some more prominence and might encourage people to nit more. Also, is it an idea to make the button open up on hover enter and close on hover enter?

> Also highlighting users I've reviewed before would be nice. Over 3~5 exercises a rapport develops.

I second that. I try to match my nits to the level of the submitter. Once you have gone over a few exercises together it becomes easier to judge that level. Also, it's rewarding to see someone take your advice and see them use that in subsequent submissions.

**Comment by kytrinyx** [comment]
Yeah, I find it annoying to have to select the track I want as well. We should definitely fix that. I'm not sure I want to have the dashboard show a mix unless people tell me that they consistently review a mix of languages.

> It's also a bit annoying to have to go to that button in the top right of my rather wide screen.

You mean the "exercises" link? Or the "five a day" feature?

**Comment by remcopeereboom** [comment]
> You mean the "exercises" link? Or the "five a day" feature?

The five a day feature. I probably should have said drop-down menu.

**Comment by kytrinyx** [comment]
Maybe :) we have several of those, as well.

I think having this in the dashboard instead of the nav would be a good idea.

**Comment by remcopeereboom** [comment]
> we have several of those, as well.

Ah... so you do... :) Clearly my workflow does not include the other ones (actually I do occasionally log out).

**Comment by kytrinyx** [comment]
This is something that we're digging into for the reboot. I'm going to close this with the label `design-research` so that we can find all the prior art when we start working on that set of questions.
