### ISSUE TITLE
Possible to have a git track?

### ISSUE THREAD

**Issue by masters3d** [exercism/exercism.io#2730]
I know git is not a language per se but I was curious if a git practice track could be even made so people could practice git on the command line. 
I am one of those people who don't really know a lot of git.

**Comment by kytrinyx** [comment]
I'd rather not, since the exercises would be very different, and I don't know what we would submit for discussion.

It would, however, be a really interesting stand-alone project.

There are a few things around already:

- https://github.com/Gazler/githug
- http://gitimmersion.com/

which are both quite good for practicing. 

For understanding git from the bottom up, the best thing I've found is

- https://www.youtube.com/watch?v=1ffBJ4sVUb4 (Git Ages 4 and Up)

I also like http://www.wei-wang.com/ExplainGitWithD3

I've also seen http://pcottle.github.io/learnGitBranching/ which seems pretty good.

**Comment by masters3d** [comment]
Sounds good. Thanks for the help.

**Comment by wobh** [comment]
Also good: http://think-like-a-git.net/

**Comment by masters3d** [comment]
Nice! Thanks.
