### ISSUE TITLE
Dashboard: "You have #{n} unsubmitted problems."

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#2737]
On my dashboard I see a list of 5 items, and a comment below that I do have 13 unsubmitted problems.

The list of 5 does tell me some of these 13. But what are the other 8?

Can we have a "see all" as we have with the active problems just above? Or am I the only one having this small problem because of my diversity in tryed tracks?

**Comment by kytrinyx** [comment]
It sounds like a bug. I don't submit code very often--I almost exclusively review code, so I haven't run into it.

**Comment by NobbZ** [comment]
I'll post a screenshot when I'm back home.

Katrina Owen <notifications@github.com> schrieb am So., 24. Jan. 2016 18:14:

**Comment by NobbZ** [comment]
![unsubmitted_problems](https://cloud.githubusercontent.com/assets/58951/12538017/32d17fea-c2ce-11e5-918e-67d3c9207293.png)

The above screenshot shows the last line of the "active problems", below that, there are 5 so far unsubmitted but fetched problems in some arbitrary (?) order. Below that there is a summary just as with the active problems, but without "see all". So I do not have a way to see all unsubmitted problems.

**Comment by kytrinyx** [comment]
Ah, OK, yes that makes sense. Thanks for clarifying.

**Comment by mhelmetag** [comment]
We could do some quick javascript to do a see more.../see less... type deal to show a shortened and full list.

Another idea would be to do it in pure css :heart_eyes: http://www.sitepoint.com/implementing-show-moreless-functionality-with-pure-css/

**Comment by kytrinyx** [comment]
Yeah, either of those would work. I don't know if anyone has a ridiculous number of these... I suspect we'll find out :)

**Comment by mhelmetag** [comment]
Agh... I'll put some thought into this over the weekend. Hopefully I have the frontend skills (or aptitude) to put something that's half decent together.

**Comment by mhelmetag** [comment]
So I have a beta version right now. Just have to figure out a way to separate each exercise (probably will just do commas).

Less:
<img width="680" alt="screen shot 2016-02-12 at 12 10 47 am" src="https://cloud.githubusercontent.com/assets/8609429/13001701/2acb1d62-d11d-11e5-831e-27481a095e26.png">

More:
<img width="654" alt="screen shot 2016-02-12 at 12 10 58 am" src="https://cloud.githubusercontent.com/assets/8609429/13001705/30c4de6a-d11d-11e5-8abd-f76ff480116a.png">

This is just using bootstrap's js collapse.

@kytrinyx and @NobbZ ,

What do you guys think?

**Comment by kytrinyx** [comment]
OK, there's been a bit of churn around the whole status/fetched/unsubmitted thing, and I spent some time taking a step back and thinking about how to solve it.

I found an approach that I liked, and then took a bigger step back and realized that all of this complexity is in the app kind of haphazardly. I've taken the slightly painful step of ripping it out (perhaps temporarily) to see what it feels like. Will people miss it? I don't know. Maybe.

I have some ideas about this, but I want to give it a few days to a few weeks to simmer.

I want to thank everyone who has worked on the features, posted the bugs, tweaked, thrashed, discussed, mused, and reflected. It's truly a pleasure to get your help figuring this out.

_cross-posted this comment in all the threads that are thrashing around with this feature, so that everyone involved knows what's going on_

:heart:
