### ISSUE TITLE
Rethinking onboarding and some design changes

### ISSUE THREAD

**Issue by ethangodt** [exercism/exercism.io#2738]
Hey y’all!

My name is Ethan and I’m a full stack Javascript developer. I’m wanting to get started on some of the front end/UX things that I’ve seen in issues here. You can see some examples of stuff I've designed at http://ethangodt.com.

So, I think one of the biggest things is that onboarding is overwhelming generally, and especially to people not yet comfortable with the command line. It seems that’s also the sentiment at #2535. I spent last night thinking of some ways that we could make this easier.

**The proposal:**

I laid out with PS what a potential homepage could be under the new scheme [here.](https://www.dropbox.com/s/r8lwho809ux3non/Exercism%20Homepage%20Redesign.png?dl=0) (I like to drop these in my browser to better see what it’d be like.) *NOTE: the logos at the header are just for the mock up. They’d be replaced with the programming language logos on the languages page.*

Regarding the homepage, I think we could trim away the blurbs in the content section and replace them with a prominent get started section. I think it’s important to continue to highlight on the homepage that Exercism is not just for newbies (my main take away from the content that is there now), but I think most of the current text could be reduced and moved to a page that is nicely designed and explains the flow of Exercism. The get started section would have two main buttons like “how it works”, and “get set up”. 

The how it works page would be sectioned something like: set up CLI, download problems, pass tests, get and share feedback. We could also have a screencast of someone going through the motions so it’s very clear how it works.

Then I think we can have another page that is about specifically setting up accounts and the CLI. I think this page could display screencasts of how to set things up. Currently there are two “how it works” type pages, and I wonder if we could reduce it down to one. The information is identical except for that the *experienced devs* page is less verbose. We could probably achieve this same thing by initially hiding all of the extra commentary for newbies, but making it visible somehow as people click learn more (tool tips and things could pop up or something). Also, I really like this Firebase [page] (https://www.firebase.com/docs/rest/quickstart.html). I think it’d be possible to do something like this with the technical steps for this set up/CLI page. We could eventually tie in all of the stuff in #2535 like OS checking.

This is sorta a big change, but I’d like to give whatever we collectively decide a whirl. I’m also interested in addressing some of the general font and spacing issues throughout the various pages on the site with some better styling guidelines.

Let me know what you all think! Would love to think through more ideas.

Ethan

**Comment by kytrinyx** [comment]
@jtigger @qianapatterson -- your eyeballs and opinions would be invaluable here!

I really, really like how much clearer and simpler the homepage suggestion is. I didn't actually notice the logos until you mentioned them specifically and I went looking for them, but it is a subtle way to emphasise the many languages.

@qianapatterson were talking about how so many of the clicks on the homepage goes to the "languages" link. It seems like there's an opportunity there to make something of that, though I'm not sure what.

> I think we could trim away the blurbs in the content section 
> [...] most of the current text could be reduced and moved

The most important thing, I think, on the current homepage, is that it speaks to three different groups of people directly, empathising with what they're currently struggling with. This is very important, because a solution (e.g. "stretch your mind with self-contained practice problems") doesn't really mean anything to me as a visitor to the site unless I know that whoever made it understands the problem I have. 

The three groups are quite distinct:

- newbie
- polyglot (experienced developer ramping up in a new language)
- artisan (experienced developer who cares about all the "craftsmanship" stuff)

I'm not tied to the specific calls to action, they're just attempts at completing the phrase "I want to..." (which is quite different between the various groups).

I think that if the homepage has _enough_ of a hook to get you to click further, then it probably wouldn't hurt us to move the blurbs to a separate page, but it's important that you end up somewhere that can funnel you into the best onboarding process for where you are and what your goals are.

> Currently there are two “how it works” type pages, and I wonder if we could reduce it down to one.

No, this is based on experience, user testing, and feedback. It's absolutely crucial to give newbies a different onboarding experience than the experienced developers. Newbies need reassurance, hand-holding, as little jargon as possible. Experienced developers just need to know the steps, and know that we're not going to do anything nefarious with the executable that you're installing on your machine.

If anything, we need to make them even more divergent.

Another important point is that feedback is _crucial_ to the process (though the feedback loop on the site is still something we're trying to figure out). The conversation is really what makes exercism different from any other site that gives you puzzles. The conversation also serves a different purpose for the three different groups.

> We could also have a screencast of someone going through the motions so it’s very clear how it works.

@genevievelesperance mentioned back in the day that she'd be willing to help out with screencasts. If she still has time, maybe we can rope her in here.

> I really like this Firebase page. I think it’d be possible to do something like this with the technical steps for this set up/CLI page.

Yeah, that sounds like it would work really well for this.

> I’m also interested in addressing some of the general font and spacing issues throughout the various pages on the site with some better styling guidelines.

Hell, yeah! The site could really use someone's design eye for that.

**Comment by kytrinyx** [comment]
Ethan, so sorry there's been no movement on this.

@jtigger @qianapatterson You both mentioned that you had thoughts about this. Would you please take a few minutes to jot down some notes here?

**Comment by genevievelesperance** [comment]
I'm happy to help with screencasts for onboarding! (For Mac users?)

**Comment by kytrinyx** [comment]
Thanks @genevievelesperance! I think it would be great to make it for both Mac and Windows (linux users tend to know enough to not get confused about this part), but even getting a good one for Mac would be a fantastic start. I'd want to wait until the redesign has settled a bit, though.

**Comment by genevievelesperance** [comment]
Sounds good. Where should I look or who can say when the redesign is near done and I can start?
I can temporarily make a mock video with the current design to show how I would go through it.

**Comment by kytrinyx** [comment]
A mock would be cool! I made a really janky one a while back (https://www.youtube.com/watch?v=TCT4eHGwfaE) and we have one for Windows as well (https://www.youtube.com/watch?v=R9Y9yuXA-qA).

When the design is ready (or ready enough) I'll either put something in this thread, or ping you directly. Not exactly sure how this design work will proceed.

**Comment by kytrinyx** [comment]
Since I have not heard anything back from @ethangodt about design I'm going to assume that he moved on to other projects, and close this issue.

@genevievelesperance if you have any ideas about what the videos would look like, would you talk about it in https://github.com/exercism/discussions/issues/18?

**Comment by ethangodt** [comment]
@kytrinyx hey, so sorry to be non-responsive on this. I'm not normally like that. A number of things have changed for me the past couple months, and I ran out of time. Feel free to ping me for a smaller task if something come up. Best of luck!

**Comment by kytrinyx** [comment]
Hi @ethangodt I know how it is! Thanks so much for letting me know.

**Comment by kytrinyx** [comment]
Ref: https://github.com/exercism/discussions/issues/34
