### ISSUE TITLE
Line comments

### ISSUE THREAD

**Issue by petertseng** [exercism/exercism.io#2743]
Sometime in the distant future I wonder if it would work out to be able to make comments on specific lines of a solution. Oftentimes in my comment I will say something like "on line 47, you could ..." whereas maybe it'd be nicer to just have the comment displayed inline.

Now obviously this would require quite a redesign of the review page, and the current way works just fine in the meantime, so I'm not too fussed about this one. But perhaps consider it when that redesign rolls around, eh?

Edit: Oh, my search powers failed me! This was mentioned briefly in #1588 . I wonder if I'll just declare this a duplicate of that. Though #1588 is a kind of larger task and this is kind of a subtask of it...

**Comment by kytrinyx** [comment]
I've wanted that since the beginning, I just haven't prioritised it yet.

**Comment by Insti** [comment]
Clarification required:
Are you talking about linking to lines in your comments (as has been implemented by #2838 / #2744?)
Or some other way of having the comments show between the code like when reviewing Github pull requests?

**Comment by petertseng** [comment]
> some other way of having the comments show between the code like when reviewing Github pull requests?

I meant this one.

**Comment by kytrinyx** [comment]
I've added the design research label to this so that we can evaluate the question within the larger context of the design reboot (see https://github.com/exercism/discussions/issues/113 for more about this).

Since this issue addresses things that are going to be difficult to implement as a quick experiment in the current prototype, I'm going to close this. If you do think that it can be implemented as a not-too jarring and not-too complicated experiment in the current website, please open a new issue about it in the discussions repository.
