### ISSUE TITLE
Highlight a specific line via #L23 or similar

### ISSUE THREAD

**Issue by petertseng** [exercism/exercism.io#2744]
Notice how in Github I am able to cause a specific line to get highlighted by doing https://github.com/exercism/exercism.io/blob/master/.travis.yml#L1

I think I might like to be able to do a similar thing in Exercism. It would provide a stopgap alternative to line comments (#2743) if I could say "on line 47" and I'd (manually at first, can think about automation later) link the "line 47" to `#L47` so that the line gets highlighted when the text is clicked.

**Comment by kytrinyx** [comment]
+1 that would be excellent! It shouldn't take much javascript to make this work.

**Comment by karloxyz** [comment]
I'd like to work on this :)

**Comment by kytrinyx** [comment]
Excellent, it's all yours.

**Comment by karloxyz** [comment]
@kytrinyx @petertseng Any insights? I'm having a hard time since the whole code snippet is displayed inside a `<pre>`. I have two choices: first, write a custom `Rouge` formatter to display it how GitHub does it (a row per line). Second, determine the line number to highlight by looking at all the whitespaces within `<pre>`.
