### ISSUE TITLE
Replace the "notify" lookups with proper subscriptions

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2771]
It would be much cleaner to implement subscriptions to solutions, rather than figuring out every time something happens who has participated or been mentioned in any of the iterations of a solution.

Also, it would be nice to be able to unsubscribe to a discussion that you don't want to hear about anymore.

**Comment by NobbZ** [comment]
That would be really nice. Also it would be nice if I not only can
subscribe to one submissions and it's successors but also to a language as
a whole or a certain exercise in a track, so that I get notified whenever
something new happens there.

Katrina Owen <notifications@github.com> schrieb am Fr., 26. Feb. 2016 19:57:

**Comment by kytrinyx** [comment]
Yeah, that's the direction I want this to go in: subscribe to entire languages, or just a single problem in a language, and also individual people (their code, or their comments).

**Comment by kytrinyx** [comment]
This has been implemented and released.
