### ISSUE TITLE
Interact with other coders more

### ISSUE THREAD

**Issue by d-mar-u** [exercism/exercism.io#2779]
I'd really like the ability to chat with people who comment on my code, to thank them, or ask them questions, other than just in the general reply function to comments.

**Comment by kytrinyx** [comment]
+100 I think that there's a lot we could do to improve the community aspect of this. I'm not sure exactly what that would look like. Some people have suggested chat rooms / forums. We do have the support chat on gitter, but that's not quite the same thing. Forums seem like overkill. I often use the comments to discuss and chat and thank people. I think that's fine.

For a while we tried introducing threaded comments, but it turned out confusing and complicated. I think that we'd need some proper user interface designers involved in thinking about how to approach this.

**Comment by d-mar-u** [comment]
Despite being of the opinion that it's vastly overused, I sort of wondered if some kind of gameification element might be useful. Maybe people could get points, much like on stackoverflow, for answers and suggestions?

**Comment by kytrinyx** [comment]
The gamification thing comes up regularly. I've written a few of my thoughts here: https://github.com/exercism/exercism.io/issues/1617

**Comment by d-mar-u** [comment]
Ah, sorry, thanks.

**Comment by kytrinyx** [comment]
@d-mar-u you opened this discussion with:

> I'd really like the ability to chat with people who comment on my code, to thank them, or ask them questions

Does it solve your issue to suggest that you can ask questions and thank people in the comments on the site?

**Comment by d-mar-u** [comment]
Yes! That's great.
