### ISSUE TITLE
Offer and Receive feedback & Featured solutions or users

### ISSUE THREAD

**Issue by iacobson** [exercism/exercism.io#2803]
I would have a few suggestions related to the code review, and featured solutions:
- would it be possible to add a feature where users are encouraged to review other people's code before moving on to the next exercise:
  - either as a requirement: eg: review other 2 solutions before proceeding to next exercise
  - or as some kind of ranking/points
- as a beginner in Elixir I feel the need at the end of the exercise to review a featured solution, something that I know complies with the language's best practices. (I think this may be valuable for all beginners, no matter the language)
  - even though I browse other solutions, and I can find some which I consider better than mine, it would be still good to know what a clean implementation of the solution lookslike
  - this can be achieved in more ways:
    - either the person that submits the exercise is posting also a solution
    - there can be some persons that contributed and are very experienced with specific languages which can have featured profiles to search for a good solution
    - or add a voting system, and the solution with most votes to be at the top
  - this doesn't mean that the featured solution is the best solution and everybody should implement it. It should be just some kind of guideline, with very clean code, respecting the language standards. So I do not think it will limit people's creativity

Thank you.

**Comment by kytrinyx** [comment]
This is one of the most important questions at the moment, and I've spent a huge amount of time thinking about it over the past year.

> review other 2 solutions before proceeding to next exercise

I do not wish to introduce any features that are likely to cause people to give unhelpful feedback. Making it a requirement will very likely mean that people do as little as possible, just to unlock the next exercise.

> as some kind of ranking/points

Gamification, ranking, and points comes up a lot. I have pretty strong feelings about this. Would you read through the discussion here https://github.com/exercism/exercism.io/issues/1617 and perhaps in the related issues, and see if that answers your question?

I think that the real reason that people aren't providing feedback is that people are intimidated. They're scared for any number of reasons: "I don't know enough", "I'll say something stupid", "I don't know what to say", "Who am I to provide feedback to someone who has been writing code for so much longer than I have", etc.

I think that this can be addressed, but probably not through points. I am currently doing an experiment where I am mentoring a handful of people specifically on how to provide feedback on the first exercise in the Go track. So far, this has been very encouraging, and I think that the result of this will be to start developing "feedback guides" for the different languages and tracks.

Something which most people aren't aware of, is that providing feedback is one of the most powerful ways of actually making your own code better. But people won't believe that until they actually experience it, so the challenge seems to be to figure out how to have people do just enough to actually discover this for themselves.

> as a beginner in Elixir I feel the need at the end of the exercise to review a featured solution

Yeah, I've been thinking a lot about this lately as well. I think that each exercise often has several really good approaches, and I think that it would be great to have a feature where we show different featured solutions with a discussion about it.

Like you say, we shouldn't limit people's creativity. I think that this should be a separate feature, not based on voting on people's solutions on the site, because so many people submit similar solutions, and it would be kind of arbitrary whose solution ends up being featured. But it would be possible to use solutions on the site to come up with the different approaches to show. For example, based on reading several hundred solutions to 'leap' in the Go track, I have four or five approaches/solutions that I think could be featured.

/cc @roseaboveit This is a really interesting discussion, and it comes up a lot. I wonder if we should put something in the discussions repository about these topics (one for "how to encourage people to do more code review" where I can summarize all of the various things about gamification and related topics, and one for "featured solutions"). What do you think?

**Comment by iacobson** [comment]
@kytrinyx thanks so much. Really detailed and helpful answer. You are so right about the reasons people avoid to provide feedback (including myself :) ). So I will have that in mind next time.
Personally I think that once you pass an initial barrier, and initiated some kind of communication, people become more open, and willing to share. 

Regarding the featured solutions, your idea with some good approaches for each exercise would be really great. But I think it would require a huge amount of work to review hundreds of solutions and extract a few main approaches.

**Comment by kytrinyx** [comment]
> But I think it would require a huge amount of work to review hundreds of solutions and extract a few main approaches.

Yes this is true. We probably need a mix of approaches to make this possible--perhaps first we could nominate existing solutions, and then eventually someone could create featured solutions based on what is there.

**Comment by petertseng** [comment]
re: featured solutions

I had half a mind to say "hey why don't track maintainers take on this task?", because we already provide example solutions for each exercise (used in CI, makes sure our test cases are correct). A few questions that would have to be answered before that can be possible:

* Currently [our docs](https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#reference-solution) say that the example solution doesn't need to be particularly great code, so that would have to change. That in itself is easy, but...
* there are probably a lot of existing examples in tracks that may not be the most suited for being a featured solution, whether because of the above, or some other reason
* How to deal with the case where we want multiple featured solutions, if we use this scheme?
    * Probably all of them should be tested against CI as well, right? And some tracks will have to be extra careful of that, for example go which builds everything in the directory, so multiple solutions in the same directory will cause conflicting definitions so fail to build.
    * More maintenance work required for track maintainers, will have to be mindful of that.

**Comment by kytrinyx** [comment]
> "hey why don't track maintainers take on this task?"

Yeah, I've had that thought, but I also don't want to overburden track maintainers (which would make it harder to find new ones and harder to keep existing ones).

I'd rather not use the example solution, mainly because I would like to see multiple featured solutions as the rule rather than the exception, since I'd really like to emphasise the idea that there are multiple good approaches. I'm sure a fair number of the existing example solutions would be close enough to good to be usable as one of the featured solutions.

I think you're right that we'd want to run the featured solutions against CI, so we'd have to think about how to do that. Putting them in the xlanguage repositories would probably make it more likely that we are able to test them properly, though there are certainly other possible approaches (we only need to test them when we change a test suite, so maybe we could have a step where we download them via the API, if they're stored in the database like other solutions).

**Comment by jkrmr** [comment]
> Something which most people aren't aware of, is that providing feedback is one of the most powerful ways of actually making your own code better. But people won't believe that until they actually experience it, so the challenge seems to be to figure out how to have people do just enough to actually discover this for themselves.

I'm sure that's true in plenty of cases—almost certainly in enough of them that tackling that problem is an interesting and worthy endeavor, but my hunch is that there are more immediate (and more simply solved) obstacles to engaged participation on exercism.io. 

To illustrate with my typical workflow, here's what I see immediately after I've submitted an exercise:

![submitted](https://cloud.githubusercontent.com/assets/4433943/14938067/bcece1b0-0ee6-11e6-9bfd-7721ae3cb319.jpg)

Cool. Since I'm in iTerm, I just cmd-click on that url, and I'm taken to my solution:

![solution](https://cloud.githubusercontent.com/assets/4433943/14938073/d7ea0100-0ee6-11e6-882c-b7319fd0ab89.jpg)

I see:

1. A form to comment on my own solution (I used to do that, thinking I was providing context and/or starting a conversation -- silly. Anyway, talking to yourself gets boring after a while.)
1. Links to a readme and test suite, and to unsubscribe from the conversation
1. A few other buttons (to expand the code viewer, copy my code, tweet something, apparently) that might be useful but I've never used 

I don't see:

*Anything* about reviewing another solution -- no copy suggesting I do so (let alone chip away at my intrinsic motivation by requiring me to do so), no UI elements I can use to take me to a solution to review....

Even if I were one of these unicorns whose intrinsic motivation was as pure as the driven snow....where do I go to see other people's solutions? 

Looking....

Oh! `Exercises` seems promising. So I click on that, and etc (the UI for that page has been discussed elsewhere). NB: This is actually the first time I've ever clicked on "Exercises" 😬 oops

Just to throw out a couple of other possible remedies, it might be helpful to <s>require</s> invite / suggest / welcome users to review other solutions by

* At the command line, providing urls of a few other recently submitted solutions for the same exercise
* Instead of displaying the "leaderboard" (i.e., activity feed) behind the "Exercises" link, display one specific to the current exercise next to the user's submission (example: vimgolf.com)

I don't claim that'll make all the engagement woes go away, of course, but I also sense a risk in letting the perfect be the enemy of the good.

**Comment by kytrinyx** [comment]
> A form to comment on my own solution (I used to do that, thinking I was providing context and/or starting a conversation -- silly.)

I don't find that silly, to be honest. When I review solutions, I find it very useful to hear what people are thinking.

You can also add a comment automatically when you submit by passing the `--comment` flag.

Since I rarely submit exercises, I don't intrinsically understand how the UX of the site hampers or hinders the behavior that I hope to encourage. It's very, very helpful to see other people's workflow. These are good suggestions.

> Instead of displaying the "leaderboard" (i.e., activity feed) behind the "Exercises" link, display one specific to the current exercise next to the user's submission

We don't have a leaderboard, the activity feed is about what happened recently, not who is better than anyone else or who has done the most. I'm trying very hard to avoid any sort of competition.

We had a "5 a day" feature where we showed you five links to things to review. It was very expensive, and ended up taking the site down. I still want to rework it and bring it back in a less expensive form, but I do not have the resources for that.

We also used to have a thing on the dashboard that suggested one specific (random-ish) exercise for you to review. That didn't appear to work at all, so I removed it.

I think one of the best things right now would be to make a very visible link on the submission page that links to the activity stream for that exercise. This would be useful whether you're looking at your own code or someone else's. "see other implementations of Clock in Go" for example.

For the CLI I wonder if we could show the link to the relevant activity stream rather than the link to your own exercise.

**Comment by NobbZ** [comment]
There also was some review other submissions from any exercise once... It
hasn't worked well though and I was often directed to submissions I already
liked or reviewed. IIRC it was labeled 'next submission'.

Katrina Owen <notifications@github.com> schrieb am So., 1. Mai 2016, 00:18:

**Comment by kytrinyx** [comment]
Yeah, I removed the "next submission" for that reason--it really wasn't clear what "next" meant.

**Comment by jkrmr** [comment]
> You can also add a comment automatically when you submit by passing the --comment flag.

Oh snap. That's awesome, thanks for the tip!

>  I'm trying very hard to avoid any sort of competition.

Thanks for that. I'm not a huge fan of that approach on other sites. I'm reminded of the grading scheme for a [notoriously difficult intro physics course](https://isites.harvard.edu/fs/docs/icb.topic1288058.files/16info.html)—a "reverse curve" that incentivizes collaboration. The failure mode for drawing inspiration from that would be a vulgar sort of gamification, of course, but I wonder...

> I think one of the best things right now would be to make a very visible link on the submission page that links to the activity stream for that exercise. This would be useful whether you're looking at your own code or someone else's. "see other implementations of Clock in Go" for example.

I'm 👍 on that. Maybe above the "unsubscribe from this conversation" link?

> For the CLI I wonder if we could show the link to the relevant activity stream rather than the link to your own exercise.

That'd be great. Maybe a filter for "my solutions" on the activity stream so that one's own solutions are still relatively easy to get to?

It'd also be cool to take note of how much commenting is happening before and after any changes, in order to make sure the impact is positive. (Or A/B test them.)

**Comment by jkrmr** [comment]
I just noticed that once a solution is archived, links to another solution and the activity feed are displayed: 

![screen shot 2016-04-30 at 11 37 49 pm](https://cloud.githubusercontent.com/assets/4433943/14939966/018fc198-0f2d-11e6-9d58-8a29d9f71f38.jpg)

**Comment by kytrinyx** [comment]
> The failure mode for drawing inspiration from that would be a vulgar sort of gamification, of course, but I wonder if there's any incentivizing of collaboration that wouldn't be step too far in that direction.

That sounds interesting. I'm not utterly opposed to gamification in principle, I'm just very, very wary of it, because it can go so badly wrong.

> For example, would it be helpful to reviewers to see that their feedback has been helpful?

Yeah, this is something that has come up and I'm tentatively optimistic about it. If it's not used to rank people at all, then it could be really helpful to have that sort of thing. I don't know what it would look like. Label-votes, perhaps, like on the TED website?

> Would featuring, in some place of prominence, helpful bits of feedback in addition to interesting solutions end up being gamed?

I think that we could probably find a way to do that without it being gamed so long as it doesn't feel like you can do specific things to get it featured.

> I'm 👍 on that. Maybe above the "unsubscribe from this conversation" link?

Yepp, that sounds like a good place to start.

> Maybe a filter for "my solutions" on the activity stream so that one's own solutions are still relatively easy to get to?

Yeah, that would be really nice! Above the different language tracks in the left-hand menu we could have "mine". That shouldn't be hard to implement at all, and it would fit with the existing UX. (In case you hadn't noticed, I struggle with UX a great deal).

Changing the link for the CLI would also be an easy fix.

> It'd also be cool to take note of how much commenting is happening before and after any changes, in order to make sure the impact is positive.

Yeah, definitely. We have all the data, it's a matter of pulling out the right details. I'm not sure we have big enough usage numbers per day/week to do A/B tests.

**Comment by kytrinyx** [comment]
Side note: This conversation has been really interesting and useful. I mentioned it in today's "Behind the Scenes" newsletter: http://tinyletter.com/exercism/letters/exercism-it-s-about-the-conversations

**Comment by jkrmr** [comment]
Thanks for the issues! 😃  I'll get started on one asap. I'm so glad the feedback was useful. 
I didn't know there was a newsletter, btw—that's brilliant ✨

**Comment by kytrinyx** [comment]
Seriously thanks for the suggestions—it's so helpful. The newsletter is a pretty new thing. For the longest time people told me I should have one and I was like "what the hell would I write about?". Then someone suggested this approach... it's tremendous fun.

**Comment by martinsvalin** [comment]
A suggestion related to featured solution: maybe don't feature a _solution_, instead feature a conversation.

I think this would probably often happen around good (or much improved) solutions. And really, I'm more interested in showcasing good code review examples than good code. For a beginner audience looking for an idiomatic solution, I'm sure the discussion would provide more context. 

This angle could also help in identifying candidates, since you can search for submissions with some threshold number of comments, participants etc. then review and mark them. One could also imagine a crowd sourced version where people can nominate a conversation.

**Comment by kytrinyx** [comment]
@martinsvalin I love this idea. I think this could actually be a valuable thing separate from featured solutions, to explore good conversations, good code reviews, etc.

I've also been thinking about whether or not I can use machine learning to identify in some fuzzy way solutions that are similar to each other. Then this can be used as the basis of exploration: which conversations exist about solutions that are similar to yours?

**Comment by martinsvalin** [comment]
I'm thinking a bit about what incentives a "Featured conversations" thing would introduce.

The obvious good one: you can "win the prize" of being featured by giving good comments. I'd certainly be proud to have participated in a featured conversation. And I'd be proud to have a submission of mine have conversation thread that becomes featured. But the glory is shared with others. I feel that is important. There is no individual "winner". No one-sided monologue would ever be featured. So care should be taken to be very clear that it is the _conversation_ that is featured, not the submission.

There's a (small) risk people will jump on the bandwagon after the fact, attracting less exemplary comments once it is made more visible. The boring solution would be to lock the thread. I'd rather have a "system comment" placed in the conversation thread that marks (and celebrates) that this conversation is now featured. Then further commenters can't pretend their input contributed to it being featured.

Anyway, I think this could address both the concern beginners have of finding good, idiomatic solutions (a good conversation will point out what is idiomatic if the solution itself doesn't). And it also teaches people what good, valuable feedback looks like.

@kytrinyx - If one were to explore this idea, I think a reasonable starting point would be to run some queries on the comments. Try to produce a list of likely candidates, put them in shared spreadsheet, and start going through the list, taking notes on what the conversation is like, and maybe also give a soft rating 1-5 :star:. Anyone can help out working through the spreadsheet, but you'd need db access to run the queries.

**Comment by jkrmr** [comment]
> A suggestion related to featured solution: maybe don't feature a solution, instead feature a conversation.
> more interested in showcasing good code review examples

I think this would be really beneficial—good examples have huge pedagogical value. I'd love to see examples of well-delivered and well-received feedback (or, just as well, poorly delivered feedback received well), and examples of the different modes of code review @kytrinyx mentioned (e.g., soliciting more context about a solution).

It's hard for me to reason about what constitutes an extrinsic or intrinsic motivator, or to predict what will trigger one or the other*, but I think that in general exemplars signal virtue and, in those who recognize it as such, also incentivize it (in an intrinsically motivated way).

*because of heterogeneity among the target population, because I imagine motivators can shift from intrinsic to extrinsic or vice versa, etc...

**Comment by kytrinyx** [comment]
> I think that in general exemplars signal virtue and, in those who recognize it as such, also incentivize it (in an intrinsically motivated way)

I think so, too.

> poorly delivered feedback received well

I've thought about whether there are ways of anonymizing things in some contexts, for example by choosing completely random usernames for authors of code and participants in a conversation (transparently, of course, not actually pretending they are real).

I wonder if whether or not this could be a way to surface content without potentially embarrassing or shaming people.

**Comment by iacobson** [comment]
Just a quick idea about the FEATURED part of the discussion. 

Before deciding anything that would require implementation of new features, maybe a simple temporary solution can help:
A simple order_by at the top of the solutions, which will allow:
- order by latest submission
- order by last commented
- order by most commented
- and (maybe most important) - order by most likes - which will act as a kind of featured

What I try to do after finishing an exercise is to find some other that I think is better and cleaner (but not complicated), take ideas from there and resubmit my exercise. Also I leave a comment to the user and "like" his solution.

**Comment by LegalizeAdulthood** [comment]
Pasting in some thoughts from an email thread with Katrina...

- As a track implementor, I had posted all my solutions to the exercises under my account, so that there would always be at least *one* solution to review.  Maybe we can implement this more formally as an "example" solution.  We might want to avoiding the word "reference" as that might make it feel to special.  My reference solutions to exercises have improved as a result of having them posted.
- It would be nice to have a side-by-side view of my solution and someone else's.  Not a diff, just side-by-side so I can see them both on a single screen.

**Comment by kytrinyx** [comment]
> and (maybe most important) - order by most likes - which will act as a kind of featured

I don't want likes to turn into something that smells of gamification. At the moment likes is just a bit of feedback to the author: someone saw your solution and thought it looked good. A lot of other people will have solved it in the same way and not gotten likes, because it simply hasn't been seen by many people. This could turn into a whole lot of undesirable behavior (in a previous job I spent a great deal of time trying to figure out what votes/likes etc were made by scripts or bots, it's a thankless job).

**Comment by justgage** [comment]
I listened to the Bike Shed podcast and was drawn to this discussion. Here's my two cents.

What about making __reviewing code one of the exercises__? The Readme of this exercise could talk about the benefits mentioned by @kytrinyx and explain why. This way it's not like a reflexive thing like, "This is just what you have to do to get back to learning" but rather, "Reviewing is just another great skill to practice" I would suggest that perhaps this be done more as perhaps the 3rd exercise or something like that so we ease them into it a little.

I've also thought a lot about **small groups**. I've noticed that one of the hardest parts of starting out in a community is feeling the group was just too big to feel at home in. I kind of wonder sometimes if we assigned subgroups that could be kind of like your feedback buddies. One of the things I've enjoyed the most about the Elm community is that it's so small that I can immediately feel like I'm part of the group because it takes so little time for people to get to know and recognize me. 

As a third idea (sorry I have so much to say) I thought about people __opting in to code reviews__ that way you could say, "Would you like trade code reviews with someone?" that way people that really want feedback would be able to get it and those that don't care so much wouldn't make the activity feed look so bare which I think communicates, "We don't have a culture of reviews"

As far as the featured problems discussion, I think it should perhaps be made by the test creators but then up for debate and pull requests so that the solution, or solutions are more of a community owned things so to hopefully avoid some of the gamification problems.  

Anyway that's my (far more than) two cents.

**Comment by stantoncbradley** [comment]
really want to see some sort of vetted example.  I like the idea of sorting most commented / most liked / etc.  Also, I think the the original solution should be pinned to the top.  This solution would have continuous iterations based on feedback, and would (at least eventually) demonstrate one version of best practices to solve the question.

I think these would be the easiest to implement and get most of what we want.  I'm happy to tackle pinning the original solution to the top, if this is something people agree would be helpful.

**Comment by kytrinyx** [comment]
> Also, I think the the original solution should be pinned to the top.

Would you elaborate, please? What do you mean by "original solution"? And where would it be pinned?

**Comment by stantoncbradley** [comment]
Sure. The original solution as in the one submitted by the person who created the question. It would be pinned to the top of the list of all the other solutions to that problem

**Comment by kytrinyx** [comment]
We have explicitly not made that solution follow best practices—it's meant as a smoke test against the test suite to make sure that it's solvable. The other thing that worries me about having a single pinned solution, is that most exercises have several interesting approaches, and pinning one of them would suggest that one approach is better than another.

**Comment by stantoncbradley** [comment]
I realize that. I just think if we had one dedicated solution that could get iterated on then it could be cleaned up to at least be one example of an acceptable solution. I'm not saying it would be perfect as is, but everyone would see it and comment on it, and the original creator could clean it up as they saw fit. I'm not saying this is a perfect solution or that that example should be taken as gospel. I think it would be a good place to start tho. Right now I just see code from others that just submitted. I think we should be able to suggest interesting or different solutions to be flagged as featured as well. We just really need at least one solution that has been refactored and polished enough that for its approach it is executed as well as possible. I just thought iterating on the original solution would be the simplest, most straightforward place to start

**Comment by stantoncbradley** [comment]
Or maybe being able to sort by most liked would be enough? Because only seeing the most recent means maybe someone came up with a unique solution, but otherwise we are all just copying the same best solution from the last few days

**Comment by kytrinyx** [comment]
> otherwise we are all just copying the same best solution from the last few days

I didn't realize that people did this.

What I'm trying to avoid is having people assume that there is one good solution or one good approach and then optimize for that. I think that having one "best of" would be worse than not having any.

**Comment by justgage** [comment]
I know amazon's ratings are based not off just the raw rating but also takes how old a solution is over time, that way it would help weed out the solutions that fall out of favor over time (think callbacks in JS)

Code wars (more of a kata site so a little different) has an interesting idea with how they have not only a raw "Best" solution but also has one based on cleverness and other things. 

![codewars-example](https://cloud.githubusercontent.com/assets/164033/15629047/5b7a547e-24cd-11e6-85c2-c8c4f3110c18.png)

The nice thing about this is that by having many ways to evaluate a code you could show that something is cool for different reasons like, "Interesting", "Idiomatic", "Efficient", "Simple", etc...

In some ways I wish there was a way we could encourage slowly learning like VimGolf does. They only show a solution that is _slightly_ better than your current one. While you could just slowly copy and paste to find them all I found it encouraged me to explore and look for the answer instead of just looking at the solution. However it's hard to objectively rate a solution automatically. That may not be a treat fit.

**Comment by kytrinyx** [comment]
> In some ways I wish there was a way we could encourage slowly learning like VimGolf does. They only show a solution that is slightly better than your current one.

I would love to figure out how to do something like that.

> The nice thing about this is that by having many ways to evaluate a code you could show that something is cool for different reasons like, "Interesting", "Idiomatic", "Efficient", "Simple",

This is interesting. Someone mentioned something about labelvoting a while back: https://github.com/exercism/exercism.io/issues/1957 This sounds kind of related to that.

**Comment by stantoncbradley** [comment]
I want to learn idiomatic patterns and best practices for a language as quickly as possible. I'm ok iterating a few times on a problem on exercism, but then I want to basically at least see one verified solution before moving on to the next problem. I can then take what I learn and apply it toward the next problem

**Comment by kytrinyx** [comment]
> I want to basically at least see one verified solution before moving on to the next problem.

Yeah, understood. I think that for experienced developers, seeing one decent, idiomatic approach (even though there are several possible great, idiomatic approaches) will not necessarily be a hindrance to their learning experience.

For new developers it can be a real problem, because they often (a) copy without understanding, and (b) tell other people that they're doing it wrong because they're doing something different.

**Comment by stantoncbradley** [comment]
It's true, but better than copying something wrong/less idiomatic. They can also look up the methods and learn why the code works. I think showing a good solution is good for everyone

**Comment by justgage** [comment]
> I would love to figure out how to do something like that.

It would be awesome. In many ways I feel your bot you made is about the best way to handle this. She offers suggestions while not giving answers. This is the best way to learn in many cases. Honestly it seems the current problem is most people _don't iterate at all on their solution_. 

> It's true, but better than copying something wrong/less idiomatic. They can also look up the methods and learn why the code works. I think showing a good solution is good for everyone

I think that this is a great point. People are always going to copy and paste at least at some level if they really want to. I think it's better to steer them towards a more canonical solution. It seems like perhaps showing multiple solutions is the quickest way to help them to realize that there's no "One right way".

**Comment by kytrinyx** [comment]
> Honestly it seems the current problem is most people don't iterate at all on their solution.

That's an interesting observation—I'd have to look at the numbers, but I suspect that you're right.

> It seems like perhaps showing multiple solutions is the quickest way to help them to realize that there's no "One right way". 

Agreed. I think that the way to go is to put in place some way of having multiple showcase examples. If we have the system in place, then we can use it where we have examples, and where we don't it would perhaps encourage people to help come up with a set of examples.

The analysis is actually pretty fun—going through everything to see if we can find "typical" approaches to the problem. I did this with the leap year problem in Go, and came up with about 12 typical approaches, three of which are reasonably idiomatic.

**Comment by justgage** [comment]
> That's an interesting observation—I'd have to look at the numbers, but I suspect that you're right.

To be fair they probably did before they submitted.  But it seems a little doubtful that most people look at other peoples solutions and then go back and fix theirs (a useful activity in opinion) most people are probably just happy they could complete it and want to move on or be done for the day. 

I'm not sure that most people have enough intrinsic drive for quality to go back and redo exercises although I think we would if we knew people where looking at the. Or to ensure quality (to some degree) people where required to put their stamp of approval on them before that at them before they where considered complete (a rule at one of the companies I worked at.) I would dare say that this would help improve the quality of answers by huge degree and increase the amount of people contributing back. The hard part I guess is avoiding the blind leading the blind. 

> I came up with about 12 typical approaches, three of which are reasonably idiomatic.

I think that this is a compelling reason for examples. That way we can figure out those three idiomatic ones rather than rely on old habits. It would be cool to use machine learning to try to detect common ways and offering advice to move to more idiomatic solutions.

**Comment by kytrinyx** [comment]
>  It would be cool to use machine learning to try to detect common ways and offering advice to move to more idiomatic solutions.

I've been thinking about that... for example, could we figure out which solution your solution is similar to, and then out of those, point you to the ones where there are lots of comments? Or, could we use machine learning to show us the typical approaches, and then see what kind of comments are associated with them?

**Comment by justgage** [comment]
It sounds like a clustering problem, the hardest part is finding a good way to quantify "sameness" in a code file.

**Comment by stantoncbradley** [comment]
We could also mark certain users who are very skilled/experienced with the given language as 'moderators' or something, and show their solution for each problem with a moderator flag next to it.  I realize there are many interesting ways to solve an exercise, but really I want to see the most straightforward solution that an expert developer would code as if writing for production.

**Comment by martinsvalin** [comment]
IMHO, the fact that no one is marked as some sort of celebrity or authority is one of the beauties of Exercism. Very democratic. I feel there's a risk of Argument from Authority entering the picture if some users are given special privilege in that way. "X said such-and-such is the correct way to do this, and who am I to argue?". It could silence some who would otherwise comment.

Thinking about identifying sameness in solutions… a crude way would be to scan the solution for standard library functions, and reduce the problem to finding sameness in the list of tools employed. Maybe try to order them by how they'd be invoked (whoops, now we're close to parsing source code into an AST).

**Comment by stantoncbradley** [comment]
> could we figure out which solution your solution is similar to, and then out of those, point you to the ones where there are lots of comments?
In my experience code with lots of comments is not necessarily useful.  The comments could be idiosyncratic to that solution, and the solution might not be a good example.  Plus, I'd like to see good examples of other implementations

> Or, could we use machine learning to show us the typical approaches, and then see what kind of comments are associated with them?
This would be cool.  like I said, most of the comments I have seen are more specific to an implementation than to the design.

> I feel there's a risk of Argument from Authority entering the picture if some users are given special privilege in that way.
I see your point, but I feel this issue affects a negligible portion of users.  Most users will either be green to programming, and benefit from a source of at least a little authority, or they will be advanced enough to reason about featured solutions and determine if those solutions are any better than their own.

> It sounds like a clustering problem, the hardest part is finding a good way to quantify "sameness" in a code file.
Yes, that will be difficult.  I'd say after that, take the top 3-5 most common implementation patterns and find maybe the most liked? (most commented could mean anything, and probably it's not a great example to showcase).

I realize highlighting solutions from advanced users isn't perfect, but I feel like it is the simplest way to get most people want and would benefit from, which is a clean idiomatic solution.  I seriously doubt someone would code a better solution, yet be naive enough to think their solution is wrong because it's not how the featured solution did it.  You either know what you're doing or you don't.  And if you don't, then it is REALLY helpful to see a good vanilla idiomatic solution.  I know there are lots of good ways to solve these examples, and I would like to see them.  But seriously, just one good idiomatic solution would really benefit most of the users on here.

**Comment by justgage** [comment]
I would agree with @martinsvalin that we should be very cautious about anything giving rank or status to our answers. It's kind of like [putting a number next to your name](https://blog.codinghorror.com/for-a-bit-of-colored-ribbon/). It sounds stupid but the effects can be very bad. That's why I think having the "good" answers come from the people that make the exercise seems like the most "unassociated with one person" way to do it.  If someone doesn't like those answers then they can always make a pull request / issue in the repo about it. That way it becomes more of a wiki then a "1st place" thing.

**Comment by kytrinyx** [comment]
Ref: https://github.com/exercism/discussions/issues/34

**Comment by masters3d** [comment]
I am with @LegalizeAdulthood I do the same for the Swift track but it would be cool to have a "sample" solution for each problem. Maybe people could vote on a solution and in this way they once with the most "likes" becomes the sample or featured solution.
https://github.com/exercism/exercism.io/issues/2803#issuecomment-217212469

**Comment by justgage** [comment]
I will say for myself that the more I look through solutions I quickly converge on a solution that is very concise and readable. I will say that I'm thinking having a good solution could aid the JS track a lot because of how many _bad_ ways there are to do things.

**Comment by kytrinyx** [comment]
> I will say that I'm thinking having a good solution could aid the JS track a lot because of how many bad ways there are to do things.

That is a very good point!

I think what I'd like to see is a feature that would _allow_ multiple solutions, but will work with just one. That would put us in a good place to expand, without delaying frightfully the benefit of showing some good code.

**Comment by justgage** [comment]
> I think what I'd like to see is a feature that would allow multiple solutions, but will work with just one. That would put us in a good place to expand, without delaying frightfully the benefit of showing some good code.

@kytrinyx so do you mean that the person doing the exercise could submit multiple solutions at the same time? Like multiple files? Or do you mean just having multiple "right solutions" listed after you finish?

**Comment by kytrinyx** [comment]
No, people can already submit multiple files, and they can submit multiple iterations.

I mean that when we show example solutions, we have the ability to show several of them.

**Comment by wolverineks** [comment]
**what about having a subscription model?**

Users can choose which users they believe write idiomatic code in a particular track, and have their solutions featured in their activity stream or solutions list.

add in some tools to enable users to see who other people follow, and easily add them to their own subscriptions.

----

**what about a series of badges/endorsements in addition to "Looks Good"**

possibilities could be "Readable", "Idiomatic", "Performant", "Maintainable", "Clever", "Terse", or whatever....
list the badges on the solutions page with the number of people that have endorsed the solution

**Comment by wolverineks** [comment]
Another possibility,

Allow "Looks Good" or similar badges/endorsements/votes to decay over time.
To remain featured, or retain badges/endorsements, a submission must also have recent 
votes/endorsements/likes.

**Comment by justgage** [comment]
@wolverineks I think that series of badges/endorcements would be cool (mentioned in [this comment](https://github.com/exercism/exercism.io/issues/2803#issuecomment-222322354)) 

A subscription model would be nice. Even just having team stuff float to the top would be good. The one thing that may need to be considered is how this would expand the amount of table rows (a current issue)

**Comment by Insti** [comment]
In #113, I wrote:
> I'd also like to enable multiple solutions to be called something sensible like hello_word_golfed.rb hello_world_best_practices.rb rather than example.rb as a way of being able to document different approaches to solving a problem 

Perhaps rather than selecting a particular solution submitted through the site, a curated selection could be stored in the relevant exercism/xlanguage repository and presented in a separate 'example solutions' page, with a short description/commentary. With these open to discussion/argument via Github pull requests.

More examples:

hello_world_low_cyclomatic_complexity.rb
hello_world_recursive.rb
hello_world_best_benchmark.rb

**Comment by kytrinyx** [comment]
My one question about this approach is whether or not there are languages that mandate file names.

We might also consider this:

```
exercises/
└── hello-world
    ├── example-best-benchmark
    │   └── hello_world.rb
    ├── example-low-cyclomatic-complexity
    │   └── hello_world.rb
    └── example-recursive
        └── hello_world.rb
```

**Comment by kytrinyx** [comment]
By sticking "example" in the pathname, we would already be ignoring them when serving files.

**Comment by Daniel-at-github** [comment]
Random thoughts on Featured solutions:
* Use whatever you see out there that works:
  * Metamoderation like slashdot: Make filtered users vote the "looks great" of the solutions
  * Let watch, star and fork users and exercises like github and extrapolate trendings.
  * Present two random exercises and choose what you like the best, like [kittenwar](http://www.kittenwar.com/) ([said in #3353](https://github.com/exercism/exercism.io/issues/3353#issuecomment-274610113))
* CI featured a solutions: mark it as pass/failed tests

Random thoughts on feedback:
* Put a "rate yourself": 
  * Do you want to think about your code filling this survey
  * was it hard? 
  * do you like your result?
  * is it the kind of code that you want if you have to mantain it in production?
  * Do you want something in your solution to be peer reviewed above the rest (fill in the comments)? 
  * ...
* Make an non coding exercise out of this:
  * UX
  * Offer good coding examples without gamification
  * ...

Hope something of value (and no feature creep) is there in this thoughts :innocent:

**Comment by kytrinyx** [comment]
This discussion has been great! Thank you so much to everyone who has taken the time to share your thoughts and ideas. 🌻 

There's an experiment underway regarding gameful design. Read about it here: https://github.com/exercism/discussions/issues/123

I've added the design research label to this so that we can evaluate this question within the larger context of the design reboot (see https://github.com/exercism/discussions/issues/113 for more about this).

Since this issue addresses things that are going to be difficult to implement as a quick experiment in the current prototype, I'm going to close this. If you do think that it can be implemented as a not-too jarring and not-too complicated experiment in the current website, please open a new issue about it in the https://github.com/exercism/discussions repository.
