### ISSUE TITLE
exercism fetch with no track specified results in listing every language as started

### ISSUE THREAD

**Issue by Cohen-Carlisle** [exercism/exercism.io#2832]
I forgot to specify a language as an argument to `exercism fetch`, and later noticed the below was on my dashboard, informing me I had 29 unsubmitted problems.

![screenshot from 2016-04-16 22-37-29](https://cloud.githubusercontent.com/assets/6425580/14584753/d7ba30d8-0423-11e6-929b-b0ea76af7d2f.png)

After a bit of investigation I determined that the other listings are the first exercises of each language. I'd assume the same is true of the others that aren't displayed, as well.

The only ones actually put on my computer by a `fetch` (that I'm aware of... heh) is the Ruby exercise listed as well as a Python exercise that didn't make the 5 displayed.

I also checkout out the JSON payload of `exercism fetch` and can see it has exercises from all 29 languages.

Not sure if this would be considered a bug in the CLI or here (or a feature :laughing:).

**Comment by mhelmetag** [comment]
I think this would be better directed at the CLI. This also might be a feature... I haven't used the CLI in awhile but I remember similar things happening when I didn't specify a language (although, back then there were a lot fewer languages).

**Comment by duffn** [comment]
There's an issue for this in the TODO repository as well: https://github.com/exercism/todo/issues/169.

**Comment by kytrinyx** [comment]
I'm pretty sure the CLI is doing the right thing, and that the x-api is (well, _was_) not.

I've just done a pretty huge refactoring (with a partial rewrite) in the x-api, and I fixed this along the way. https://github.com/exercism/x-api/pull/104

I still need to deploy this--want to do so when I can spend a bit of time monitoring the site.

**Comment by kytrinyx** [comment]
This is deployed and should be fixed.

**Comment by cshutchinson** [comment]
I mistakenly executed exercism fetch with no argument today, and have 40 fetched problems in languages other than the one I am working on (Java) shown in the dashboard. Is there a way to correct this on the dashboard?

**Comment by kytrinyx** [comment]
I don't think there is at the moment. We should fix that!

Also... do you have the most recent version of the CLI? We changed the behavior of `exercism fetch` with no arguments so that it only fetches stuff for whatever directories you have in your exercism directory (which avoids the problem in the first place).

**Comment by cshutchinson** [comment]
Thanks for the super quick response. I am using version 2.2.5 which appears to be the latest compiled on April 2nd, 2016...  I will look at the code tomorrow and see if there is anything I can contribute to help fix this problem.

**Comment by kytrinyx** [comment]
Huh. I also have 2.2.5 and when I say `exercism fetch` I don't get all of the—Oh. Sheesh.

Yeah, we changed the behavior, kind of. Here's what's going on:

1. The CLI is calling the global "fetch" endpoint with no arguments, which causes a fetch to be called on every single existing track.
1. Then, when the response comes back, the CLI only _writes_ the data for directories that exist.

I think we can do two things to fix this:

1. Make it so the CLI will only fetch for directories that are present (https://github.com/exercism/cli/issues/313)
1. Only show "fetched" for tracks where you've actually submitted something.

**Comment by kytrinyx** [comment]
I'm reopening this so that we can figure out part two described by @cshutchinson above.

**Comment by kytrinyx** [comment]
I changed my mind :)

There's been a bit of churn around the whole status/fetched/unsubmitted thing, and I spent some time taking a step back and thinking about how to solve it.

I found an approach that I liked, and then took a bigger step back and realized that all of this complexity is in the app kind of haphazardly. I've taken the slightly painful step of ripping it out (perhaps temporarily) to see what it feels like. Will people miss it? I don't know. Maybe.

I have some ideas about this, but I want to give it a few days to a few weeks to simmer.

I want to thank everyone who has worked on the features, posted the bugs, tweaked, thrashed, discussed, mused, and reflected. It's truly a pleasure to get your help figuring this out.

_cross-posted this comment in all the threads that are thrashing around with this feature, so that everyone involved knows what's going on_

:heart:

Note: I will actually fix the CLI stuff, but that's now unrelated to this.
