### ISSUE TITLE
Teambox not visible anymore from dashboard with many unsubmitted solutions

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#2835]
Before the recent addition, which does introduce the collapsibles for usubmitted solutions, I had the box with my team at the bottom area of my viewport and was able to access team related stuff instantly from the dashboard.

Now there is much information on the page, I am not really interested in, but I have to scroll past it (it reaches down about 3 screenpages; the box' overall height is 2186px!) to access a link I am using nearly everyday.

Also there is so much of blank on the right side, where only every other day a notification pops up, which is away after clicking and reading it.

Can't we move the team box from below the monster box over to the right below the feedback box?

A screenshot which does show my dashboard from a couple of minutes ago:

![exercism_unsolved](https://cloud.githubusercontent.com/assets/58951/14668003/4f6455a8-06e2-11e6-80dd-ba8cef86d61b.png)

**Comment by NobbZ** [comment]
Addition:

Also there are many languages shown now, that I never touched so far at a very “high rank”. Visible at my screenshot there are psql and lua, both of them were never touched by me actively, while other tracks are far below them or even missing (there is no elixir in my list, but I have “solved” only about half of its exercises.

**Comment by mhelmetag** [comment]
Ah... This is my fault for moving all those unsubmitted languages into collapsibles... Maybe a fix would to be float the teambox over to the right?

I'm not really sure what the best way to have all this info on the page is...

**Comment by NobbZ** [comment]
Yeah, I think, that moving it right is the best. Would have made it much more accessible on smaller displays (smaller -> less height but wide enough to not collapse due to responsive design) even before the change…

**Comment by mhelmetag** [comment]
I'll take a look at this tonight and look at the rearranging the dashboard on multiple devices.

**Comment by kytrinyx** [comment]
Thanks! Maybe also we should collapse the entire "fetched" section and people can open it up if they care. It doesn't seem like fetched is the most important thing you would look for on the dashboard most of the time.

**Comment by NobbZ** [comment]
It became even worse, now that inactive tracks are shown. Tracks I did never fetched before and don't have on my hard-drive.

**Comment by kytrinyx** [comment]
Ah, I missed the inactive tracks thing. That's a bug.

The CLI behavior is not ideal here: https://github.com/exercism/cli/issues/313

I'm going to do some manual cleanup on this in the next few days.

**Comment by kytrinyx** [comment]
Fixed the inactive tracks thing in exercism/x-api@3b67fa873568560ffc157e5821865de43cb4abf8

**Comment by kytrinyx** [comment]
OK, there's been a bit of churn around the whole status/fetched/unsubmitted thing, and I spent some time taking a step back and thinking about how to solve it.

I found an approach that I liked, and then took a bigger step back and realized that all of this complexity is in the app kind of haphazardly. I've taken the slightly painful step of ripping it out (perhaps temporarily) to see what it feels like. Will people miss it? I don't know. Maybe.

I have some ideas about this, but I want to give it a few days to a few weeks to simmer.

I want to thank everyone who has worked on the features, posted the bugs, tweaked, thrashed, discussed, mused, and reflected. It's truly a pleasure to get your help figuring this out.

_cross-posted this comment in all the threads that are thrashing around with this feature, so that everyone involved knows what's going on_

:heart:
