### ISSUE TITLE
Comments are lost if not logged in

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2842]
From [twitter](https://twitter.com/tannerprynn/status/723260319527776256):

> please stop your site from losing comments when login is required, they even get lost in the browser cache

This is a real pain in the ass. I thought we had fixed it (using local storage), but clearly we have not. If someone has javascript skills and some time to dig into it, it would be great to eradicate this once and for all.

**Comment by joeltaylor** [comment]
Going to see if I can get a regression test for this and knock it out tonight.

**Comment by tprynn** [comment]
Thanks, sorry for snarkiness. There are three parts to this that contributed to three rewrites on my part:

* When logged-out, attempting to post a comment prompts log-in, and the comment is lost as you are redirected after log-in

* After log-in, I attempted to go back in browser history to the initial page. When going back in history, my comment is thankfully saved by my browser's cache for situations like this. However, it immediately gets wiped out by some javascript on the site, so I have to rewrite it.

* Then, the comment is rewritten and I'm ready to submit again. Except that due to some poor auth handling on the site, it simply redirects me to the login page again *even though I'm already logged in* because I was on the cached, logged-out version of the comment page.

So, fixes:

* Save the submission state somehow within the login flow and finish posting the comment post-login.

* Do not use javascript to overwrite field value after the page has loaded, that's a code smell and has the side effect of destroying the browser's cached data.

* Don't handle logged-out and logged-in comment posting differently in the front-end. They should be differentiated based on whether the user has valid cookies.

**Comment by joeltaylor** [comment]
Turns out there was a bug in the authentication flow and the javascript. For more info, you can check out the synopsis in the PR.

**Comment by kytrinyx** [comment]
@joeltaylor epic fix. Thank you!
