### ISSUE TITLE
Human-friendly dates within one day

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2886]
See https://github.com/exercism/exercism.io/issues/2861 and https://github.com/exercism/exercism.io/pull/2870 for a history of this issue.

For a long time we had fuzzy dates that said things like:

- 20 minutes ago
- 3 hours ago
- 5 days ago
- 3 weeks ago
- 7 months ago
- about a year ago
- ages ago

Then after a discussion I came to agree that it's frustrating to not be able to know exactly when something happened, and that the "ago" type language is great when it's within a day or so, but not for things that are far in the past.

So we wanted to change it so that:

- it shows the full date if it's older than a day, and
- it shows the fuzzy language within a day, but with a tooltip that shows the actual date and time.

The change was made in #2870, but it broke the activity stream visually:

![broken-activity-stream](https://cloud.githubusercontent.com/assets/276834/15275185/d74072b0-1a81-11e6-8889-fd9b42d17761.png)

I therefore commented out the change, and left only the full timestamp visible.

I'd like to have the fuzzy date for times within a day, with the full value as a tooltip.

**Comment by nithinbekal** [comment]
I'll look into this and submit a PR later today.

**Comment by joeltaylor** [comment]
@nithinbekal Whoops, I didn't see that you had called dibs.

The issue was that the FuzzyTime `ago` method returns a link for the tooltip, which will cause the HTML to break if nested within another link. In the screenshot above, the content is already wrapped in a link [(source)](https://github.com/exercism/exercism.io/blob/master/app/views/stream/_main.erb#L14-L28) and bad things happen.

From what I've tested locally, it seems like returning a `span` tag instead of a `<a>` fixes the issue. I think it makes sense since it's not really a link anyhow.

Tried to think of ways to get the HTML out of the helper, but haven't come up with anything just yet.

**Comment by nithinbekal** [comment]
@joeltaylor No worries! I didn't get to work on this yesterday after all. :)

**Comment by kytrinyx** [comment]
> Tried to think of ways to get the HTML out of the helper, but haven't come up with anything just yet.

:heart: I would love to see a way to do that. My first reaction when seeing (or putting) HTML in helpers is _it feels gross_, but sometimes that's just the thing that works. Meh :)
