### ISSUE TITLE
Bulk archive of submissions

### ISSUE THREAD

**Issue by darrenhaken** [exercism/exercism.io#2971]
The UI currently allows a mass delete of submissions but I'd like to be able to archive multiple submissions too.

I spoke to you on Twitter and you said this should be possible and to open a GitHub ticket, here you go :-)

**Comment by kytrinyx** [comment]
Yepp! Thanks so much.

**Comment by kytrinyx** [comment]
For context, the page in question is `http://exercism.io/:username`, which is handled by https://github.com/exercism/exercism.io/blob/master/app/routes/user.rb#L6

We should be able to add a button "archive" next to the "delete" button (make it gray, I think, rather than red or green).

<img width="999" alt="bulk-profile-actions" src="https://cloud.githubusercontent.com/assets/276834/16889013/be7e75a2-4aa0-11e6-8d1b-a295c883ce3e.png">

**Comment by wolverineks** [comment]
it sounds like you want to use the same form but have it submit to the /exercise/delete route or /exercises/:key/archive route based on which submit button is pressed. Is this right?

**Comment by kytrinyx** [comment]
Yeah, the same form, different route.

Also I just realized that the delete route should be `DELETE /exercises/:key`. I'll see about cleaning that up.

**Comment by aranair** [comment]
Took a quick jab at this, do let me know if I got everything!:P

**Comment by nickb-minted** [comment]
I think we should close this issue 😄

**Comment by kytrinyx** [comment]
Indeed! Thanks :)
