### ISSUE TITLE
Repeating npm install for every new problem.

### ISSUE THREAD

**Issue by niksmac** [exercism/exercism.io#2972]
Repeating npm install for every new problem, looks weird and time consuming. This is for ecmascript test.

**Comment by kytrinyx** [comment]
@exercism/javascript Would you take a look at this?

**Comment by niksmac** [comment]
@kytrinyx  Sorry, but that page gives me a 404.

**Comment by rchavarria** [comment]
Yep, that's true. For each new problem, there are some libraries/tools that need to be re-installed.

I understand that this can be as time consuming (and disk space consuming as well).

The ecmascript track works in this way to keep it as simple as possible for exercism.io users. Instead of requiring users to install globally all required tools, the track requires them to install globally just one.

A possible solution for this could be to install all required tools globally. They are not infinite, just: Babel, Jasmine, Gulp and ESLint (specific versions would be provided as well, to avoid problems). But I don't see it as a good practice, and it may conflict with those tools if the exercism.io user has already them installed globally. I think it could be possible to describe this in the [installing instructions](http://exercism.io/languages/ecmascript#installing).

Another solution could be to install them half-globally, half-locally. They wouldn't be installed globally, they would be installed in the root folder for ECMAScript problems: `<EXERCISM_FOLDER>/ecmascript`, a folder that could be available for all ECMAScript problems, without polluting the user's global *space* for NodeJS packages. But, I'm not sure this will work, and I don't know if this would need aditional configuration from the user side.

I think I could spend some time with this intermediate procedure.

**Comment by kytrinyx** [comment]
> that page gives me a 404

Sorry, yes. That was a question to the exercism javascript team, not to you (the @ mention notifies them of the conversation).

**Comment by kytrinyx** [comment]
> I think I could spend some time with this intermediate procedure.

That sounds like the best of both worlds... if it actually works.

**Comment by rchavarria** [comment]
I've tried... and it works.

I think the most important change to fix this is to explain it right in the [installation instructions](http://exercism.io/languages/ecmascript#installing). Basically, I would have to explain the `gulp-cli` must be installed globally (same as now):

    npm install -g gulp-cli

These node packages should be installed on `<EXERCISM_FOLDER>/ecmascript` (maybe with specific versions):

    npm install babel
    npm install del
    npm install gulp
    npm install gulp-babel
    npm install gulp-eslint
    npm install gulp-jasmine
    npm install yargs

And the crucial step, users must update the `PATH` environment variable (as of now) to include that folder:

    export PATH=<EXERCISM_FOLDER>/ecmascript:$PATH

---

**Question**: is there a way to copy the file `package.json` from the root folder in the git repository to the `<EXERCISM_FOLDER>/ecmascript` folder? That would simplify the second step: instead of installing a bunch of node packages, the command would be just `npm install`.

**Comment by kytrinyx** [comment]
> is there a way to copy the file package.json from the root folder in the git repository to the <EXERCISM_FOLDER>/ecmascript folder?

Not yet, unfortunately. It's in the list of things we'd really, really like to do: https://github.com/exercism/cli/issues/88

**Comment by tejasbubane** [comment]
Can this be closed in favour of https://github.com/exercism/xecmascript/issues/235?

**Comment by rchavarria** [comment]
Yep, absolutely!
