### ISSUE TITLE
Coveralls - the newbies guide.

### ISSUE THREAD

**Issue by ghost** [exercism/exercism.io#2973]
I'm confused about the following with Coveralls (https://coveralls.io/) which is being used on Exercism.io and would appreciate feedback on the following:
- what's the project conventions with using Coveralls?
- how do we pass?
- how much do we need to write tests?
- is there some documentation in relation to Coveralls + Exercism which is written for newbies?

**Comment by mhelmetag** [comment]
> what's the project conventions with using Coveralls?
It's better if coverage goes up rather than down 😆 

> how do we pass?
You don't really pass or fail. Coveralls just reports whether test coverage went up or down in the PR branch compared to master.

> how much do we need to write tests?
If the method has more than a few lines, it's probably worth testing. I like to make at least 2 - 3 tests per method: a pass, fail, and edge case. It would probably be nice to stay higher than 75% (currently around 80%).

> is there some documentation in relation to Coveralls + Exercism which is written for newbies?
Nope! Not yet.

**Comment by kytrinyx** [comment]
Yeah, up is better than down, and we don't have an official threshold, we just want it to be reasonable (75% is a good number, but I wouldn't be alarmed if it dropped a bit below it).

I really, really want to overhaul the documentation and will make a note of the coveralls thing.

**Comment by ramyaravindranath** [comment]
I am happy to come up with the document about coveralls for newbies.

**Comment by machikoyasuda** [comment]
@jendiamond the results of this PR could be great for the meetup!

**Comment by tejasbubane** [comment]
Related to #3139 

There are two parameters:
`coverage threshold for failure` and `coverage decrease threshold for failure`.

**Comment by Insti** [comment]
This issue is tagged `good first patch` but I was confused reading through the issue trying to work out what needed to be done.

@tejasbubane what is the actionable task here?

**Comment by tejasbubane** [comment]
I think we should have a doc which addresses these:

* Little bit about coveralls.
* What is coverage? (maybe pointing to resources instead of explaining)
* When can we expect the build to fail with coveralls? (the threshold values set)

Not sure if this should be a separate file or part of some existing doc.

**Comment by kytrinyx** [comment]
> Not sure if this should be a separate file or part of some existing doc.

It seems like this could be a separate doc, linked to from the CONTRIBUTING guide.

**Comment by m-a-ge** [comment]
I can try to create this doc if it's still a relevant issue considering that a new redesigned version of exercism.io is being developed at the moment as stated in '[I would like to help; I know / want to get better at Ruby](https://github.com/exercism/docs/blob/master/finding-your-way.md#i-would-like-to-help-i-know--want-to-get-better-at-ruby)'

**Comment by kytrinyx** [comment]
Hm. I actually think that I'd like to hold off on this. I'm not sure we're going to be using coveralls at all.

I'm going to close this and then once the dust settles in the new redesign we can start considering what guides and docs we need to add.

Thanks @m-a-ge!
