### ISSUE TITLE
Multi-line OCaml comments not correctly highlighted

### ISSUE THREAD

**Issue by dcorking** [exercism/exercism.io#3044]
Multiline comments, such as those [in my submission](http://exercism.io/submissions/6ae5d256b9d444229dfb8f1bfbc16e30) are not correctly highlighted for syntax.

The second and subsequent lines are formatted as code, not as comments.

The same code [pasted onto the Rouge demo site](http://rouge.jneen.net/pastes/5xPa) seems to format better.

**Comment by Insti** [comment]
Excellent bug report :heart:, thanks!

**Comment by k3rni** [comment]
The problem is in [lib/rouge/formatters/html_exercism.rb:66](https://github.com/exercism/exercism.io/blob/master/lib/rouge/formatters/html_exercism.rb#L66), where the HTML-wrapped string is cut into lines with no regard for its structure. Each line is then wrapped into a span.

It's easily seen in the raw HTML output (not your browser's inspector), tags rearranged for clarity:

```html
<span id='L4'></span>
<span id='L5'><span class="c">(* reverse the first list, then prepend it to the second list. (In</span>
<span id='L6'>   other words, one by one, move the head of the first list onto the head</span>
<span id='L7'>   of the second.) *)</span></span>
```

What should happen here is that each of the comment lines should be wrapped in its own `span.c`. This is valid HTML, but only accidentalyl. What happens when I change the "external" spans into divs?

```html
<div id='L4'></div>
<div id='L5'><span class="c">(* reverse the first list, then prepend it to the second list. (In</div>
<div id='L6'>   other words, one by one, move the head of the first list onto the head</div>
<div id='L7'>   of the second.) *)</span></div>
```

which is clearly invalid.
