### ISSUE TITLE
Entering an incorrect path requires Login

### ISSUE THREAD

**Issue by blueelvis** [exercism/exercism.io#3064]
Hi,

I mistakenly entered the URL as - http://exercism.io/heslp
I know that this page does not exist, but I got a screen asking me to login via Github instead of returning 404. On logging in via Github, I got the 404 page.

Don't you think that it should be otherwise and directly a 404.

This does not happen when logged in via Github.

Also, if I enter the URL as 
http://exercism.io/helpsssssssssss
http://exercism.io/help;;;;;;;;;;;;sss

it redirects me to 'http://exercism.io/help'

Isn't this similar to the PHP's famous *cgi.fix_pathinfo* parameter. Should this be fixed?
Security Issue - http://serverfault.com/questions/627903/is-the-php-option-cgi-fix-pathinfo-really-dangerous-with-nginx-php-fpm

**Comment by Insti** [comment]
> Don't you think that it should be otherwise and directly a 404.

How do you know that `heslp` is not a page you have to be logged in to see?
Do you want someone who is not logged in to be able to guess all the paths that only logged in people can see by what returns a 404 and what returns a login prompt?
(In this case it doesn't *really* matter since all the code is open source anyway.)

> Isn't this similar to the PHP's famous cgi.fix_pathinfo parameter. 

No, because Sinatra is not trying to execute arbitrary content if it cannot find something.

> Also, if I enter the URL as
http://exercism.io/helpsssssssssss
it redirects me to 'http://exercism.io/help'

This is expected behaviour, since the pattern that matches `/help` is not anchored at the right hand end. and `/help` is the first thing that it matches, after that it stops looking.

That part of the code is here: https://github.com/exercism/exercism.io/blob/master/app/routes/static.rb

**Comment by Insti** [comment]
And you can read more about how Sinatra works here: http://www.sinatrarb.com/intro.html
