### ISSUE TITLE
Inconsistent behavior from anchor tags on CLI page

### ISSUE THREAD

**Issue by bradhvr** [exercism/exercism.io#3078]
I'm getting very inconsistent behavior from the anchor tags on the [http://exercism.io/cli](http://exercism.io/cli) page. If you click on `MAC OS X` or `Windows` and then click one of the anchor links for methods of installing, the page jumps to the appropriate section but often the navbar will cover the section's `<h2>` title.

What is weird is that sometimes it will jump fine and sometimes it will cover the title. Here are some examples from the Windows section. I'm using Chrome, but I noticed the same behavior in Firefox.

- On a fresh page load clicking the `Manual Installation` link works ok:
![image](https://cloud.githubusercontent.com/assets/4006188/17894072/0ccc5aba-6916-11e6-9cc9-bcea3c06079d.png)

- Without refreshing the page, clicking the `Manual Installation` link again covers the title:
![image](https://cloud.githubusercontent.com/assets/4006188/17894346/0880ce68-6917-11e6-9c41-5093ce0c1a2c.png)

- Again without refreshing the page, clicking the `Using the Chocolatey Package Manager for Windows` link covers the title:
![image](https://cloud.githubusercontent.com/assets/4006188/17894323/f8ee2342-6916-11e6-8852-961fa3e14e32.png)

- After this if I click `Manual Installation` again without refreshing the page it works ok.

I'm not sure if anchor tags are used anywhere else. I did a search for `<a name` in Sublime Text and these two markdown files were all that it found: `mac.md`, `windows.md`

**Comment by bradhvr** [comment]
I played around a little bit and so far best I can do is have the first click jump higher than it should, and then subsequent clicks end up being spot on. Don't really understand yet why it's acting the way it does. What is it about the first page load/click that is different?

**Comment by kytrinyx** [comment]
That is so odd! I have no idea why this would be happening. @gusseting @troubalex do either of you know anything about this sort of behavior?

**Comment by troubalex** [comment]
Is there any kind of Javascript going on as far as you can see, @bradhvr? Something must be calculating the offset for the navbar at the top.

Maybe the fact that the tabs point to ```exercism.io/cli#mac``` and the anchors on the (tabbed) page to ```exercism.io/cli#installing-without-homebrew``` leads to trouble?

**Comment by gusseting** [comment]
@bradhvr here's what i think the problem is:
`### Using Powershell and the Chocolatey Package Manager for Windows <a name="chocolatey"></a> ###  `
I'll have a shot at doing a fix by putting the links _above_ the heading, rather than beside them, which is why you're getting the heading covered by the top nav - the heading is going over 2 lines.

I'm working on making these pages simpler at the moment, and will take this issue into account.

**Comment by gusseting** [comment]
Confirmed that the problem is just where the anchor links are.
I've changed where the link is in the windows.md file, and here's the results:

![screen shot 2016-08-26 at 3 02 09 pm](https://cloud.githubusercontent.com/assets/540264/17994687/4799b50e-6b9e-11e6-8375-34cda3bc7660.png)

I'll do a pull request asap.

**Comment by kytrinyx** [comment]
so much :heart: for finding this problem in the first place, and figuring out root cause @gusseting @bradhvr

**Comment by jtigger** [comment]
Confirm fixed.
