### ISSUE TITLE
Retract invitations doesn't update Invited members list

### ISSUE THREAD

**Issue by MohanL** [exercism/exercism.io#3185]
The bug happens when inviting a wrong person to the team and try to delete the invitation. 
The message says "user removed from team team" but the invitation list doesn't update.
![1](https://cloud.githubusercontent.com/assets/10900547/19523460/96fd5438-95e8-11e6-81ba-0113f7482b85.gif)

**Comment by c1505** [comment]
I just encountered this too.

**Comment by c1505** [comment]
Looks like it is hitting the route since you are getting that success message, but that there isn't really code to delete an invite.  The code that is executed is to delete a current member of the team.  This should probably be a separate route too.  I can look at this tonight.  

Probably will do these things and submit a PR soon:
-Update manage.erb to change class of link for javascript action from member_delete to invite_delete
-Add an deleteInvite method .to app.coffee to submit the form
-Add a route/action to routes/teams.rb
-Add a method to team_membership_invite.rb to destroy the invite
-Add a test to team_test.rb for deleting an invite as a team manager 

Let me know if any of that looks off base.

**Comment by MohanL** [comment]
@c1505  can you also check on the invitee's side to see if the notification of the invitation retracted ?

**Comment by c1505** [comment]
@MohanL Yup.  I'll look into that also. :)

**Comment by MohanL** [comment]
@c1505 
Could you please have a review of my PR at https://github.com/exercism/exercism.io/pull/3193 ? 
Thank you.

**Comment by kotp** [comment]
@zrc210 noticed the same issue today.

**Comment by kytrinyx** [comment]
I've asked Mohan if they'll have time to complete their PR, or if we should carry it.

**Comment by bernardoamc** [comment]
I'm redoing it right now, but the credit is all to Mohan.

**Comment by kytrinyx** [comment]
@bernardoamc thank you!

**Comment by kytrinyx** [comment]
Closed by #3304, deploying now.
