### ISSUE TITLE
Show test results on submissions page

### ISSUE THREAD

**Issue by andreyrubtsov** [exercism/exercism.io#3198]
Currently it is seems impossible to distinguish submission with PASSed tests from the FAILed one.
What I am missing is at least some simple green/red indication of whether tests passed or not.
Otherwise, it is kind of hard to learn from other's submissions simply because you are not sure wether they are simply correct (it might even be even syntactically incorrect or contain complete garbage).

**Comment by kytrinyx** [comment]
@andreyrubtsov - I know you closed this, but I wanted to give a little context about this behavior.

The main reason we don't have any pass/fail indication in the submission page is that we currently don't have the capacity to run people's solutions after they've submitted them. It would require spinning up a VM somewhere with the correct environment, and this would take a lot of resources that we don't have (e.g. we don't have the programming resources to put together the VM or sandbox to run someone's code in 33 languages, and we don't have the server resources to run the code on).

It is possible to download other people's solutions using the `exercism download <UUID of exercise>` command in the command-line client, so you can try running their code to see if it passes. The issue here is that sometimes the test suites change and are not always backwards-compatible with older solutions.

**Comment by andreyrubtsov** [comment]
@kytrinyx Thank you for a clear explanation, now I understand the problem.

**Comment by mhelmetag** [comment]
@kytrinyx, but what about having the submitters environment run the test, pipe the output to a file and submit the output with their solution haha. Have people's systems do the work!

**Comment by andreyrubtsov** [comment]
@katrinyx, jfyi yesterday bitbucket pipelines were made GA, i think we could link exercism with user bitbucket repo to track build status

**Comment by kytrinyx** [comment]
@mhelmetag We could do that. In fact, that is possible now (pipe to a file, then exercism submit the solution and that file). It would require a bit of documentation... not sure where, though.

**Comment by kotp** [comment]
It is even possible to submit it as a comment, when submitting the solution.

In Bash shell...

```
exercism submit hello_world.rb --comment "$(ruby hello_world_test.rb )"
```

It will show as this [iteration does](http://exercism.io/submissions/bfcc906654f54f0bb66134afc7cd598a).
