### ISSUE TITLE
Team invitation not showing up in notifications after changing Github username

### ISSUE THREAD

**Issue by claytonflesher** [exercism/exercism.io#3222]
I recently changed my github username from Calvyn82 to claytonflesher,

Around the same time, I was sent an invitation to the team:
http://exercism.io/teams/confident-poodr/streams

The invitation never showed up in my notifications for me to accept it. Please let me know if there is any further information I can provide, or a known issue I can try to help out with on this subject.

**Comment by MohanL** [comment]
potentially relate to https://github.com/exercism/exercism.io/issues/3100

**Comment by kytrinyx** [comment]
@claytonflesher if an invitation is sent to a username that is not in our system, it will create a placeholder user. The next time someone logs in to the system using that GitHub username, it will connect the GitHub user to the placeholder user, and the invitation will show up.

If the invitation was sent to the Calvyn82 user after you changed your username, then we would have no way of connecting this. If it was sent to the 'claytonflescher' user before you had logged into exercism, then we also couldn't catch this, because it would create a placeholder user, but then we'd connect you to the real user and change the username on your account the next time you log in.

I've manually updated the invitation—let me know if this fixes it for you.

**Comment by bernardoamc** [comment]
I'm closing this one for now, we can always reopen if necessary.
