### ISSUE TITLE
Submissions with multiple files are displayed always alphabetically.

### ISSUE THREAD

**Issue by rbasso** [exercism/exercism.io#3277]
I'm not sure if this was intentional or an *accidental feature*, but solutions submitted with multiple files are always displayed with the files ordered alphabetically, despite the order supplied to the command line client.

Step to reproduce:

```bash
$ cd exercism/foo/bar
$ touch a b c
$ exercism submit b c a
$ exericsm open foo bar
```

This behavior is undesirable, because it doesn't allow users to put what they consider more important first, and also forces reviewers to scroll down searching for the most critical parts.

**Comment by kytrinyx** [comment]
This is unintended (I totally never thought about it)—and I think it's worth thinking about a fix.

Implementation detail: we store the files as a hash / dict / map which by definition is unordered. Right now we're using Ruby, and ruby hashes happen to be ordered, but it's not something we can rely on. So we would need some explicit way of ordering them or defining an order.

**Comment by kytrinyx** [comment]
The recommendation here is to store (and submit) the files in the order that they are submitted. I think that is the correct behavior.

In order to fix it, though, we're going to need to discuss how to tackle it, and it's likely going to involve both CLI and API changes.

@rbasso would you mind moving this to the discussions repo so that we can hash out the details there, and then open prescriptive/actionable issues in the correct places once we figure that out?

**Comment by kotp** [comment]
Issue moved to [exercism/discussions #130](https://github.com/exercism/discussions/issues/130) via [**ZenHub**](https://www.zenhub.com/)
