### ISSUE TITLE
Feature request: Navigation between implementations

### ISSUE THREAD

**Issue by acamargo** [exercism/exercism.io#3305]
It would be very handy to have a couple of links like "previous implementation" and "next implementation" on the page you read submissions from other devs.

I don't know how to call that page, an example is http://exercism.io/submissions/ca3534a7d2a3449e81e1af6ced675436

**Comment by Insti** [comment]
Yeah, this comes up from time to time. Have a search through the issues and see if you can find what was said about it.

**Comment by kytrinyx** [comment]
I know I've written about this before, but I had trouble finding a good thread to point you to.

There are a few tricky things with this. What does "next" actually mean?

Is it...

- The next solution to the same exercise in the same language?
- What if you are navigating a track stream (not filtered to a solution)?
- What if you are navigating a team stream (not necessarily filtered by language, sometimes filtered by user)?
- As soon as you comment, this is the most recently active thing in the activity stream, which means that the next-most-recently active is probably the thing that you looked at just prior to looking at this one

**Comment by acamargo** [comment]
I searched and found it nothing, so, I gave up.

But, as @kytrinyx spent some time writing all those options, my vote goes to number 1.

I thought just about a "simple" way to navigate between solutions to the same exercise in the same language.

**Comment by Motardo** [comment]
There was a [discussion about this here](https://github.com/exercism/discussions/issues/33#issuecomment-241856639). I think it would be a nice feature that would save some clicking back and forth from the `See other implementations of _` page.

**Comment by binoymichael** [comment]
I was thinking if we could have a quick peek of the solutions in the 'Activity Streams' page itself with an accordion style implementation. It would probably look something like [this](https://gfycat.com/SpeedyRadiantDingo).

Some points I could think of:
- Users can quickly see other solutions and comments. Saves the users some clicks.
- It would work well with both the language streams and the exercise specific streams. So there is no confusion about the next and previous implementations.
- Implementation would mostly be just AJAX calls to fetch the submissions.

Please share your thoughts. If everyone is fine with this approach, I can take a shot at implementing this.

**Comment by kytrinyx** [comment]
@binoymichael a quick peek using ajax sounds like it could work. I'd be up for seeing something in that direction. Would you take a few minutes to work through what it would look/work like in the different activity streams? Nothing fancy, just a few bullet points about each situation would be really helpful.

**Comment by binoymichael** [comment]
@kytrinyx 
- The gif that I linked to in the previous comment is how I envision the activity stream page will look like.
- Screenshot for more clarity
<img width="974" alt="screen shot 2017-01-02 at 12 50 20 pm" src="https://cloud.githubusercontent.com/assets/756795/21596047/61b1d672-d0ea-11e6-80c9-29803f930f70.png">

- afaik there are just three sections in the Activity Stream (a) Language wise solutions (b) My Solutions and (c) Exercise wise solutions. 
All three behave in a similar fashion - rendered as lists and currently clicking on each list item currently takes you to a new page (/exercises/uuid). 
What I have in mind is that, instead of navigating to a new page, we just pull the contents of the submission (/exercises/uuid) via an AJAX call, open the list item like an accordion and display it there. This would be similar for all the three sections.


Would you like me to address any specific point?

**Comment by kytrinyx** [comment]
It sounds like you're suggesting that the ajax call would go to an endpoint that fetches the N "next" exercises for the stream that you were navigating.

* How do we know what stream you were navigating?
* What does "next" mean? Let's say that you are working your way through all of the "clock" exercises in Go. You've commented on the 7 first exercises, and you click on exercise 8. You comment. Now the exercise which was number 8 has become number 1, since it is the one with the most recent change. This means that the next 5 exercises are exercises that you already have commented on today.
* What do we show if you followed a link to an exercise from somewhere else (e.g. twitter, or the someone's profile page, or perhaps you were looking at solution number 8 in the Go / Clock stream, and saw an interesting comment by someone you don't know, and clicked through to their solution.


There are two different types of activity streams:

**Track Streams** which have the three sections that you mention:

* all of a language
* all of an exercise in a language
* all of the exercises by the current user

**Team Streams** which have the following sections:

* all of a team (many languages, exercises, users)
* all of a language within a team (many exercises, users)
* all of an exercise in a language within a team (many users)
* all the exercises by a single user within a team (many languages, exercises)
* all the exercises in a given language by a single user within a team (many exercises)

We will also be implementing a **profile stream**:

* all of the exercises for a given user
* all of the exercises in a single language for a given user

**Comment by binoymichael** [comment]
> It sounds like you're suggesting that the ajax call would go to an endpoint that fetches the N "next" exercises for the stream that you were navigating.

No, I was thinking of one ajax call per submission. When the user clicks on a submission on whichever stream he/she is on (it doesn't matter how he/she arrived there), we get the particular submission uuid and we fire an ajax call to get the details of that particular submission alone and display it. When the user clicks on the next submission, we fire an ajax call again to get the details of the next submission.

> How do we know what stream you were navigating?

Just to clarify, the changes I am suggesting will be on the activity stream page and not on the submissions page.  So, it does not matter which stream the user is on.

> What does "next" mean? Let's say that you are working your way through all of the "clock" exercises in Go. You've commented on the 7 first exercises, and you click on exercise 8. You comment. Now the exercise which was number 8 has become number 1, since it is the one with the most recent change. This means that the next 5 exercises are exercises that you already have commented on today.

There is no concept of 'next' in what I am suggesting. 

> What do we show if you followed a link to an exercise from somewhere else (e.g. twitter, or the someone's profile page, or perhaps you were looking at solution number 8 in the Go / Clock stream, and saw an interesting comment by someone you don't know, and clicked through to their solution.

The user will have to use the existing mechanisms like 'See other implementations of -exercise- in -language-' to get to the activity stream. He/she then can use the quick view option on the stream.

---

Sorry, I am still very new to the website and the codebase. So maybe I am attacking the problem at a much micro level instead of seeing the big picture.

This is what I do now, when I want to see other solutions of an exercise that I completed:
 - Go to my solution. Click on the 'See other implementations' link to go to the 'Activity Stream'
 - Open each solution that I want to see in a new tab
 - Once I have browsed through all the tabs, come back to the activity stream page and open another set of tabs for the another set of solutions

Instead, what I would like is this:
- Get to the activity stream page
- Take a quick peek at a submission by another user
   + Click 'quick peek' on the stream list item. It expands to reveal a loading icon. 
   + Ajax request to fetch the details of that submission alone gets fired. Solution gets loaded below the list item.
- If the solution is similar to mine or if there is nothing to comment on it, close the accordion pane and move to the next submission.
- If I want to explore the submission in detail, I can still open it in a new tab and dig into it.
- Even when I leave a comment on a submission, my activity stream order is preserved until I manually refresh the page.

So, we take the users away from the activity stream page only when it is really necessary.

What happens when a user clicks on links inside the quick view pane, is something we need to think about. My initial thought is that:
- Clicking on the iteration link will reload the quick view pane with that particular iteration code and comments
- Click on other links would probably take the user away from the stream page
- It would be great if the user can comment on the solution from the quick view pane itself

I didn't know that a team stream existed, but I think what I suggested will work well with team streams as well.

**Comment by kytrinyx** [comment]
> No, I was thinking of one ajax call per submission. When the user clicks on a submission on whichever stream he/she is on (it doesn't matter how he/she arrived there), we get the particular submission uuid and we fire an ajax call to get the details of that particular submission alone and display it.

Ah, OK, I totally missed that. Yes, if that's what we do, then this would work. It's going to be harder to fit everything into a single, narrower view, though.

**Comment by binoymichael** [comment]
Cool :) Shall I go ahead and take a shot at this?

**Comment by kytrinyx** [comment]
Would you do a mock-up of what it might look like before doing any code on it?

E.g.

- an exercise with 17 iterations (is there a difference between that and 1 iteration?)
- an exercise with 0 comments, 1 comment, 15 comments
- an exercise with 1 file, 2 files, 5 files

**Comment by binoymichael** [comment]
Sure.

**Comment by binoymichael** [comment]
Here are the mockups. 
I loaded the existing submissions page into a div below a list item and the manipulated the html/css via the web console to get these mockups. 


With 0 comments, the avatars hidden away in the comments section -
<img width="1438" alt="mockup1" src="https://cloud.githubusercontent.com/assets/756795/21665526/c66ff036-d2a1-11e6-8d76-d5f45da0680e.png">

With 1 comment, 1 iteration, 1 file and with the avatars hidden in the comments section -
<img width="1438" alt="mockup2" src="https://cloud.githubusercontent.com/assets/756795/21665527/c671d37e-d2a1-11e6-87ad-8d9d50a009b8.png">

With lof of comments. Did not hide away the avatars here - 
<img width="1439" alt="mockup3-1" src="https://cloud.githubusercontent.com/assets/756795/21665528/c673ffd2-d2a1-11e6-8875-584da2c8e512.png">
<img width="1439" alt="mockup3-2" src="https://cloud.githubusercontent.com/assets/756795/21665529/c67663c6-d2a1-11e6-94bd-6c90eafa4d6a.png">
<img width="1440" alt="mockup3-3" src="https://cloud.githubusercontent.com/assets/756795/21665530/c676e01c-d2a1-11e6-8840-e083866145cc.png">

With multiple files, multiple iterations. Zoomed out the browser a bit to get both the files in the screenshot -
<img width="966" alt="mockup4" src="https://cloud.githubusercontent.com/assets/756795/21665531/c677608c-d2a1-11e6-937c-0949240ff356.png">

With a lot of iterations - 
<img width="1280" alt="mockup6" src="https://cloud.githubusercontent.com/assets/756795/21665534/c687e402-d2a1-11e6-80d9-a9a2a7fa847a.png">

With 5 files - 
<img width="1169" alt="mockup7-1" src="https://cloud.githubusercontent.com/assets/756795/21666083/778e714c-d2a4-11e6-9204-ddd3f31311af.png">
<img width="1196" alt="mockup7-2" src="https://cloud.githubusercontent.com/assets/756795/21666084/778ee8d4-d2a4-11e6-93c9-cfd65a7e8ed5.png">


With the code section expanded and the comments rendered below the code section. Again zoomed out the browser a bit to get the comments section in one screenshot - 
<img width="990" alt="mockup5" src="https://cloud.githubusercontent.com/assets/756795/21665533/c68348e8-d2a1-11e6-977a-2d00ea18ab37.png">

---

We could probably set the expanded code view (as shown in the last screenshot) as the default in the quick peek section. This way it is much easier to read the code. In the mockups, with the code section expanded, I can view 102 columns of code and 46 columns of code when it is not expanded.

Please share your thoughts.

**Comment by kytrinyx** [comment]
I think that it's worth a try. It seems a little bit cramped without the full width, but if it helps people's workflow, it's worth it.

In light of https://github.com/exercism/discussions/issues/113 I think that we can experiment with a few things as well, so long as people are OK with it.

@troubalex @jtigger @Insti @kotp @bernardoamc @tejasbubane You have all had really great opinions in the past :-) Would you take a quick look at this?

**Comment by Motardo** [comment]
Current behavior: clicking a list item loads the page at `submissions/xyz`  

Proposed new behavior: clicking `View` loads the page at `submissions/xyz` and clicking `Quick Peek` opens an accordion view containing the exercises iteration tabs, submission code, and comments.  
![screenshot](https://cloud.githubusercontent.com/assets/756795/21666083/778e714c-d2a4-11e6-9204-ddd3f31311af.png)

I don't think the text `View` really conveys the idea that it is opening a new page, but I don't have a better suggestion (Maybe something like `Goto`). For the `Quick Peek` accordion fold, it might be nice to use a semantic icon like 
![selection_017](https://cloud.githubusercontent.com/assets/2099793/21694109/9b831848-d351-11e6-9d10-5e9122e08829.png)
or 
![selection_016](https://cloud.githubusercontent.com/assets/2099793/21694123/a9f21460-d351-11e6-8e72-989cb57b04b1.png)


Also, if you can comment and switch iterations from the `Quick Peek`, then maybe we don't need the `View` behavior at all? What if we just click the list item to open the accordion view and not even have separate `View` and `Quick Peek` links?

**Comment by binoymichael** [comment]
1. Yes, if we can, we should come with a better name for 'View'. I didn't put much thought into the names of the links. We could also have an external link icon <img width="40" alt="screen shot 2017-01-05 at 11 46 59 am" src="https://cloud.githubusercontent.com/assets/756795/21695045/dccf2e64-d33c-11e6-9a9a-e88a3888cd31.png"> next to it convey that it will open in a new page.

2. IMO, we should still have a separate view. The accordion view would not work well for certain scenarios. e.g. if I want to bookmark a certain iteration and the discussion on it.

**Comment by kotp** [comment]
I think "quick peek" should be "peek" because "You can't tell me how my peeking speed should be!".  The way that I generally use Exercism website is via a browser called w3m, so I think that in general, I can't really know how I feel about it until after I see how it renders there.

In the graphical mockup, it appears to be some really good ideas there.

**Comment by Motardo** [comment]
> a browser called w3m

I don't think this kind of AJAX effect would work in w3m because it doesn't interpret javascript (is that correct?)

> IMO, we should still have a separate view. The accordion view would not work well for certain scenarios. e.g. if I want to bookmark a certain iteration and the discussion on it.

Indeed, and also for people browsing without javascript enabled.

**Comment by kotp** [comment]
The effect will not work, but the data may be organized well.  For the most part, so far, there aren't any tricks that are being used that break using w3m.  I get the graphics where I should and things work well for fast, low cost, usage.

**Comment by tejasbubane** [comment]
> I think that it's worth a try. It seems a little bit cramped without the full width, but if it helps people's workflow, it's worth it.

I was wondering if we absolutely need to show the comments in there. Since we don't have full width, can we use a minified layout instead of the full one we are using now and show just the solution and nothing else? I would even go ahead to suggest to show only the latest/last iteration (but I am not very sure if this would be appropriate or feasible). For a full view we can have an external link as @binoymichael suggested in his previous comment.

**Comment by binoymichael** [comment]
> I was wondering if we need to show the comments in there.

In my opinion, comments are as important as the submitted code, so we should be displaying both in the quick peek section. The main idea here is to take a quick peek at the submission, before deciding whether to open up the submission in a new page and dig into it in detail. If we don't show the comments in the quick peek section, the user will again have to open a new tab to just to view the comments and I feel that would defeat the purpose of this change.

**Comment by kytrinyx** [comment]
I'm taking a pass through our issue tracker with the goal of making sure that every open issue we have on exercism/exercism.io is actionable. 

As this issue stands it isn't actionable. If you would like to move this topic forward, please open a new issue in http://github.com/exercism/discussions

Please:
- summarize the points so far
- link back to this issue
- include the intended goals for the discussion
