### ISSUE TITLE
Feature Request: Diff view comparing prior iteration with currently viewed iteration

### ISSUE THREAD

**Issue by kotp** [exercism/exercism.io#3307]
It would be nice to be able to see a view showing the differences between iteration 1 and iteration 2, for example, of solutions.

**Comment by kytrinyx** [comment]
We had this and ripped it out. I'd consider adding it back if we can do it without making the solution page even messier and harder to navigate than it already is.

**Comment by kotp** [comment]
Just a button similar to the clipboard and expand view button...

![selection_002](https://cloud.githubusercontent.com/assets/16747/21107083/7fdd52f8-c05e-11e6-9673-ae1e6d977ccd.png)

In the text browser, perhaps a diff link.  The others don't show, so no messing up the page there.

![selection_003](https://cloud.githubusercontent.com/assets/16747/21107167/d44314ea-c05e-11e6-92f9-8db8677dea8d.png)

**Comment by kytrinyx** [comment]
That could work. It should stay in the same page, though, not take you to a different page, I think. That way you could look at the diff and still comment.

**Comment by kotp** [comment]
Yes, that is the hope.  Perhaps the diff side by side, with the comment area below.

**Comment by Motardo** [comment]
>  It should stay in the same page, though, not take you to a different page, I think. That way you could look at the diff and still comment.  

What is the best way to do this? Lets say Iteration 1 is at `/submissions/xxx` and Iteration 2 is at `submissions/yyy`. So if you're looking at Iteration 2 and click the `diff` button:
 - the browser stays on `submission/yyy`
 - there would be an ajax request for Iteration 1's code only (not comments)
 - the view updates with a nice side-by-side diff of the iterations
 - any comments you make get posted to Iteration 2

Also what should happen if there are more than two iterations? Always diff the predecessor?

**Comment by kotp** [comment]
The bullet list looks good.

Checkbox the iterations you want to see the diff of, but default to the prior if they are not selected.

**Comment by Motardo** [comment]
I have been working on this. I took the approach of generating the diffs on the frontend with [jsdiff](https://github.com/kpdecker/jsdiff) rather than making ajax requests to a server side diff engine. My reasoning was that it would be simpler and snappier without involving a server round trip.

When you click the diff button, the current iteration's navigation tab turns green, and the iteration being diffed against tab turns red. Changes in the code are highlighted red and green the same way. It diffs against the previous iteration by default, but you can select another iteration by clicking it's tab. Clicking the diff button again restores the normal, original view. 

Here is a version with a unified diff:
![unified](https://cloud.githubusercontent.com/assets/2099793/21463921/2cd2ff6a-c93f-11e6-87eb-0888dbe32403.png)

 Here is a version with a side by side diff:
![diff1](https://cloud.githubusercontent.com/assets/2099793/21463923/31755478-c93f-11e6-9c83-c46c5c9df3a8.png)

Let me know what you think, and if I'm on the right track. Any suggestions for the diff button icon? I'm currently using font awesome's `fa-file-code-o`, but I would like to find something better.
![diffbtn](https://cloud.githubusercontent.com/assets/2099793/21464266/228a9bd8-c946-11e6-933b-c3c9481ddc4d.png)

**Comment by kotp** [comment]
I kind of like the `</>` symbol for this, since it is similar in communication that you are going to see a different iteration, but may be there is a universal symbol for "not equal" that can be used?

**Comment by kotp** [comment]
Would the `<=>` graphic make sense for the diff button graphic?

**Comment by kytrinyx** [comment]
Or maybe something like this? 
<img width="144" alt="compare" src="https://cloud.githubusercontent.com/assets/276834/21594122/06abb2e2-d0dc-11e6-933c-cbb8a853b734.png">

**Comment by kotp** [comment]
![selection_006](https://cloud.githubusercontent.com/assets/16747/21598228/d8c60436-d126-11e6-801f-a74977bb24bd.png)

From [github](https://octicons.github.com/icon/diff/)

**Comment by kytrinyx** [comment]
@kotp the GitHub one is the one! Thanks for finding that.

**Comment by Motardo** [comment]
Yes the github diff icon is what I was looking for. I'm going to make a PR for this now.

**Comment by kotp** [comment]
I think @kytrinyx likes the icon, and agrees it is not making the page more confusing, staying out of the way... so I am closing the issue and hopefully we will see the PR come in soon!
