### ISSUE TITLE
C++ / CMake help needed

### ISSUE THREAD

**Issue by Insti** [exercism/exercism.io#3333]
As part of moving to the up-to-date Exercism language track structure, the [CMakeLists.txt](https://github.com/exercism/xcpp/blob/master/CMakeLists.txt) file for the cpp track needs updating. There is a pull request that already moves the files:  https://github.com/exercism/xcpp/pull/108 but the makefile needs to be updated to run the tests in their new locations.

Can you help?

**Comment by Adam-A** [comment]
Sorry, I'm very new to open source. Could you clarify a little bit more? So in the CMakeLists.txt file I need to change the old directory to the new directory location where the tests would run?

**Comment by kytrinyx** [comment]
@Adam-A That's my understanding. Here's a way to test it out:

1. Fork the https://github.com/exercism/xcpp repo
1. Clone your fork
1. Add the upstream as a remote (`git remote add upstream https://github.com/exercism/xcpp.git`)
1. Pull down https://github.com/exercism/xcpp/pull/108 to a local branch with `git pull upstream refs/pull/108/head && git checkout carry-108 FETCH_HEAD`
1. Switch to the branch and get the makefile working
1. Push to your repo and create a new pull request. In that pull request use the magic comment "closes #108" so that the old pull request will get closed when yours get merged
1. the continuous integration system will try running the tests as well, so if it works, everything will look green in the pull request, and if it doesn't it will complain

I *think* that's it. Always feel free to pop into the gitter chat and get some help from people hanging out there.

**Comment by Adam-A** [comment]
@kytrinyx Thank you so much! Much appreciated.

**Comment by Insti** [comment]
> Could you clarify a little bit more? So in the CMakeLists.txt file I need to change the old directory to the new directory location where the tests would run?

Yes.

The exercises used to live in /foo, they have been moved to /exercises/foo but the makefile was trying to run the tests in /foo, which no longer exists.

However if you follow the link to the pull request you will see that this has already been solved.

**Comment by jdsutherland** [comment]
As @Insti mentioned, it looks like this was fixed as part of [exercism/xcpp#108](https://github.com/exercism/xcpp/pull/108/commits/c093e9f73bb9b91042b03a37283db5fa43b72e19) and should be closed.

**Comment by kytrinyx** [comment]
Good call. Thanks!
