### ISSUE TITLE
Limit teams to a specific language

### ISSUE THREAD

**Issue by sebasmagri** [exercism/exercism.io#3362]
This would be nice for language specific teams in which their members are also working on other languages and don't want to have the team timeline flooded by other lang responses.

**Comment by kytrinyx** [comment]
Thanks for the suggestion @sebasmagri. To clarify you mean this as a potential configuration on teams, right?

**Comment by sebasmagri** [comment]
@kytrinyx yes, it could be a team parameter limiting its timeline to a single language.

**Comment by NobbZ** [comment]
This was part of #2944 (“focused languages“) which is still open for this and various other reasons.

@kytrinyx maybe we take a closer look at #2944 and split it up into multiple issues which we can close on its own? I think that would increase discoverability of the sub-issues and reduce doubles as well.

**Comment by kytrinyx** [comment]
@sebasmagri This sounds like a good feature.

Yes, I think splitting #2944 up would probably make it more likely for various issues to be fixed.

**Comment by bernardoamc** [comment]
That's an interesting feature! 

@sebasmagri Do you mind if I investigate a little and try to come up with something?

**Comment by sebasmagri** [comment]
@bernardoamc probably @kytrinyx can give you more information about this.

**Comment by kytrinyx** [comment]
@sebasmagri actually @bernardoamc is our resident teams expert :-) I'd say have at it, Bernardo.

**Comment by bernardoamc** [comment]
We have options here:

_1.  Create a column in teams with the allowed teams, or empty if we don't want to restrict by language. We have something similar with tags._

Downsides of option 1:
  - It will be hard to update the column in case we change the slug of a track (should never happen?).
  - Using an empty value to represent `all` is kinda weird (when the user doesn't want to limit his team by language).
  - If we ever want to filter teams by allowed languages it can be slow. For example, list teams that allows only ruby and rust.
Pros:
  - We don't need to join tables, so the existing queries don't need to change that much.

  _2. Create a new table to hold this information._

Downsides of option 2:
  - Existing queries will get more expensive since we will need to join another table.
  - We still can't express that we don't want to limit a. team by language
Pros:
  - Since the table only holds a foreign key we don't need to deal with updates in a track manually.
  - Filtering teams by specific languages is easier.

Since option 1 and option 2 have the same downside regarding the case where the user doesn't want to limit his team by language, we will probably need to create another column in `teams` representing the this state. The alternative is to check for an empty value in the new array column or for an empty result after querying the new table.

Any thoughts regarding the subject @kytrinyx, @NobbZ and @sebasmagri ?

**Comment by kytrinyx** [comment]
> Create a column in teams with the allowed teams

You mean allowed languages, right?

**Comment by kytrinyx** [comment]
> It will be hard to update the column in case we change the slug of a track (should never happen?).

Technically, yes, but it has already happened. Twice. Luckily it's on languages that were not active yet, so it only affected a very small number of people who were beta-testing the track.

In the first case, it happened because the name of the language changed. In the second, it was because we hadn't done a good job naming the track (we are using a variant of the language, and had not specified that in the track name and slug).

**Comment by kytrinyx** [comment]
Question: Would it be sufficient to say that you can either restrict to a _single_ language, or you can't restrict it at all? It seems a very, very restricted use case to have a team for two or three languages.

**Comment by NobbZ** [comment]
Why not use tags for this? If a language matches the tag name it is primary
while every other language is hidden per default

Katrina Owen <notifications@github.com> schrieb am Sa., 4. März 2017, 17:04:

**Comment by bernardoamc** [comment]
> You mean allowed languages, right?

Haha, yes! 

> Technically, yes, but it has already happened. Twice. Luckily it's on languages that were not active yet, so it only affected a very small number of people who were beta-testing the track.

That's good to know! It shouldn't be complicated to update the teams in the case of beta-testing, but knowing that it happened in the past is a good eye opener. 

> Question: Would it be sufficient to say that you can either restrict to a single language, or you can't restrict it at all? It seems a very, very restricted use case to have a team for two or three languages.

Good question. I can see value in restricting a team by a frontend+backend languages, but it  shouldn't be the main use case for sure. We can totally go through this route first (solving for one team) and gather more data before trying to build a general solution.

> Why not use tags for this? If a language matches the tag name it is primary while every other language is hidden per default

This can totally work, but I think we would be too smart in this case. As an user I would be confused to restrict my team language(s) using tags. As a developer it would be weird for me to read the source code and see that we are using the `tags` column for multiple things.  That can be just me though!

**Comment by kytrinyx** [comment]
> As an user I would be confused to restrict my team language(s) using tags. As a developer it would be weird for me to read the source code and see that we are using the tags column for multiple things.

I would find that really confusing as well. I'd rather avoid that.

**Comment by kytrinyx** [comment]
I'm taking a pass through our issue tracker with the goal of making sure that every open issue we have on exercism/exercism.io is actionable. 

As this issue stands it isn't actionable. If you would like to move this topic forward, please open a new issue in http://github.com/exercism/discussions

Please:
- summarize the points so far
- link back to this issue
- include the intended goals for the discussion
