### ISSUE TITLE
gradle tests not working

### ISSUE THREAD

**Issue by dtwizee** [exercism/exercism.io#3379]
first time using excercise.io installed everything correctly but couldnt get gradle test in cmd to work

```C:\Users\David\exercism\java\hello-world> gradle test
'gradle' is not recognized as an internal or external command,
operable program or batch file.```
 
help would be appreciated

**Comment by NobbZ** [comment]
Installing `gradle` on windows is explained on the [Installing Java](http://exercism.io/languages/java/installing) page.

According to your error message I'd guess you are using windows, so the next step according to that guide is to `choco install gradle`.

Please do remember, that `choco` needs an elevated powershell to work.

If oyur problem persists though, it would be more appropriate to open up an issue at https://github.com/exercism/xjava/issues since documentation is part of the tracks repository.

**Comment by kotp** [comment]
Issue moved to [exercism/xjava #294](https://github.com/exercism/xjava/issues/294) via [**ZenHub**](https://www.zenhub.com/)
