### ISSUE TITLE
activity stream for all languages' submissions for a specific exercise?

### ISSUE THREAD

**Issue by petertseng** [exercism/exercism.io#3395]
We can currently get an activity stream for submissions of:

* a specific language * exercise pair e.g. http://exercism.io/tracks/c/exercises/leap
* all exercises (at least, those submitted by me) for a specific language e.g. http://exercism.io/tracks/c/exercises

So then, what if there were a way to get submissions of all languages (at least, those submitted by me) for a specific exercise?

This may help serve the polyglot segment of the userbase, who might like to see solutions to a given problem in a language they're familiar with together with a language they're learning.

Maybe it also helps serve those people who are curious about the various approaches one might take to solve a problem and for whom the language of expression of that approach is less important. I alluded to similar ideas in https://github.com/exercism/discussions/issues/65#issuecomment-284279846.

I don't know if this is too much of a jarring switch for Exercism, as I perceive Exercism to be pretty track-focused currently but this particular feed would be very exercise-focused in contrast, an orthogonal direction.

**Comment by kytrinyx** [comment]
I've opened an issue in the past suggesting that we make the user's profile an activity stream: https://github.com/exercism/exercism.io/issues/2059

**Comment by kytrinyx** [comment]
Rereading the original issue, I see that the profile activity stream is completely different from what you're asking about.

I've added the design research label to this so that we can evaluate the question within the larger context of the design reboot (see https://github.com/exercism/discussions/issues/113 for more about this).

Since this issue addresses things that are going to be difficult to implement as a quick experiment in the current prototype, I'm going to close this. If you do think that it can be implemented as a not-too jarring and not-too complicated experiment in the current website, please open this as an issue in the discussions repository.
