### ISSUE TITLE
Improve ordering in Progress section on profile page

### ISSUE THREAD

**Issue by shdblowers** [exercism/exercism.io#3457]
Hello, thanks for making exercism, I have a suggestion on how to improve it.

I'm not sure what the current ordering of languages is on the Progress section on the profile page, I can't figure it out. 

But, I think what would be a better ordering is by the date of last submitted exercise for that language or language you have submitted the most number of solutions to.

**Comment by kytrinyx** [comment]
@shdblowers I'm not actually sure what the ordering on the Progress section is, I'd have to look. My guess is that whatever it currently is, it wasn't intentional.

The code is in [the UserTracksSummary file][summary-file] and from what I can tell, the order is whatever comes out of the database, which is non-deterministic.

[summary-file]: https://github.com/exercism/exercism.io/blob/master/lib/exercism/user_tracks_summary.rb

**Comment by kytrinyx** [comment]
I would welcome a pull request that makes the change that you propose.

**Comment by shdblowers** [comment]
Excellent, I'll take a look into writing that pull request then :smile:

**Comment by kytrinyx** [comment]
Sweet! ✨ holler if you get stuck (the code base is a bit of a ~~mess~~ prototype).

**Comment by Insti** [comment]
The ordering of the progress section should be most recent iteration first and then by iteration date descending.

However it has never been implemented correctly, due to misunderstandings by those trying to implement it that the html code `data-sorted-direction="descending"` 
does not change the ordering of the data that is returned from the database,
and that the sample data used for testing is accidentally sorted correctly but the data from the live database is NOT.

See: 
https://github.com/exercism/exercism.io/pull/2993

 https://github.com/exercism/exercism.io/blob/master/app/views/user/_exercises_table.erb#L21

See also:
 https://github.com/exercism/exercism.io/issues/3246
https://github.com/exercism/exercism.io/pull/3272

**Comment by kotp** [comment]
Thanks @insti for the research and explanation.  I am sure it will come in handy.

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this, since we're now that v2 is in beta, we're actively discouraging design changes to v1.

You can see v2 here: http://v2.exercism.io/
And provide feedback here: https://github.com/exercism/v2-feedback/blob/master/README.md

Thanks for the input everyone! 🌻
