### ISSUE TITLE
Public team search suggests private team names

### ISSUE THREAD

**Issue by ncs-alane** [exercism/exercism.io#3522]
1. I began typing in a private team name to the public team search on the web site. 
   * **Expected:** to not see the private team name suggested, 
   * **Actual:** I see the private team name as a suggestion.

**Comment by bernardoamc** [comment]
Thanks for opening the issue @ncs-alane !

Can you provide the search query so we can reproduce this scenario?

**Comment by ncs-alane** [comment]
I created a new, private team named "aprivateslug" for the sake of this issue. If a user not on the team types "apr" in to the search box, "aprivateslug" is suggested.

**Comment by bernardoamc** [comment]
I see, the team cannot be found but the suggestion is still there. 👍

**Comment by nathanbwright** [comment]
@bernardoamc - Are you working on this, or can I take it?

**Comment by bernardoamc** [comment]
@nathanbwright I was planning to tackle it by this week, but feel free to take it! Thanks! <3

**Comment by nathanbwright** [comment]
Here's what I've found...

When a team is created it **always** creates tags for that team regardless of whether the team is private or not... [relevant team.rb line](https://github.com/exercism/exercism.io/blob/master/lib/exercism/team.rb#L57) 

Is this the intended behavior? It would seem to me that if a team is set to private it shouldn't have tags created from it.

@bernardoamc what do you think?

**Comment by bernardoamc** [comment]
@nathanbwright You got it, this is an implementation that should have changed when private teams were implemented. We can totally change this to only create tags when the team is public. This brings a few complications, but we can deal with them. Let me try to list a few scenarios:

1. Team is created as private. This case is straightforward, we can avoid creating the tags.
2. Team is created as private and then becomes public. Also not a problem as we can create tags at the moment the team becomes public.
3. Team is created as public and then becomes private. This is a little more annoying since a tag doesn't belong to a team. What we can do here is delete the tag (from `tags` table) associated with only the team name since we know that they are unique per team and then update the `tags` column in the `teams` table.

What do you think, sounds reasonable?

**Comment by Insti** [comment]
What do tags have to do with public/private?

**Comment by nathanbwright** [comment]
@Insti Tags are being automatically created from the team name, slug, and any additional tags added regardless of whether the team is public or private.

Then when somebody types into the search field at http://exercism.io/teams, it doesn't search through team names, it actually searches through all the tags (just like the placeholder text says "Search tags").

Does that make sense?

**Comment by Insti** [comment]
Thanks @nathanbwright 

To me it seems like tags and privacy are two separate concepts.
A teams tags should be independent of its privacy status.

Rather than messing about adding/removing tags, whatever is returning the tags should be filtering out any tags that are not publicly visible. (In this case because they are not attached to public teams?)

**Comment by nathanbwright** [comment]
Maybe some screenshots would be helpful...

This is after a fresh `db:seed` and the creation of one private team `Private Team`

The `tags` table:
![tags](https://cloud.githubusercontent.com/assets/4740018/26690727/9f576ea4-46b7-11e7-9b21-194b184ec0f9.png)

The `teams` table:
![teams](https://cloud.githubusercontent.com/assets/4740018/26690737/ab110354-46b7-11e7-8466-273869a3bc74.png)


@Insti Tags and teams are two independent concepts. Tags do not have any concept of their status (private or public). The issue is that tags that should be private (such as the team's name and slug) are getting added to the tags table, which is public.


@bernardoamc What about any additional tags that could have been added to a team? Do you think we should treat the team's name and slug as the only things that get removed from the tags table?

**Comment by Insti** [comment]
@nathanbwright are you saying that private teams may not have tags?

**Comment by bernardoamc** [comment]
> @bernardoamc What about any additional tags that could have been added to a team? Do you think we should treat the team's name and slug as the only things that get removed from the tags table?

I would say that for now this should be enough, but it doesn't solve all the problems. We can't remove tags that are not the team name and slug because they can still be in use by other teams. Unless you write a migration/script that checks that the tag is being used by only that team.

@Insti The problem is that there is no concept of public or private tags, every team that has a `Ruby` tag shares it. You can see in the DB above that teams `chocolades` and `ghost` both references the `Go` tag for example.

**Comment by Insti** [comment]
> The problem is that there is no concept of public or private tags.

Yes, this is the problem.   

It can be solved by working out which are public (used by at least one public team) and which are private (not used by any public team).

What is the problem you are trying to solve?

> every team that has a Ruby tag shares it. You can see in the DB above that teams `chocolades` and `ghost` both references the Go tag for example.

This is not a problem.

**Comment by bernardoamc** [comment]
> This is not a problem.

It is right now. Unless we are ok in removing tags from private teams since they are used only for search anyway. Or work in a new solution/model for tags.

**Comment by Insti** [comment]
(It's really not a problem.)

Using the definitions of public/private tags from [my previous post](https://github.com/exercism/exercism.io/issues/3522#issuecomment-305605749).

On the team search page:

What happens when you select a public tag from the dropdown list?
What happens when you select a private tag from the dropdown list?

**Comment by bernardoamc** [comment]
@Insti Sorry if I'm not getting it, are you suggesting going through every team from a tag and checking if this tag is public/private every time we search? Or are you suggesting removing private tags?

> What happens when you select a public tag from the dropdown list?
> What happens when you select a private tag from the dropdown list?

"Public" tag   -> Every public team with this tag will be returned.
"Private" tag -> No results returned.

Note the quotes in public/private, this is to mention that there is no concept of public/private tags.

**Comment by Insti** [comment]
> "Public" tag -> Every public team with this tag will be returned.
> "Private" tag -> No results returned.

What would happen if the "Private" tags were not present in the dropdown list?

> going through every team from a tag and checking if this tag is public/private every time we search?

This is the closest to what I am suggesting.

I am suggesting that:
1. The tags returned `/tags` route should only include tags which have at least 1 public team associated with them.
2. This can be achieved without adding/removing to the list of tags every time a team changes it's public/private status.

**Comment by bernardoamc** [comment]
> What would happen if the "Private" tags were not present in the dropdown list?

That's basically what we want to achieve right now, because tags are useful only for searching teams. 

> The tags returned /tags route should only include tags which have at least 1 public team associated with them.
> This can be achieved without adding/removing to the list of tags every time a team changes it's public/private status.

This is one solution for sure, another solution is to decide this during team creation/update using for a example a counter in the tags table that keeps track of the number of `public` teams using this tag.

**Comment by Insti** [comment]
Yes, there are several ways to solve this.

> another solution is to decide this during team creation/update using for a example a counter in the tags table that keeps track of the number of public teams using this tag.

This is also a valid way to solve the problem, I personally do not prefer this solution because it  requires the team creation/update methods to care about maintenance of the tags table every time it changes rather than just adding a new one if it doesn't already exist and
it would be duplicating information that is already present in the database (which tags are present on private teams)

Databases are optimised for doing this sort of query so performance should not be something to worry about until it starts to become an issue. If anything does need changing it might be the addition of a tag/team mapping table rather than using an integer array column to store the mappings from tags to teams.





But whoever makes the PR gets to decide which solution they want to use.

**Comment by nathanbwright** [comment]
Do we need to reach some sort of consensus with what needs to happen with tags before I work on a solution?

**Comment by Insti** [comment]
@nathanbwright probably not.

As long as it solves the problem it doesn't matter too much. Working code that exists is usually better than theoretically ideal code that doesn't.
