### ISSUE TITLE
Connection pool in production might be too small

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3533]
We currently have 5 connections in the production connection pool, and we're seeing connection errors in production.

```
ActiveRecord::ConnectionTimeoutError·could not obtain a connection from the pool within 5.000 seconds (waited 5.006 seconds); all pooled connections were in use
```

Do any of you know what the best practices are for determining the size of the production connection pool?

Or... figuring out if something isn't releasing its connection?

**Comment by kytrinyx** [comment]
We do use sidekiq to kick off rikki jobs. Maybe sidekiq needs its own connection

https://devcenter.heroku.com/articles/forked-pg-connections#sidekiq

**Comment by nilbus** [comment]
Assumption I'm making about production:
- MRI ruby server that handles one request concurrently (each will have its own connection pool, making 5 plenty for normal use)

Is that true, or is it a multithreading/threadsafe server? If so, 5 is likely too low. You'd want to set it as high as you think might be reasonable to have concurrent DB requests. 

Sidekiq behavior is irrelevant here, because the bugsnag reports (not posted here) have stack traces originating from requests.

**Comment by kytrinyx** [comment]
We're using `puma` which is a multithreading/threadsafe server.

How high would be reasonable for concurrent DB requests? Where would the estimated number originate from?

**Comment by nilbus** [comment]
As per [Heroku's recommendations for Puma][1], set the connection pool size equal the max thread count.

As you make this change, the new performance bottleneck will become the database performance, rather than the database connection count. There's a good chance that this will solve the problem we're seeing, because the database likely has a lot of untapped power when we're limiting connections to 5 per worker. On the other hand, if someone is attempting a DOS attack or our application has some database performance issues that require optimization, upping the effecting limit on concurrent requests could possibly overwhelm the database and cause other site-wide performance problems. Just something to be look out for. If you do encounter database performance issues, the best way to attack those will be to attack them directly (i.e. optimizing queries or caching).

**Comment by nilbus** [comment]
oops, forgot the link.

https://devcenter.heroku.com/articles/concurrency-and-database-connections#threaded-servers

**Comment by kytrinyx** [comment]
Thank you @nilbus. From my reading of https://github.com/puma/puma#configuration it looks like the default is 16. I'll try that and see how we do.
