### ISSUE TITLE
Stacktrace detectives: Why is user_exercise nil here?

### ISSUE THREAD

**Issue by Insti** [exercism/exercism.io#3549]
In what circumstances could `user_exercise` be nil?

[app/views/submissions/show.erb#L10](https://github.com/exercism/exercism.io/blob/e4408c062b94fc1c6b6a1e32d3a020f1df8dd3d5/app/views/submissions/show.erb#L10)
```html
      <% if submission.user_exercise.help_requested? %>
        <span class="label label-danger">Requested help</span>
      <% end %>
```

`show.erb` is is called by: [app/routes/submissions.rb#L30](https://github.com/exercism/exercism.io/blob/e4408c062b94fc1c6b6a1e32d3a020f1df8dd3d5/app/routes/submissions.rb#L30)
`Submission` can be found at [lib/exercism/submission.rb](https://github.com/exercism/exercism.io/blob/e4408c062b94fc1c6b6a1e32d3a020f1df8dd3d5/lib/exercism/submission.rb)

Context: 
A `NoMethodError` captured by bugsnag from the live site.

Full stack trace:
```
app/views/submissions/show.erb:10:in `block in singleton class': undefined method `help_requested?' for nil:NilClass (NoMethodError)
    from vendor/bundle/ruby/2.3.0/gems/tilt-2.0.7/lib/tilt/template.rb:170:in `call'
    from vendor/bundle/ruby/2.3.0/gems/tilt-2.0.7/lib/tilt/template.rb:170:in `evaluate'
    from vendor/bundle/ruby/2.3.0/gems/tilt-2.0.7/lib/tilt/template.rb:109:in `render'
    from vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:839:in `render'
    from vendor/bundle/ruby/2.3.0/gems/sinatra-contrib-2.0.0/lib/sinatra/engine_tracking.rb:91:in `block in render'
    from vendor/bundle/ruby/2.3.0/gems/sinatra-contrib-2.0.0/lib/sinatra/engine_tracking.rb:83:in `with_engine'
    from vendor/bundle/ruby/2.3.0/gems/sinatra-contrib-2.0.0/lib/sinatra/engine_tracking.rb:91:in `render'
    from vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:682:in `erb'
    from app/routes/submissions.rb:30:in `block in <class:Submissions>'
    from vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1631:in `call'
    from vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1631:in `block in compile!'
    from vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:991:in `block (3 levels) in route!'
    from vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1010:in `route_eval'
    from vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:991:in `block (2 levels) in route!'
    from vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1037:in `block in process_route'
    from vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1035:in `catch'
    from vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1035:in `process_route'
    from vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:989:in `block in route!'
    from vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:988:in `each'
    from vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:988:in `route!'
    from vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1094:in `block in dispatch!'
    from vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'
    from vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'
    from vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'
    from vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1091:in `dispatch!'
    from vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `block in call!'
    from vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'
    from vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'
    from vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'
    from vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `call!'
    from vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:913:in `call'
    from vendor/bundle/ruby/2.3.0/gems/rack-flash3-1.0.5/lib/rack/flash.rb:124:in `call'
    from vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/xss_header.rb:18:in `call'
    from vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/path_traversal.rb:16:in `call'
    from vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/json_csrf.rb:26:in `call'
    from vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
    from vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
    from vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/frame_options.rb:31:in `call'
    from vendor/bundle/ruby/2.3.0/gems/rack-2.0.2/lib/rack/logger.rb:15:in `call'
```

**Comment by kntsoriano** [comment]
Hi @Insti, I looked at why this bug happens. I'm not able to pinpoint it exactly yet, but here's what I found out:

## How a submission is created

1. Submissions are created when the CLI posts to `/user/assignments`. Within this, it creates an `Attempt`.
2. `Attempt` is directly responsible for creating a submission. First, a `Submission` is created inside `Attempt#initialize`:

```
  def initialize(user, *stuff)
    @user = user
    @iteration = stuff.last
    @slug = iteration.slug
    @track = iteration.track_id
    @comment = iteration.comment
    @submission = Submission.on(Problem.new(track, slug))
    submission.solution = iteration.solution
  end
```

A `Submission` is already created as soon as `Submission.on` is called. When a `Submission` is first created, it is always assigned `user_exercise_id = nil`.

3. `user_exercise_id` is only updated once `Attempt#save` is called. `Attempt#save` contains a call to `Hack::UserUpdatesExercise`. This is where `user_exercise_id` for a `Submission` is set correctly.

```
class Attempt
  def save
    user.submissions << submission
    submission.comments.create(user: user, body: comment) if comment.present?

    Hack::UpdatesUserExercise.new(submission.user_id, submission.track_id, submission.slug).update
    submission.reload.viewed_by(user)
    self
  end
end
```

```
module Hack
  class UpdatesUserExercise
    def update
      return unless latest

      exercise.user_id = user_id
      exercise.language = latest.language
      exercise.slug = latest.slug
      exercise.created_at ||= earliest_submission_at
      exercise.updated_at = most_recent_change_at
      exercise.iteration_count = submissions.count
      exercise.skipped_at = nil if exercise.iteration_count > 0
      exercise.last_iteration_at = latest.created_at
      exercise.update_last_activity(latest)
      exercise.save

      submissions.each do |s|
        s.user_exercise_id = exercise.id
        s.save
      end
    end
  end
end
```

## Possible scenarios why `user_exercise=nil`
1. A user attempted to access the page as soon as an exercise was submitted. The `user_exercise_id` wasn't updated yet, but the submission was already created. To check if this is the case, we can check if the specific `Submission` that threw the error already has a `user_exercise_id` assigned to it.
2. The submission wasn't updated because `Hack::UpdatesUserExercise#update` returned due to the guard clause. This is an unlikely case because we are sure that a `Submission` gets created first.
3. An exercise wasn't created properly in `Hack::UpdatesUserExercise#update`. I've checked and an `Exercise` isn't created because of a DB level constraint that ensures that `user_id` for an `Exercise` should exist. To check if this is the case, we can look at Bugsnag and see if an error was thrown regarding creation of an `Exercise`.

## Possible solution
Based on the code, it seems that we always assume that a `Submission` always has `UserExercise` associated with it. With that said, we must do the ff (if possible):

1. Create and update a `Submission` in one atomic step. We should assign `user_exercise_id` as soon as we create a `Submission`.
2. Add model validations and a `null: false` constraint to ensure that `user_exercise_id` is always present for a `Submission`.

**Comment by Insti** [comment]
Thanks @kntsoriano great informative write-up 👍 :heart: ⭐️ 

This issue might not be important to fix right now as:
1. It only seems to have happened once.
2. Nextercism (The planned site update) will be re-implementing solution storage.

But I like 

> Create and update a Submission in one atomic step. We should assign user_exercise_id as soon as we create a Submission.

@kytrinyx thoughts?

**Comment by kytrinyx** [comment]
Agreed that this is probably not a very urgent fix to do, but I do like the proposal. I'd say go for it, if you have the cycles to spare!

**Comment by kntsoriano** [comment]
Are there more important things I can work on? I have more time on my hands right now, and I would like to help :D

**Comment by kytrinyx** [comment]
@kntsoriano Probably _the_ most important thing right now is a tool that will let each track maintainer generate the README for exercises so that each exercise becomes stand-alone. Do you happen to know Go at all? I'm thinking we'll expand [configlet](https://github.com/exercism/configlet) since this seems to be pretty legitimate track configuration.

**Comment by kntsoriano** [comment]
Sadly, I have very little experience with Go. I just used it once for a very small project at work.

Is it possible for that problem to be solved with the experience I have?

**Comment by kytrinyx** [comment]
@kntsoriano I really don't know. I think I might sit down today and see if I can build this.

What languages do you feel comfortable working in?

We need to settle this discussion: https://github.com/exercism/discussions/issues/159 and then there's a bunch of work to be done to turn the existing linear tracks into tracks with core exercises and secondary exercises.

Also, we're going to want to do a clean rewrite of the APIs to submit and fetch exercises pretty soon—there's a bit of work there as well to figure out exactly what those APIs are and need to do.

There's a nice little improvement suggestion here for the current team stuff (if you know javascript) https://github.com/exercism/discussions/issues/164

**Comment by kntsoriano** [comment]
Thank you very much! I'm comfortable with Ruby and Javascript. I'll look into the links you posted.

**Comment by kytrinyx** [comment]
Awesome, we're definitely going to need help in the Ruby, JavaScript, and ECMAScript tracks with the transformation of the metadata, and the API will be all Ruby.
