### ISSUE TITLE
Typescript: Using yarn lint will fail with error ' was unexpected at this time.

### ISSUE THREAD

**Issue by marekpetak** [exercism/exercism.io#3572]
Typescript excecism using Windows OS (8.1)

When running `yarn lint` above error will occur.
error details:

    yarn lint v0.24.5                           
    $ tslint '*.ts?(x)'; exit 0                 
    ' was unexpected at this time.              
                                            
    E:\exercism\typescript\hamming>  "E:\exercism\typescript\hamming\node_modules\.bin\\node.exe"  "E:\exercism\typescript\hamming\node_modules\.bin\\..\tslint\bin\tslint" '*.ts?(x)'; exit 0
    error Command failed with exit code 255.    

changing package.json from

    "scripts": {
        "test": "jest --no-cache",
        "lint": "tslint '*.ts?(x)'; exit 0"
    }

to

    "scripts": {
        "test": "jest --no-cache",
        "lint": "tslint *.ts?(x)"
    }

not sure what is the reason behind `exit 0`

**Comment by NobbZ** [comment]
After changing this, it will probably fail on linuxes.

Also your issue is much better suited in the [exercism/typescript repository](https://github.com/exercism/typescript).

PS: I can't close here, therefore I'd be happy if someone who can, moves this over to the other repositories issue tracker using ZenHub.

**Comment by marekpetak** [comment]
@NobbZ I'm happy to close this here, but I'm not sure how to move it across ...

**Comment by marekpetak** [comment]
moved to https://github.com/exercism/typescript/issues/45
