### ISSUE TITLE
Show Lines of Code in solution lists

### ISSUE THREAD

**Issue by GaryBoone** [exercism/exercism.io#3582]
The primary way I review other solutions is to look for implementations that are more elegant than mine or use simpler techniques. In both cases, these solutions tend to have fewer lines of code. Currently, the list of solutions (eg http://exercism.io/tracks/go/exercises/palindrome-products) shows, for each solution, the number of iterations and number of comments. So there's no way to pick out solutions that are more concise. Instead, the tiles should include the number of lines of code for each solution. Ideally, comment lines would not be counted, so as not to discourage their use. 

Fewer lines of code can sometimes mean more obscure code instead of simple, clear, and maintainable code; taken to extreme, it's a poor practice. So it should not be a goal in itself to encourage only the shortest solutions. User rankings or solution sorts on LoC are not obviously good ideas. Nevertheless, showing the LoC would allow finding and reading usually elegant solutions to the problems that I may have missed in my solution.

**Comment by kytrinyx** [comment]
Thanks for the input @GaryBoone.

/cc @iHiD @nicolechalmers for consideration in the redesign.

**Comment by Insti** [comment]
Shortest solutions are not always the best, showing lines of code will lead to gamification based on that metric [citation needed]. 

Just look through a lot of solutions, even longer ones will often have something interesting you can learn.

**Comment by weitzman** [comment]
The OP is not suggesting that we default sort by fewest lines. Its merely an additional statistics - and a valuable one IMO.

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this, since we're now that v2 is in beta, we're actively discouraging design changes to v1.

You can see v2 here: http://v2.exercism.io/
And provide feedback here: https://github.com/exercism/v2-feedback/blob/master/README.md

There will be sorting and filtering along various axes in v2 (not sure how much of that is already implemented), but do keep an eye on that and feel free to suggest improvements in the v2-feedback repo.

Thanks for the input everyone! 🌻
