### ISSUE TITLE
My work blocks x.exercism.io !

### ISSUE THREAD

**Issue by andrewmp** [exercism/exercism.io#3600]
Hi,
My work blocks access to this specific server, x.exercism.io:
[]PS[8]>exercism fetch csharp hello-world
2017/07/28 11:00:46 Get http://x.exercism.io/v2/exercises/csharp/hello-world?key=04d24eb7a0cb4087b36ae5e659c4672a: dial
tcp: lookup x.exercism.io: no such host

Any way I can copy them for offline use instead? Git works, main page works too.

Thanks,
Andrew

**Comment by NobbZ** [comment]
1. Try to convince your people in charge to unlock it, since exercism can be used to teach and learn 

2. Is this really a blocking issue or are you behind a proxy and the cli didn't use it? Can you access x-api from the browser? 

3. If you really need to mimic the x-api on your own system, you can look at the erlang and Java journey tests. The setup a fake server to be able to mimic a student's workflow.

**Comment by kytrinyx** [comment]
We're going to be ditching x-api very soon (probably less than 6 weeks), so this is not a long-term problem, thankfully.

You should be able to grab the exercise files from https://github.com/exercism/csharp/tree/master/exercises (just try to avoid looking at the sample solution).

**Comment by andrewmp** [comment]
Thank you!
