### ISSUE TITLE
Exercism will not connect to Github account

### ISSUE THREAD

**Issue by Bbarrett** [exercism/exercism.io#3615]
I have installed everything via CL, but cannot get Exercism to connect to my Github account for some reason, what I get is the connection page, but the green "Authorize Exercism" button is grayed out and unclickable. I have tried everything I can think of.

**Comment by Bbarrett** [comment]
/Users/bbarrett/Desktop/Screen Shot 2017-08-28 at 8.42.55 AM.png

**Comment by Bbarrett** [comment]
Here it is:

**Comment by Bbarrett** [comment]
Photo

**Comment by Insti** [comment]
Check https://github.com/settings/applications and see if exercism.io is listed there.

**Comment by Bbarrett** [comment]
It is not . I have tried to add it, but maybe I am adding it in the wrong place? I tried adding it under the developer settings tab. Still nothing appears as being authorized on the section you linked to.

**Comment by Insti** [comment]
Where is the link you are clicking that takes you to the github authorize button? Can you link to it here?

**Comment by NobbZ** [comment]
@Bbarrett asked me to post the screenshot, because he isn't able to do so…

![screen shot 2017-08-28 at 8 42 55 am](https://user-images.githubusercontent.com/58951/29791340-d98ffb3e-8c3c-11e7-95d5-829a641c1d5b.png)

And the link that takes him there is the "Log in with Github" which you have on every page if logged out.

But since Image upload didn't work for him either, I have the suspicion that for some reason JavaScript for at least github is filtered or deactivated.

@Bbarrett 
Have you checked your JavaScript Settings if JavaScript is enabled for GitHub? Are you behind a proxy or firewall that may filter stuff out?

**Comment by Bbarrett** [comment]
@NoobZ yes, the JavaScript is enabled and I don't think I am behind any sort of proxy or firewall.

**Comment by NobbZ** [comment]
Please stop mentioning the wrong people ;) My name is NobbZ, only 1 "o", but 2 "b".

Just to be sure, have you tried the following:

1. Incognito mode
2. other browser
3. other PC
4. other network
5. other network and PC

**Comment by Bbarrett** [comment]
Ooops! Sorry about that. I have tried all of those except for other network and PC. I will give that a try tonight.

**Comment by Bbarrett** [comment]
Hey all, I figured it out. There was an issue with the pc I was using. Tried it at home on mine, all good now. I will close the issue.

**Comment by kytrinyx** [comment]
Glad you got it sorted @Bbarrett!
