### ISSUE TITLE
Problem with API key

### ISSUE THREAD

**Issue by bauerpm7** [exercism/exercism.io#3616]
I keep getting the following error when trying to fetch new problems even though I have configured the cli with my api key:

unable to fetch problems (HTTP: 401) - Please provide your Exercism.io API key

<img width="491" alt="screenshot 2017-08-30 06 48 11" src="https://user-images.githubusercontent.com/30079132/29869174-e41f26f6-8d4f-11e7-98a1-75ccdde9022b.png">
<img width="491" alt="screenshot 2017-08-30 06 54 20" src="https://user-images.githubusercontent.com/30079132/29869211-137c3132-8d50-11e7-80ec-a63a3ce61d2a.png">

**Comment by kytrinyx** [comment]
Wow, we did a particularly bad job of providing an accurate error message here!

Ok, so a couple things:

First—I'd recommend regenerating a new key, since this one has been shared publicly. You can do this on http://exercism.io/account/key

Next... the actual problem here (which the error message totally doesn't tell you) is that the track ID for C# is `csharp`, so the command needs to be `exercism fetch csharp`.

I'll make sure this error message gets fixed! Sorry about that, and thank you for reporting it. ✨
