### ISSUE TITLE
ColdFusion should possibly be renamed CFML

### ISSUE THREAD

**Issue by adamcameron** [exercism/exercism.io#3634]
CFML is the language; ColdFusion is a vendor implementation of it; Lucee is another. It looks to me like the exercises are language-oriented, not platform-oriented, so I think they are about CFML not ColdFusion per se.

I also suspect the instructions for downloading an engine and running the code would actually be running the code on Lucee not ColdFusion anyhow.

Back when there was only one significant vendor (ColdFusion) the terms ColdFusion and CFML were often used interchangeably, but this is not the case so much now, and it's straight out wrong to be describing it as ColdFusion if the engine is actually Lucee.

**Comment by kytrinyx** [comment]
> CFML is the language; ColdFusion is a vendor implementation of it; Lucee is another.

Thanks @adamcameron. I had no idea.

This isn't the first time we've had some ambiguity that we've had to straighten out.

We have a language track called Delphi. Originally we named it Pascal, but we happen to be using the Delphi implementation (which is provided by a specific vendor). I am happy to include more or less any language, and I think that it's important to name the track so as to avoid confusion about things like the above.

> It looks to me like the exercises are language-oriented, not platform-oriented, so I think they are about CFML not ColdFusion per se.

I think that is probably true.

> this is not the case so much now, and it's straight out wrong to be describing it as ColdFusion if the engine is actually Lucee.

Got it. Yeah, that makes sense.

The history for why it's called ColdFusion rather than anything else is a short and straight-forward story: TL;DR I didn't know.

A couple of years back someone asked for a ColdFusion track. I had a very short stint writing ColdFusion about a decade ago, but it was not long enough to have any context about variants, etc. I also hadn't put in place any process around starting new tracks (now I ask a few questions to help ferret out these sorts of nuances and bits of confusion before we actually kick everything off).

After the person requested the track, they never came back. So up until very recently we had a repository named ColdFusion with just some boilerplate in it, and a single pull request that wasn't ready to be merged.

That was the state of things when I asked for help on the wide internets, and @bdw429s came in and contributed a whole lot—bringing a dead track to life.

I think now is a great time to figure out the right naming. 🌷

**Comment by bdw429s** [comment]
So, here's my thoughts on this.  I had noticed this when I starting reviving the track but decided it largely didn't matter.  The truth is, the vast majority of the CF world (like, 99%) doesn't really place any distinction between CFML and ColdFusion.  CFML does, after all, stand for "**ColdFusion** Markup Language" so it's not like we're getting away from a trademark or anything.  

The open source communities of BlueDragon, Railo and now its fork, Lucee pushed the distinction to distance themselves from Macromedia/Adobe, even though the engines adhere to the base language spec (sort of like Ruby and jRuby) and the colloquial name for the majority of users has always been "ColdFusion".  To me, it's really more like the distinction between "tissues" and "kleenex".  It's technically different, but noone really cares because when you say "Give me a kleenex" you really just mean a soft thing to blow your nose on.  

So, in the end, I don't care too much what we call the track, but I think this is more of an academic discussion about technicalities and such.  For what it's worth, the readmes and docs I've written call out both Lucee and ColdFusion by name as separate engines and in the contribution guide, I've put that the exercises should enforce the basics of CF that apply to both engines.  Perhaps if it makes us feel better, we could put a little disclaimer that we're using the colloquial name of "ColdFusion" for the track even though there is more than one engine.  I think it's certainly more likely to be recognized by that name.  Every time I introduce myself as a "CFML Developer" people go, "HUH?". Then I say, I'm a "ColdFusion Developer" and they're like, "Oh yeah, why didn't you say so?  I did that back in 2000...".  :smile:

**Comment by adamcameron** [comment]
> Every time I introduce myself as a "CFML Developer" people go, "HUH?". Then I say, I'm a "ColdFusion Developer" and they're like, "Oh yeah, why didn't you say so? I did that back in 2000...".

Followed, no doubt, by "I thought it was dead", or "[insert derisive comment here]". That's what I get. Although I stick with the CFML label, and just explain it's the language the ColdFusion and other platforms use, but make a point of decoupling it from the ColdFusion brand.

I take your point re Kleenex / a tissue though.

I think the cost to be technically accurate here is minimal, and you possibly ought to actually give a crap about that (being technically accurate, I mean), esp given most of your efforts actually _aren't_ on the ColdFusion platform these days, are they Brad? It's mostly Lucee innit?

Also I think you'd possibly get more uptake on this if you lead with CFML (and your excellent description of it!), than blot its copybook from the outset by mentioning ColdFusion when you don't really need to. 

Bear in mind the target here is not existing CFML devs; it's _non_-CFML devs. I think the "ColdFusion" brand is toxic from most perspectives. In a way yer perhaps better off going with "CFML on Lucee", and sideline the mention of ColdFusion at all? Most people will have no opinion of Lucee at all, but that's better than most of the opinions of ColdFusion most people will have, which will be a blocker to entry from the outset.

Anyway, I've raised the issue. Do with it what you will.

**Comment by kytrinyx** [comment]
Based on the discussion here so far, I'm leaning towards renaming the track to CFML, since it's more accurate, and then starting the "blurb" with "ColdFusion Markup Language...". This is the same pattern we're using for LFE (Lisp-Flavoured Erlang) (see discussion here: https://github.com/exercism/lfe/pull/64)

> esp given most of your efforts actually aren't on the ColdFusion platform these days, are they Brad? It's mostly Lucee innit?

It sounds like you're taking a personal dig at Brad here. That's uncalled for and unacceptable. Please keep the discussion to CFML.

This discussion isn't about Brad's activities elsewhere, though all Exercism's tracks are likely to be colored by the maintainer's belief's, preferences, background, and skill sets.

This discussion, however, is about what to call the track, and—by extension—what is implied by the tooling and documentation. It sounds to me like the documentation allows for for choice of either engine.

> Followed, no doubt, by "I thought it was dead", or "[insert derisive comment here]". That's what I get. 

It pains me that this is true about _any_ language... and I see it happen all the time 😢 For what it's worth, my very brief stint in the language a decade ago was good fun.

I'm prepared to be wrong, so if you think I'm still missing some context/nuance, please speak up and help me understand better!

**Comment by adamcameron** [comment]
> It sounds like you're taking a personal dig at Brad here.

Not at all, I mean "not at all do I think that", and "not at all does it sound like that either". Just read the words, don't try to find "nuance".

I was just confirming what I'm pretty sure is true, and in no way was there any loading. Lucee is the newer, easier to integrate with, more dynamically-maintained, more collaborative and _open source_ CFML engine. And - bear in mind Brad and I have known each other a long time and have had beer with each other (well: I had the beer; he had a Coke) - just confirming what I knew to be historically correct back when we worked more closely with each other. I am mostly out of the CFML community now, so amn't necessarily up to speed with where he's at with stuff. Hence asking for the confirmation. Which is exactly how my wording reads.

This is not a confrontation: don't try to make it into one.

Cheers.

**Comment by bdw429s** [comment]
> I'm leaning towards renaming the track to CFML

@kytrinyx That's fine.  My only question (other than what needs to happen to change it) is how much this affects the repo names and CLI commands.  Updating the markdown files are very easy, but I do have a screencast I published last week and another that recorded and edited that I'll be publishing next week that demo how to use the ColdFusion/CFML track and how to contribute more exercises.  I need to know if I'll need to re-record these.  It's not horrible, just time consuming.  Here's the already-published one:
https://youtu.be/jxs0G9nMfxI
The second one covers the names of the repos and such that people need to have cloned.

**Comment by cybersonic** [comment]
CFML is the name of the language so to for that.

**Comment by cybersonic** [comment]
*go for*

**Comment by robertdmunn** [comment]
CFML FTW.

**Comment by cfchef** [comment]
I agree with naming it CFML.

**Comment by creayt** [comment]
I think even most to all ColdFusion ( Adobe ) developers have given up on ColdFusion ( Adobe ). I say name the track Lucee, because if you're trying to lure new developers in the best shot you have is sounding like something totally arbitrary that they *might* click on simply out of curiosity. A random, misspelled name like "Lucee" is more likely to pique some curiosity than YAA ( yet another acronym ).

**Comment by zspitzer** [comment]
CFML

**Comment by cfvonner** [comment]
CFML

**Comment by elpete** [comment]
I agree with CFML as the name.

**Comment by kytrinyx** [comment]
> My only question (other than what needs to happen to change it) is how much this affects the repo names and CLI commands.

@bdw429s An excellent question. In terms of renaming, we (well, I) need to:

- rename the repository
- run a couple of shell commands
- run a couple of database queries to update any existing submissions on the sate

And then, as you say, a few updates in markdown files.

So—not a big deal on this end.

> I do have a screencast I published last week and another that recorded and edited that I'll be publishing next week that demo how to use the ColdFusion/CFML track and how to contribute more exercises.

Ouch. Now this _is_ a lot of work. 

We're going to be launching v2 in ~mumble mumble~ not _too_ long (though we're likely talking months rather than weeks). How would you feel about the following?

1. Rename now
1. Wait to re-record until the new site is up
1. Add some text-comments on-screen to point out the new repo names where they've been changed.

Another option would be to wait to rename until we officially launch the new site.

A third option would be to not rename, though I think in the long term being more precise/correct is a win.

**Comment by bdw429s** [comment]
@kytrinyx I  asked on Twitter for some more opinions which brought the inflow of answers.  It seems like CFML is the clear winner.  I appreciate @creayt 's suggestion of going with a more obscure name for the purpose of tricking people with an existing CF bias into trying it, but I don't think that's the right move.  For what it's worth, I've let Adobe ColdFusion's marketing manager (Kishore) know about the CF track and they're excited to help promote it as a general CFML learning resource so I think it's best to just stick with the most generic name and let students learn about the commercial or FOSS engine that best suits them.  

I see you just posted a reply as I was typing.  I say let's rename sooner than later.  Ripping the bandaid off never gets any easier :)  The Github repo should actually do a redirect to the new name so that's ok. I'll just need to add a note about the CLI command being a bit different in the screencasts and all documentation I do going forward will be "CFML".

**Comment by kytrinyx** [comment]
@bdw429s This sounds like the best way forward.

Thanks so much to everyone for weighing in here, and thank you, Brad, for your efforts and enthusiasm for the CFML (!) track. 🌷

**Comment by adamcameron** [comment]
Thanks for following this up & all the input from everyone.
