### ISSUE TITLE
Person who like to check my answers 

### ISSUE THREAD

**Issue by rwobben** [exercism/exercism.io#3636]
Hello, 

I have a few challenges solved in c# but till now nobody wants to check if I did them the right way.
Maybe someone who wants to be a volunteer

**Comment by remcopeereboom** [comment]
@rwobben If you go to your solution, than on the page you should see a drop-down button with an option to "request help". Try flagging your solution that way and than adding a self-comment explaining the request for a review.

Not having enough reviewers is a common issue on exercism so that's something to be aware of. I'd offer to check them myself, but I don't have access to the C# branch (if someone from the C# could give me access that would be nice - my work consists mainly of programming C/C++/C# and matlab so...) and uploading solutions is something of a pain after you've seen and done them a million times.

Some general advice for while you wait... Get your hand on a copy of "Refactoring: Improving the Design of Existing Code". Learn to "squint test" (i.e. look at your code from a distance - see the code but don't read the code) and try to identify code smells. If you are not familiar enough with code smells to identify them, than at least try to identify patterns. Are all the colors together (= usually good)? Are all the methods nice and short (= usually good)? Finally, take a good hard look at the names. Does every name describe the object/method exactly and precisely? Be very critical!

**Comment by rwobben** [comment]
@remcopeereboom  Thanks, I hope you get very soon access to the c# branch

**Comment by rwobben** [comment]
@remcopeereboom  maybe a idea to put my solutions into a private github or bitbucket repo and work from there till you have access to the c# branch

**Comment by NobbZ** [comment]
It does not have to be private.

It does not even have to be a repository, you can give anyone the link to a submission you made, and everyone who knows that direct link can see and comment your solution.

**Comment by remcopeereboom** [comment]
@rwobben, Nobbz made the suggestion to paste a link, but you haven't responded. Is the issue ready to be closed?

**Comment by rwobben** [comment]
sorry 
I forget this subject

Links to my submissions : 

http://exercism.io/submissions/4c7cbe58943c466c81e21e710f718f1b
http://exercism.io/submissions/afa143d2b7e6489f9f58e142ac2b64f2
http://exercism.io/submissions/3c8d2ed86b1a43f0877822f55305be68
http://exercism.io/submissions/bbbd6c796b3f40478e832c71b87fb2f3
http://exercism.io/submissions/23412bfbf1654cb98a8656f013f82b62
http://exercism.io/submissions/3b162a8f7a154637a3c357aab4dce81e
http://exercism.io/submissions/3b162a8f7a154637a3c357aab4dce81e
http://exercism.io/submissions/8559595956ed47cba305abb33eef791a
http://exercism.io/submissions/8559595956ed47cba305abb33eef791a

Roelof

**Comment by remcopeereboom** [comment]
@rwobben 
I've been giving feedback and you seem to be getting some from others as well. Can this issue be closed?

**Comment by rwobben** [comment]
@remcopeereboom  thanks for the feedback.
