### ISSUE TITLE
--dir=~/exercism  interferes with cli command exercism

### ISSUE THREAD

**Issue by DeviatedMind** [exercism/exercism.io#3649]
--dir=YOUR_EXERCISM_PATH
When I press tab after "exer" it brings "exercism" instead of "exercism "
so I have to press space to use the command.
If you change the default folder to sth like --dir=~/exercism-main the problem would be solved.
I did it for myself.

**Comment by NobbZ** [comment]
Can you elaborate?

What exactly do you type? It reads as if you were typing `--dir=YOUR_EXERCISM_PATH exer`, which makes not much sense to me…

**Comment by DeviatedMind** [comment]
no, I simply typed "exer" then pressed tab button.
Normally the command would become "exercism " with the space at the end. So I can type the rest of the command.
But with exercism folder in my home directory, pressing tab after "exer" brought "exercism" without space at the end. So I had to manually press space each time I wanted to use exercism cli command.

**Comment by NobbZ** [comment]
This is expected behaviour in most shells, also when you rename the folder to something that still begins with `exercism` this behaviour does not change at all, since your shell will expand until there is an ambiguity.

But to be honest. in about 99.99% of the time (if not more) you are somewhere inside of the exercism workspace when using the CLI, there the exercism folder from your HOME directory doesn't interfere anymore.

Last but not least, since I use exercism quite a lot, I've added some aliases:

```bash
alias exs='exercism submit'
alias exf='exercism fetch'
alias exdl='exercism download'
alias exws='cd ~/exercism'
```

**Comment by DeviatedMind** [comment]
Your aliases are very nice, thanks.
I agree that most of the time we are inside exercism folder, yet for beginners it might get confusing.
About the problem however, when I changed the name to "exercism-main" it was solved. I don't know why yet.

**Comment by NobbZ** [comment]
Maybe your shell treats dash separated names as 2 tokens, since many programs have a basename (e.g. `git`) and give you the ability to add further subcommands by calling `git-yoursubcommand` if they do not know the subcommand natively. It maybe that your completion does assume exactly this behaviour.

My shell doesn't consider folders or files in the current working dir at all when completing the command unless I explicitely prefix with `./`.

So as you can see, systems behave differently based on their configuration, and we have to assume, that a user knows at least enough to see when he needs to insert a space or not.
