### ISSUE TITLE
Make interesting solutions easy to discover.

### ISSUE THREAD

**Issue by Josef-Vonasek** [exercism/exercism.io#3660]
When I write a solution to problem, I naturally want to look at other solutions, which are better in some way than mine, to learn something new. Right now it is very hard to find these, because all solutions are just presented as a list, sorted by date of submission. I would like to be able to sort them with few criteria on mind: 

* robustness (proper error and corner case handling)
* elegancy (number of lines)
* performance
* originality

**Comment by NobbZ** [comment]
Rank what?

Submissions? Feedback? Tracks?

I'm not a fan of this proposal. Also @kytrinyx has told about her concerns regarding gamification some times, and she is not a friend of it as well.

Also the current version of exercism is at its end. Behind the scenes a new version is developed and tested which in my opinion makes the desire for gamification obselete, as most gamification elements that were proposed so far were to increase amount (not quality) of feedback.

**Comment by Josef-Vonasek** [comment]
It's not about gamification. Its about learning something new from more experienced programmers.

Current system makes it very hard.

That's the sole reason of this proposal, if you know a better system, that fulfills this goal, I will be happy to use it.

**Comment by NobbZ** [comment]
In nextercism (the in dev version) there any solution that is visible to the public (and has been submitted after the relaunch) has been mentored before. So every solution that is visible then, holds some quality criteria.

**Comment by kytrinyx** [comment]
In the v2 of Exercism we will be adding more things that you can filter on, and we will be looking at other ways of making the available solutions easier to explore.

I'm going to go ahead and close this one, since it's already in the works. That said, I don't know that we will be able to include things like robustness and performance. Robustness requires that a human triages it as being robust, and performance requires that we run all the solutions in 40+ programming languages on machines with similar/known capabilities so that they can be compared.

If you'd like to discuss the topic for v2, please do so here: https://github.com/exercism/v2-feedback/issues/99
