### ISSUE TITLE
How does the CLI get exercises?

### ISSUE THREAD

**Issue by wolf99** [exercism/exercism.io#3671]
Not an issue as such. I'm looking for info on how the CLI gets exercises. I'm not a web, Go or Ruby dev so looking through code to find this has been pretty confusing to date. Is there documentation on this?

Essentially I wanted to determine how hard it might be to use git sub-modules for exercise dependencies - but I'm not sure how things get from a track's github repo, to the exercism app and to the CLI.

Thanks for any info!

**Comment by Insti** [comment]
For version 1:

All tracks are imported as git submodules to https://github.com/exercism/trackler.
This is then used by https://github.com/exercism/x-api to serve the relevant files.

Have a look though the documentation in those repositories for more clues.

https://github.com/exercism/exercism.io also has some api endpoints which deal with solutions.

All this is probably different in V2, but I'm not currently up-to-speed with what is happening there.

**Comment by wolf99** [comment]
Thanks @Insti. It would be good to know, if anyone has that info, if this changes for nextercism.

**Comment by Insti** [comment]
Can you explain what you mean by: 

> use git sub-modules for exercise dependencies

**Comment by wolf99** [comment]
For example, in the C track each exercise includes a directory holding the Unity testing framework. I wondered if it is possible/worthwhile/interesting to instead replace the directory with a submodule in such a way that a student still gets the framework included in the content downloaded for each exercise

**Comment by NobbZ** [comment]
We explored symlinks for such stuff, but they broke the system. I can't remember exactly what the problem was, but it boiled down to "doesn't work on windows", (I'm not sure though if this was for students or maintainers).

Git submodules or a similar thing have not been explored yet, but those either require the server to resolve them or require the student to install and use an additional tool (`git`). Therefore I'm not sure if we should do it.

**Comment by kytrinyx** [comment]
> it boiled down to "doesn't work on windows"

This is my recollection as well.

@wolf99 Is the Unity testing framework currently included once per exercise?

**Comment by wolf99** [comment]
@kytrinyx yes, each exercise contains a `/test/vendor/` directory that holds Unity. In this case Unity only consists of 3 files. However I realised that there is the possibility to introduce inconsistencies where exercises that are created at different times will use different releases of Unity.

Using a given release, and updating that, may be more consistent and easier using sub-modules. A simple fix for half the benefit is to document the specific version of each dependency. This does not make updating that at some future point (say, to take advantage of bug-fixes etc)  any easier though.

This is a pretty minor concern AFAIK - I don't think there has been any issue with the current method so far. Might be interesting to know if other tracks have a structure that might benefit from some kind of abstraction for 3rd party dependencies and if they have problems with the current method?

**Comment by kytrinyx** [comment]
For v2 of exercism we are planning on introducing a "prepare" step when people get started with a track, where we download dependencies that all the exercises use. We'll be able to store the files just once (well, once when people start, and we'll also serve a header that says the most recent update timestamp of the dependencies so that we can update them if they've been changed).
