### ISSUE TITLE
Updating outdated tests.

### ISSUE THREAD

**Issue by jaccarmac** [exercism/exercism.io#3681]
[This question](https://github.com/exercism/exercism.io/issues/2398#issuecomment-255642611) was asked a while back, and it's one I have as well, since I recently ran into the issue myself. Is there any way to update the test suite/specification of a problem so that one can keep getting feedback on a solution as tests change, like `bob` in the Go track did a couple of days ago?

See http://exercism.io/submissions/fec708cd1c624819b1b80d958307d4dc

**Comment by kytrinyx** [comment]
@jaccarmac sorry it's taken me so long to respond to this!

At the moment, the way to update a test suite is a bit hacky—you delete the test file and call `exercism fetch` for the exercise again.

I don't anticipate changing it even though I'm not super happy with it, since we're changing how things work in the new design ([v2](https://github.com/exercism/v2-feedback/blob/master/README.md)) and this should not pose a problem.

Thanks for asking!

I'm going to go ahead and close this, but feel free to ask more either here or in a new issue. 🌻

**Comment by jaccarmac** [comment]
Thank you!
