### ISSUE TITLE
When putting code in the comment section via markdown, the line number always starts with '1'

### ISSUE THREAD

**Issue by Ornataweaver** [exercism/exercism.io#3692]
Or maybe I don't know how to change it.
For example in http://exercism.io/submissions/0b5833b9062741f39b6bac675a6805fd in my comment,
When I click on '1' link, it highlights the first line of mihas1984's code. instead I want it to show '2' and highlight line 2 to 7.
I read markdown documentations, yet I couldn't find anyway to do this.

**Comment by Ornataweaver** [comment]
"As you may noticed in Markdown Cheatsheet, GitHub does not show line numbers in code blocks."
from
https://stackoverflow.com/questions/36122803/how-to-display-line-number-using-github-markdown-code

**Comment by kytrinyx** [comment]
This is expected, as the code block in the comment is not in any way connected to the code example. It's a stand-alone code block, and as such will always start at `1`.

The question about whether or not GitHub shows line numbers does not apply, since we don't use GitHub to show code on the Exercism website.
