### ISSUE TITLE
linked-list requirements incomplete

### ISSUE THREAD

**Issue by bennypowers** [exercism/exercism.io#3697]
It's possible to pass the linked-list tests for JS/ES like so:

```js
const List = Array;
List.prototype.count = function () { return this.length; };
List.prototype.delete = function (value) {
  return this.indexOf(value) !== -1
    ? this.splice(this.indexOf(value), 1)
    : this;
};

export default List;
```

It seems to me that this object doesn't satisfy the true definition of linked-list, although it does pass the tests.

Please correct me if I'm wrong.

**Comment by NobbZ** [comment]
cc @exercism/javascript

**Comment by joelwallis** [comment]
@bennypowers thanks for catching it and bringing to our attention.

@exercism/javascript I'm believe the reason it passes the tests is because the naming chosen for the methods are pretty much the same used in `Array`. If it really is a problem we should adopt different names - like `List#append()` instead of `List#push()`, etc. What you think?

**Comment by bennypowers** [comment]
I would pull the same shtick in that case
```js
List.prototype.append = Array.prototype.push
```
etc

**Comment by matthewmorgan** [comment]
We should move this issue to the JavaScript track.

I've copied the original post to https://github.com/exercism/javascript/issues/480, let's continue the discussion there.
