### ISSUE TITLE
Suggestion: Mark Submissions That Pass All Tests

### ISSUE THREAD

**Issue by getchar** [exercism/exercism.io#3761]
If users are stuck on an exercise, you suggest that they submit the nonworking code and look through other submissions for ideas on how to proceed. The problem is it's hard to tell at a glance (particularly if you're stuck on the exercise) whether another implementation will actually work. Arguably, that process of discovery might be valuable in itself, but I think that the excessive difficulty of this approach is more of a barrier to learning than the presumed rewards are an aid. 

So why not just put a checkmark next to submissions that pass all tests, along with maybe some stats about execution time and a breakdown of tests passed and failed?

I did look through the specs for v2, and there were some hints in there that something like this might be on the way. If so, sorry for the redundancy. I love the program otherwise and I'm learning a lot. Thanks for everything!

**Comment by kytrinyx** [comment]
Thanks, @getchar!

> So why not just put a checkmark next to submissions that pass all tests, along with maybe some stats about execution time and a breakdown of tests passed and failed?

Since we don't run anyone's code, we have no way of knowing what passes the tests. Likewise since we don't run any code, we don't have a standardized way of doing benchmarks—you'd have to download two solutions and run the benchmarks locally to compare.

There has been some discussion about similar things before (see #2312, #2803, #1710, #3127, #3750, #3610, and https://github.com/exercism/discussions/issues/121).

I'm going to go ahead and close this, since it's not on our roadmap to implement—that said, if you have any ideas around how to do this in a scalable manner across 45+ programming languages, we'd love to hear about it!
