### ISSUE TITLE
GDPR

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#3782]
How does exercism in its current or future version comply to [GDPR](https://www.eugdpr.org/)?

PS: Sorry for beeing devils advocate…

**Comment by kytrinyx** [comment]
>  Sorry for beeing devils advocate…

You're not being devil's advocate. We've discussed this thoroughly in order to ensure that we are compliant.

@iHiD has done the deep dive on all the details, but the TL;DR for Exercism right now is:

v1 doesn't store anything that isn't already public on your GitHub profile, or that you explicitly submit as part of the process of participating. And we never email anyone in v1.

v2 asks for permission to email specific things (for example notifications related to your activity on the site).

**Comment by iHiD** [comment]
@NobbZ Thanks for thinking about this. The new site explicitly asks for permissions on first login. If you still have thoughts/concerns once you've been through that flow, please let me know :)
