### ISSUE TITLE
Malformed BASH output in Walkthrough

### ISSUE THREAD

**Issue by PTrottier** [exercism/exercism.io#3803]
When checking for the existence of `~/bin` is in the path, the provided BASH script is malformed, see the image below:

Pre-Walkthrough
![screenshot_2018-07-13 exercism](https://user-images.githubusercontent.com/31802216/42717008-5700d798-86cc-11e8-9a7b-b0285f45849c.png)
Step for checking path
![screenshot_2018-07-13 exercism 1](https://user-images.githubusercontent.com/31802216/42717009-570ef436-86cc-11e8-86ac-0260e638f1cc.png)
Malformed BASH
![screenshot_2018-07-13 exercism 2](https://user-images.githubusercontent.com/31802216/42717027-751daea4-86cc-11e8-9b9d-e4287f3c30fd.png)

I believe this is the code that displays the script: https://github.com/exercism/website-copy/blob/master/walkthrough/index.html#L156

Thanks for the wonderful project!

**Comment by NobbZ** [comment]
Can you please tell the exact clicks you have done in the walkthrough, as I am not even able to find the screen…

**Comment by PTrottier** [comment]
Path: Begin Walk-Through>Linux>Yes>Continue>Yes

**Comment by nickborromeo** [comment]
I looked into this a bit and I found that the website is rendering 

```
[[ ":$PATH:" == *":$HOME/bin:"* ]]
``` 
from [exercism/website-copy](https://github.com/exercism/website-copy/blob/9a475ae0d2c33035339dc1901fca344968b57842/walkthrough/index.html#L156) as 

```
<a href="javascript:void(0)" data-passage=" &quot;:$PATH:&quot; == *&quot;:$HOME/bin:&quot;*"> ":$PATH:" == *":$HOME/bin:"* </a>
```

I see that we call `html_safe` on the text but still it renders that way

[my/solutions/walkthrough_modal.html.haml](https://github.com/exercism/website/blob/7491f8688753a87600cdb2bd0e3795dcb97ef15d/app/views/my/solutions/walkthrough_modal.html.haml#L1-L2)
```
#cli-walkthrough
  = @walkthrough.html_safe
```

---

I tried to see if I could reproduce this locally but I am having trouble getting passed the sign in and login pages.

**Login** 
When I try to authenticate using GitHub I get this in the logs
```bash
I, [2018-07-28T12:47:15.755196 #41089]  INFO -- omniauth: (github) Callback phase initiated.
E, [2018-07-28T12:47:15.755860 #41089] ERROR -- omniauth: (github) Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected
```

**Sign Up**
I tried signing up, but I used a dummy email address. I am not sure if I need to use a real one because it seems like the address needs to be verified.

**Comment by iHiD** [comment]
This is triaged to exercism/interactive-cli-walkthrough#31
