### ISSUE TITLE
Exercise time label

### ISSUE THREAD

**Issue by nicolechalmers** [exercism/exercism.io#3804]
From what I can see the time stamps on the exercises all say "MEDIUM" - if this is right I wonder if we should just remove the label?

<img width="1101" alt="screen shot 2018-07-13 at 23 39 05" src="https://user-images.githubusercontent.com/5421823/42716954-f7062ca6-86f5-11e8-8a7e-57314c92fe43.png">

**Comment by kytrinyx** [comment]
Yes, I think that we should remove it until we have something useful to put there.

**Comment by nickborromeo** [comment]
I can take this on, unfortunately I cannot get my local dev environment working 😢 

I run into the following when trying to login or sign up.

**Login** 
When I try to authenticate using GitHub I get this in the logs
```bash
I, [2018-07-28T12:47:15.755196 #41089]  INFO -- omniauth: (github) Callback phase initiated.
E, [2018-07-28T12:47:15.755860 #41089] ERROR -- omniauth: (github) Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected
```

**Sign Up**
I tried signing up, but I used a dummy email address. I am not sure if I need to use a real one because it seems like the address needs to be verified. 

Any thoughts or tips that I should look into? I am **not** using the Docker instance for local.

**Comment by iHiD** [comment]
> I can take this on,

💙 

> unfortunately I cannot get my local dev environment working 😢

😢

> When I try to authenticate using GitHub I get this in the logs

I've just updated the oauth app. As long as you're on http://lvh.me:3000/ it **should** work now.

> I tried signing up, but I used a dummy email address. 

If you run `User.find_by_email("xxx").confirm` in a console, that should work.

Let me know :)

**Comment by nickborromeo** [comment]
@iHiD It got it working 🎉thanks for the update!
