### ISSUE TITLE
"Independant mode" should clearly warn about the fact that you can not switch back to "normal"

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#3810]
When one chooses the independant mode (either from the beginning or changing from normal) there is no word of warning that you can not switch back to normal.

If you then are in independant, then there is no button to switch modes, but at least one user managed to use URL-manipulation to change the mode backk to normal but he lost all his progress in that track. This manipulation was used in a slack-thread which I can't find right now.

Therefore I suggest to create a big warning on entering independant mode and an aditional confirmation dialog.

**Comment by bdf74** [comment]
I posted this just now, then I noticed your post and closed my issue. I really hope it's not irreversible: that would be a HUGE mistake, as there's no warning. Also, as a user, I would like to try something before making a decision.

**Comment by Zialus** [comment]
There's no option to "leave track" either, when you change to independent mode.

**Comment by Ornataweaver** [comment]
I think it's common sense to expect a turn-back button where it is possible.

**Comment by Ornataweaver** [comment]
GitHub is Introducing the dashboard. It says:
Opt-in by clicking below. You can opt out of these changes at any time from your dashboard.
#common-sense

**Comment by NobbZ** [comment]
> I think it's common sense to expect a turn-back button where it is possible.

You already gave the correct condition. **If** it is possible. And if this is possible in a way that does not overwhelm mentors with workload is under internal discussion.

Please be aware about the fact that even though the website, the tracks, the CLI tool are open source, the product itself is not. There is a small team of product designers that are actually those who decide what gets added and what the flow should be.

So instead of spamming every issue that is remotely related to your problem and even ref linking between them doesn't bring you or other participants any further.

If you have something valuable to add, please do so, but if it is just a disguised "I want this too", then please use reactions on the original ticket to show your support.

But please don't get me wrong, this is only my perception of the last ~12h which I went through by email before I had my coffee. But even after a coffee my perceiption is not much better.

Please simply stay patient.

**Comment by Ornataweaver** [comment]
• I really like to contribute, I don't know of anyway other than having conversations in issues.
• About the mentors part, I want the map of the MENTOR MODE, I don't wanna take mentors time.
• I'm linking the issues that I think are related: I want people to easily find this hub and to focus the conversation so there comes good results out of it.
• I wanna create the #IDEAsPlatform, and UserStoryHub.com, so what you see as spamming, I see it as Brainstorming; It's my art, my work, my love. I'll happily prune it if you have any suggestions.

You see, the internet is a brain. It lacks a mind, you tell me to stay patient. What should I wait for? When there is no plan.
I'm under a lot of pressure from the #IDEAsPlatform, it's a live meme in my head and it's eating me out. It needs to get out. Help me if you can.

**Comment by Ornataweaver** [comment]
If I sound strange, it's because of the pressure, I'm giving birth to something totally bigger than myself.

**Comment by NobbZ** [comment]
I'm not sure how your platform is related to the shape of exercism, so I do not understand why you are under pressure and especially why you have to push it on exercism.

Also, as I said, even if it seems as if there is no plan right now, it has been said that the problem is under internal discussion.

Exercism (as it is now) is a very young platform, and even though it has been thought through much better than the last one, we still need to cut the diamond, but as long as everyone keeps calm, there will be no inlets or cracks on it.

If though, you want to tell me, that you want to create some platform unrelated to exercism, after you have learned through exercism, then you should probably rethink your learning strategy.

Perhaps even rethink your hiring policies.

**Comment by kytrinyx** [comment]
> I think it's common sense to expect a turn-back button where it is possible.

@Ornataweaver we have plans to implement the turn-back option. That is not what this issue is about. This issue is about making a warning that is sufficiently clear _until_ we have implemented the turn-back option.

**Comment by kytrinyx** [comment]
> There's no option to "leave track" either, when you change to independent mode.

@Zialus Please see https://github.com/exercism/exercism.io/issues/4065 which is tracking this issue.

**Comment by kytrinyx** [comment]
> GitHub is Introducing the dashboard. It says:
> Opt-in by clicking below. You can opt out of these changes at any time from your dashboard.
> #common-sense

@Ornataweaver now you are insulting us, which is unacceptable. We have already stated in a number of places that we are planning on implementing the possibility of switching back, once we have worked out how to do that without overloading the mentors.

> I really like to contribute, I don't know of anyway other than having conversations in issues.

@Ornataweaver Let me make some suggestions, which @NobbZ has already made, but which bear repeating:

- When adding a comment to an issue, make sure that your comment is about the issue, and not a separate issue.
- When adding a comment to an issue, ensure that you are adding something new to the issue. If you are re-iterating something which has already been stated, then it is not a contribution to the conversation.

Additionally, I would add:

If you do have something relevant to contribute which has not yet been added to the conversation, then consider:
- what is the main point that you are trying to make
- what context is necessary for others to know, in order to understand your point
and then put together a single response that outlines these things for the reader.

In many cases you have posted a series of comments on an issue, each with a partial phrase, an at-mention, or a link to some other issue.

As the reader of these comments, we cannot know why you are linking or mentioning, though sometimes we are able to puzzle it out. Puzzling out takes time and effort. If you consistently add a burden of understanding to readers when you participate in a conversation, that is the opposite of contributing.

If you continue to make more work for the maintainers and contributors to Exercism, then we will remove your privileges to post to this organization.

**Comment by Ornataweaver** [comment]
I'm looking for people, it is a meme in my mind, so it's infectious, and it's finding hosts. Like a virus.

**Comment by Ornataweaver** [comment]
I truly don't mean to insult you guys, I have the most respect for you. I'll be silent for now until I understand what is the matter with my communications skill on GitHub.
Thank you for your time.

**Comment by iHiD** [comment]
@Ornataweaver Thanks for saying that. I think the thing to do before posting is to try and make sure you are giving some **new** information that is **actionable** and clear. And posting multiple comments in a row isn't helpful. While we wish you luck in your own projects, this also isn't the place to post about them. We have a huge amount of issues we are working through and anything that is a distraction here is unhelpful. I would advise reading again what @kytrinyx wrote as she gave very clear guidance on how to contribute best.

I'm locking this thread now.  Thanks for wanting to help.
