### ISSUE TITLE
Mobile device viewport is not correct

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3928]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/155._
_Originally posted by @ErikSchierboom._

#

When viewing the mentorcism website on a mobile device (iPhone 6S), the display is not correct:

![image](https://user-images.githubusercontent.com/135246/41808657-1b06f452-76e1-11e8-9e1b-f5a15198f3ba.png)

It appears to be the case that the viewport is not correct, leading to the mobile browser only displaying a part of the website.

**Comment by filipewl** [comment]
I also noticed this and initially thought the problem was with [viewport meta tag](https://github.com/exercism/website/blob/cbedb3b9d3ea8e9aa522f8c18addd875937d59e3/app/views/layouts/_meta_tags.html.haml#L4) as well. But upon further investigation, the real problem seems to be some specific CSS properties setting the width to 1200px [here](https://github.com/exercism/website/blob/cbedb3b9d3ea8e9aa522f8c18addd875937d59e3/app/assets/stylesheets/layout.scss#L6) and [here](https://github.com/exercism/website/blob/cbedb3b9d3ea8e9aa522f8c18addd875937d59e3/app/assets/stylesheets/defaults.scss#L16). The [image with the person coding](https://github.com/exercism/website/blob/cbedb3b9d3ea8e9aa522f8c18addd875937d59e3/app/assets/stylesheets/widgets/code-person.scss#L3) also gets in the way.

After some CSS modifications, with media queries targeting 480px max-width, I was able to get the landing page to look like this:

![localhost_3000_ iphone 6_7_8](https://user-images.githubusercontent.com/381395/42920372-b2d34bd6-8aec-11e8-835b-44f77b8b9f42.png)

It's still a WIP, but it could come handy later.

**Comment by ErikSchierboom** [comment]
That's some great work! IIRC there will be an attempt to make everything mobile-friendly in a couple of months.

**Comment by iHiD** [comment]
This is being handled as part of our responsive update.
