### ISSUE TITLE
In independent mode you can't leave a track! 

### ISSUE THREAD

**Issue by Ornataweaver** [exercism/exercism.io#4027]

**Comment by Ornataweaver** [comment]
You can neither switch to MENTOR MODE.

**Comment by Ornataweaver** [comment]
https://github.com/exercism/exercism.io/issues/3985

**Comment by Ornataweaver** [comment]
I'll keep on trying to hack the site UI to find dead ends. ;)

**Comment by kytrinyx** [comment]
@Ornataweaver Thank you for wanting to help.

Please understand that Exercism is a work in progress. We are quite aware that there are numerous rough edges and incomplete features, and--if you take a moment to read through the open issues--you will note that we are planning on completing this.

When you find incomplete or missing features, please open issues that carefully explain the value of them in one clear post at the top. You can also add your observations to existing open issues if you have noticed things that are not mentioned there, but please avoid "I want this too" style comments.

Also, please note that the style of writing you are using (exclamation marks, multiple comments, etc) is coming across as quite antagonistic and unpleasant right now. If you do find something that is not covered in an open issue, I would appreciate it if you reported it with the assumption that we might very well know about it, and have not prioritized it yet. Rather than telling us emphatically that we're wrong, I'd recommend asking if it's intentional, and what the plan is.

Can I ask that you also please review our code of conduct at https://exercism.io/code-of-conduct

Thank you.

**Comment by Ornataweaver** [comment]
I'm really sorry about being emphatic. I'm trying to communicate with people, I didn't mean to have a demeaning tone.
Thank you for telling me.

**Comment by Ornataweaver** [comment]
"--if you take a moment to read through the open issues--you will note that we are planning on completing this."
I couldn't find this problem in issues.
So I opened it in a nice description:
https://github.com/exercism/exercism.io/issues/4065
Should I close that? If so, could you refer this to the related issue?

**Comment by Ornataweaver** [comment]
By the way check https://github.com/exercism/exercism.io/issues/3810. That's why I was surprised.

**Comment by Ornataweaver** [comment]
They say:
"Independant mode" should clearly warn about the fact that you can not switch back to "normal"
Other people are antagonistic and unpleasant by saying "should clearly warn", maybe it's common sense to expect a turn-back button.

**Comment by Ornataweaver** [comment]
I really like this statement of yours: "Rather than telling us emphatically that we're wrong, I'd recommend asking if it's intentional, and what the plan is."
I expect the person intelligent enough to make that statement, to have the modesty to doubt their plan if too many people find it unpleasant.

**Comment by Ornataweaver** [comment]
Thank you for caring.

**Comment by Ornataweaver** [comment]
@Zialus

**Comment by kytrinyx** [comment]
@Ornataweaver You are right, this particular issue (leaving a track in independent mode) was not tracked. Thank you for opening the issue, I have edited it for clarity.

For the rest of this conversation, I'm trying to understand what you're saying, and struggling to follow.

It sounds like you think that we are not accepting feedback. I am unable to figure out why that is the case, since we have quite clearly been responding to feedback and adjusting our plan based on it.

There are three things that are relevant here, which you may not be aware of:

1. We have a lot of plans for changes which we have not yet been able to implement.
2. There are things that we purposefully left unfinished because we felt that we needed community feedback before we could complete them.
3. There are things that we made guesses about, and are discovering that we were wrong.

We are constantly iterating on this.
