### ISSUE TITLE
🆘 Windows sub-system for linux issue

### ISSUE THREAD

**Issue by conormcg13** [exercism/exercism.io#4036]
Following error when I try to configure token:

runtime: epollwait on fd 4 failed with 38
fatal error: runtime: netpoll failed

As mentioned in the title I am using WSL and I believe this is what causes the issue. Is there any compromises I can do or exercism that sorts this issue. Ideally I'd prefer to use WSL with exercism rather than windows.

**Comment by NobbZ** [comment]
How did you install the CLI?

**Comment by conormcg13** [comment]
I had exercism prior to the new update so I'm pretty sure I just did an upgrade. I could try doing a fresh install and see what happens.

**Comment by NobbZ** [comment]
Even for the fresh install you didn't answer how you did it. Which tarball did you download? Where did you extract it to? What is the output of `which exercism`?

**Comment by NobbZ** [comment]
PS: WSL is a bit like Ubuntu but not perfectly. It may happen that neither the linux nor the windows binaries are compatible. In that case, please try a build from source and check if that is working.

**Comment by conormcg13** [comment]
I downloaded the exercism-linux-64bit file and 'which exercism' outputs the exercism executable in the bin directory I created in my home directory. I'm assuming its the cli repository that I should build from source. I haven't much experience building from source, whats the usual steps? Do I need a Go compiler and build it and if so is there not additional things I need to do to run it in bash?

**Comment by conormcg13** [comment]
I ran build-all in the bin directory and I hadn't 'go' installed so I installed it but no luck, got an error but I don't want to mention it because it may be getting sidetracked and the fact I haven't much experience building things. The output from the build-all mentions 386 and arm64 architectures as well as windows. I'm assuming WSL is confusing the installer.

**Comment by NobbZ** [comment]
Since installation from source is not the recommended way of installing the CLI, the tooling directly in the repository is aimed at cutting proper releases, not for ad-hoc builds.

The instructions about how to actually build the CLI from source are hidden in the [`CONTRIBUTING.md`](https://github.com/exercism/cli/blob/master/CONTRIBUTING.md), as usually contribution is the only "cause" for building from source.

In your case we need to try a guided compilation.

But as I am unsure what version of Go is available in the WSL, we need to check that one first by calling `go version`. If it does not print 1.9 at least, you are out of luck. You'll need to change your platform then (Mac, Dualbooted Linux, VirtualBoxed Linux, native Windows).

If you meet the build requirements, you can do the following (I hope I do not forget any steps)

1. `mkdir -p $(go env GOPATH)/src/github.com/exercism/cli/` to create the folder where the sourcecode lives. Go enforces a certain structure.
2. `git clone https://github.com/exercism/cli.git $(go env GOPATH)/src/github.com/exercism/cli/` to clone the repository.
3. `cd $(go env GOPATH)/src/github.com/exercism/cli/` to get there
4. `git checkout v3.0.5` to get the latest released version and not a possibly broken development snapshot
5. `go get ./exercism` to fetch the dependencies (the leading `.` is important!)
6. `go install ./exercism` to compile and install to `$(go env GOPATH)/bin/exercism`.
7. `$(go env GOPATH)/bin/exercism version` to check if it is the correct one (v3.0.5) and if it works now.

If you see a version number printed out in the last step copy that binary wherever you like it in your `$PATH`.

If you encounter any errors during this process, please open a ticket at https://github.com/exercism/cli and post a stripped-to-the-important-bits-transcript of the commands run and their output.

I won't have acces to a WSL enabled host before next week, so I can not check that soon, but I hope someone from the @exercism/cli team is able to check into such an issue much earlier than me if it gets reported over there.

**Comment by conormcg13** [comment]
Thanks very much for this, I will try this today and report back.

**Comment by conormcg13** [comment]
I checked which go version I had installed and the output is:
`go version xgcc (Ubuntu 4.9.3-0ubuntu4) 4.9.3 linux/amd64`

I removed this and try to install 1.9.1 but ubuntu complains I need the package gccgo which then installs that version above. I did go through your steps but the get and install commands got errors. 

I think to give you less of a headache with this, I can compromise and use windows in the meantime until you get your hands on wsl to see what is happening. Thanks again, much appreciated

**Comment by NobbZ** [comment]
That go version string is not as I am used to it…

Especially I can't explain the 4.9.3 to me. Go is only at 1.10 right now (latest release).

But is there any special reason you do not use a VM? Depending on the track you choose that will be so much easier than Windows. And even WSL might have its problems, as it is *not* windows **and** *not* linux.

**Comment by NobbZ** [comment]
PS: To help a bit with debugging, could you please tell us the output of `go env GOOS` and `go env GOARCH` in the WSL? That might probably help to debug everrything a bit faster.

**Comment by conormcg13** [comment]
go env GOOS:
`linux`
go env GOARCH:
`amd64`

Well I use exercism at work as well but we work in a windows environment and I assumed I would have issues with the network but mostly because I'm working with visual studio and using a VM just for the source control (how does the VM access my windows directories, I'm guessing there is a way) seemed impractical and WSL felt the obvious choice to me.

**Comment by NobbZ** [comment]
Also I have to say, it works for me:

This is from a WSL host on a co-workers computer:

```plain
$ wget https://github.com/exercism/cli/releases/download/v3.0.5/exercism-linux-64bit.tgz
[... snip ...]
$ tar xvzf exercism-linux-64bit.tgz
[... snip ...]
$ ls
exercism  exercism-linux-64bit.tgz  shell
$ ./exercism version
exercism version 3.0.5
$ lsb_release --all
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04 LTS
Release:        18.04
Codename:       bionic
```

**Comment by conormcg13** [comment]
Can you configure your token and download exercises? Also worth noting that my WSL is on ubuntu 14.04.5 LTS

**Comment by NobbZ** [comment]
As 14.04 is close to its EOL and there are already 2 LTS released since then, you should probably upgrade that installation. The kernel used in that Ubuntu version **has** reached its end of life 2 weeks ago.

I do assume, that due to its age, you will have problems running exercism on a native installation of ubuntu 14.whatever. Also you'll probably have massive problems due to the age of the tools needed by your language.

Even though LTS gets 5 years support, you shouldn't actually use one longer than until the next LTS happens.

**Comment by NobbZ** [comment]
PS: I just checked if I am able to configure my token and it was a success.

**Comment by conormcg13** [comment]
I'll try upgrade it but I have no control of my windows updates nor do I have access to microsoft store. Previously I just ran bash command in cmd to install ubuntu. The windows version is 1607 and my particular build may not support 18.04 but that's just my guess. I'll try upgrade in the meantime through cmd.

**Comment by NobbZ** [comment]
> mostly because I'm working with visual studio

Then stick to windows.

I was often told, that you should not access WSL stuff from windows and the other way round, as it will cause you a lot of trouble.

**Comment by NobbZ** [comment]
> The windows version is 1607

End of life of that version of windows ended April 10th of this year. Urge your management to update as soon as possible! I do assume though, you are not using an Enterprise or Education Edition. But even then, EOL will be reached in October.

Some arguments that should bring you in a better position:

https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet

**Comment by conormcg13** [comment]
Yeah tried a reinstall and it defaults to 14.04. I'm happy for this issue to be closed as I'm using out of date software.

**Comment by kytrinyx** [comment]
Thank you for your patience with this @connermcd, and thanks so much for laying out all the detailed steps, @NobbZ!

**Comment by absurdist** [comment]
for anyone else coming here searching about installing exercism in wsl bash, I had not issues when downloading the client in bash using wget:

>wget https://github.com/exercism/cli/releases/download/v3.0.12/exercism-linux-64bit.tgz

then following the walk through instructions on the exercism site

>tar -xf exercism-linux-64bit.tgz
...
