### ISSUE TITLE
Contributors webhook not working

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism.io#4039]
## Error in Exercism V2

**ActionController::ParameterMissing** in **api/webhooks/contributors#create**
param is missing or the value is empty: payload

[View on Bugsnag](https://app.bugsnag.com/exercism/exercism-v2/errors/5b48dbbbc5b8680017719e38?event_id=5b55c5a10027266ca41a0000&i=gh&m=ci)

## Stacktrace

    app/controllers/api/webhooks/contributors_controller.rb:26 - payload_params
    app/controllers/api/webhooks/contributors_controller.rb:7 - create

[View full stacktrace](https://app.bugsnag.com/exercism/exercism-v2/errors/5b48dbbbc5b8680017719e38?event_id=5b55c5a10027266ca41a0000&i=gh&m=ci)

*Created by Jeremy Walker via Bugsnag*

**Comment by iHiD** [comment]
@ccare @kntsoriano Could one of you look at this pls?

**Comment by kntsoriano** [comment]
@iHiD Starting on this now.

**Comment by kntsoriano** [comment]
@kytrinyx @iHiD 

1. It seems that the way that the contributors webhook was coded was to respond to the [Pull Request Event](https://developer.github.com/v3/activity/events/types/#pullrequestevent) rather than the [Push Event](https://developer.github.com/v3/activity/events/types/#pushevent). I determined this by looking at the test fixtures. Can we check if we’ve set up the webhooks to send to the contributors endpoint on Pull Request Events and not on Push Events?
2. If we wanted to instead use Push Events, can you describe what we need in to determine in order to qualify what a contribution is?

**Comment by kytrinyx** [comment]
I thought I responded to this. Yes, I think we need to use the Push event. That obviously complicates things, as the committer and pusher are not the same. There is an array of `commits` that we could loop through, but those are not connected to the GitHub user.

Let's just use the `pusher` -- it's going to be correct most of the time.

**Comment by iHiD** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ActionController::ParameterMissing** in **api/webhooks/contributors#create**](https://app.bugsnag.com/exercism/exercism-v2/errors/5b48dbbbc5b8680017719e38?event_id=5b635cd60029b81754830000&i=gh&m=ra)

**Comment by iHiD** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**ActionController::ParameterMissing** in **api/webhooks/contributors#create**](https://app.bugsnag.com/exercism/exercism-v2/errors/5b48dbbbc5b8680017719e38?event_id=5b635d500029d1274fc10000&i=gh&m=fx)
