### ISSUE TITLE
Faulty login

### ISSUE THREAD

**Issue by dmagro** [exercism/exercism.io#4049]
Last saturday I've tried to login with my github account. I was able to do what I think it's supposed to be the normal account setting flow. But something went wrong when I tried to set my profile picture, which was the github one but I did want to change it. After doing that, something wen wrong.

With this I'm unable to interact with my account, even after doing a reset password.
The following image depicts the screen that I'm redirected to after I login into my account.
![capturar](https://user-images.githubusercontent.com/4038443/43098870-4b46863e-8eb8-11e8-81c6-bdc41c12cd8c.PNG)
From this page I can't access any other endpoint and only after deleting the exercism cookies I can access the public homepage in order to try to login again.

I guess it's some problem of a new login, or account validation brought by the new web app because I didn't have this problem before.

**Comment by iHiD** [comment]
@dmagro This sucks. Sorry. 

So, uploading a photo totally screwed with your account because we couldn't deserialize the photo from the database.
1) This should be caught by https://github.com/exercism/website/pull/224
2) I've opened https://github.com/exercism/exercism.io/issues/4057 to try and work out what caused it.
3) Would you mind *not* updating your profile photo for now so we can try to debug it.

I will deploy this shortly so you should be good to go within the next few minutes. Thanks and sorry!

**Comment by dmagro** [comment]
Sure thing @iHiD! Thanks for the help!
