### ISSUE TITLE
Green balloon icon not doing anything

### ISSUE THREAD

**Issue by bdf74** [exercism/exercism.io#4052]
![cattura](https://user-images.githubusercontent.com/1384899/43102700-18c0d660-8ecc-11e8-8bc6-f8f5d99cf40e.JPG)

I'm using Windows 10 and Firefox, and I'm on Independent Mode.
I see this icon on all of my solutions, but when I click on it nothing happens. I'm just wondering what does it mean? Do I have a message waiting somewhere? The bell icon doesn't show any new notification.
Thanks!

**Comment by pgaspar** [comment]
From my understanding from looking at some submissions, the 1 in the green box indicates this is the first iteration, and the blank comment bubble indicates there’s no comments in this iteration.

**Comment by iHiD** [comment]
> I'm just wondering what does it mean? Do I have a message waiting somewhere? 

It means I forgot the `if` clause to only show it if there were comments! All the examples I tested on had comments on all iterations. Sorry.

Fixed by https://github.com/exercism/website/pull/223

> Also, the published solution shows 0 comments.

The comments on the published solutions are different. These are public comments, not your private conversation with mentors.
