### ISSUE TITLE
Adding migration guide in the help section in the footer

### ISSUE THREAD

**Issue by MohamedHajr** [exercism/exercism.io#4056]
I went throw a headache until I figure out that I needed to redownload the exercise in order to be able to submit solutions again, and I didn't figure out this until I reached out in the CLI repo and found out about this link [](https://exercism.io/cli-v1-to-v2 ) so if we can add this link to help section in the footer that would be great for anybody trying to migrate.

**Comment by kytrinyx** [comment]
@MohamedHajr I'm sorry that this has been confusing!

We have a migration guide, and the latest version of the CLI, which was released 7 days ago, will point you to it if you try to submit without metadata.

Please run `exercism upgrade` if you are on Linux or Mac, or follow the installation instructions in the [interactive walkthrough](https://exercism.io/cli-walkthrough), if you're on Windows (since the upgrade command was broken on Windows until 3.0.5).

**Comment by kytrinyx** [comment]
The FAQ contains a link to the migration page. I've opened a PR to clarify this.
https://github.com/exercism/website-copy/pull/254

Since I think we've got this covered going forward, I'm going to go ahead and close this.

**Comment by iHiD** [comment]
I've also added links to the footer for both CLI and Walkthrough.
