### ISSUE TITLE
Allow for collaboration on submissions

### ISSUE THREAD

**Issue by verdammelt** [exercism/exercism.io#969]
It would be great if when I've worked on a submission with another user, then we can submit it "together".

I'd like to see the assignment on both my page and my collaborator's page. Conceptually the submission should be 100% shared. The nit-picks would be shared, if one collaborator submitted it would still be shared.

Also it would be necessary for any collaborator to be able to leave the collaboration. 

Another interesting feature would be to allow the collaborations to diverge.

**Comment by kytrinyx** [comment]
I've decided to close some of the issues that I would like to get to, but that aren't about getting the basics of exercism right (onboarding, rich conversations, quality feedback).

I'm adding the tag "future roadmap" so that we can find all of these great ideas when we're ready for them.

https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md#future-roadmap
