### ISSUE TITLE
Allow for collaboration on nit-picking

### ISSUE THREAD

**Issue by verdammelt** [exercism/exercism.io#970]
Allow for N people to collaborate on reading code and submitting the nit-picks.

**Comment by kytrinyx** [comment]
I've decided to close some of the issues that I would like to get to, but that aren't about getting the basics of exercism right (onboarding, rich conversations, quality feedback).

I'm adding the tag "future roadmap" so that we can find all of these great ideas when we're ready for them.

https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md#future-roadmap
